### ISSUE TITLE
[RFC] Explicit N/S and E/W suffixes

### ISSUE THREAD

**Issue by maandree** [jonls/redshift#107]
To avoid the error where users on the west side of the
prime meridian specify `lon=100` instead of `lon=-100`
(for example), and analogously with lat if that also
happens, I suggest that a warning should emitted unless
`lat` is suffixed with [nNsS] and `lon` is suffixed with [eEwW].
A warning should also be emitted if `-` is.

So for example, instead of `-l 50:-100` on would write
`-l 50N:100W` or `-l 50n:100w`. `-l 50n:-100w` would also
be accepted but emits a warning because it is ambiguous.

**Comment by jonls** [comment]
This seems to have solved most of the confusion about this.
