### ISSUE TITLE
redshift 1.7: Unable to get location from provider.

### ISSUE THREAD

**Issue by bitliner** [jonls/redshift#12]
Sometimes, starting redshift, i receive the following error that prevents redshift to start
```
** (process:31477): WARNING **: Metadata for error domain "geoclue-error-quark" already registered

Started Geoclue provider `Geoclue Master'.
Using provider `geoclue'.
Could not get location (3 retries left): Geoclue master client has no usable Position providers.
Unable to get location from provider.

```

**Comment by jonls** [comment]
I'm closing this one since the latest version has a GeoClue2 provider that waits for a location to become available. In addition, `redshift-gtk` should provide better feedback on errors.
