### ISSUE TITLE
Random temperature adjustment failure using WinGDI (windows)

### ISSUE THREAD

**Issue by dan9550** [jonls/redshift#121]
Getting some errors trying to run on the Windows Technical Preview.

```
C:\Users\Danny\Downloads>redshift -v -c C:\Users\Danny\Documents\redshift.conf
Location: 0, 0
Temperatures: 6500K at day, 5000K at night
Brightness: 1.00:1.00
Gamma: 1.000, 1.000, 1.000
Status: Enabled
Period: Night
Color temperature: 6500K
Brightness: 1.00
Period: Night
Color temperature: 6484K
Brightness: 1.00
Unable to set gamma ramps.
Temperature adjustment failed.
```

Here is my config:

```
; Global settings for redshift
[redshift]
; Set the day and night screen temperatures
temp-day=6500
temp-night=5000

; Enable/Disable a smooth transition between day and night
; 0 will cause a direct change from day to night screen temperature. 
; 1 will gradually increase or decrease the screen temperature
transition=1

; Set the screen brightness. Default is 1.0
;brightness=0.9
; It is also possible to use different settings for day and night since version 1.8.
;brightness-day=0.7
;brightness-night=0.4
; Set the screen gamma (for all colors, or each color channel individually)
;gamma=0.8
;gamma=0.8:0.7:0.8

; Set the location-provider: 'geoclue', 'gnome-clock', 'manual'
; type 'redshift -l list' to see possible values
; The location provider settings are in a different section.
location-provider=manual

; Set the adjustment-method: 'randr', 'vidmode'
; type 'redshift -m list' to see all possible values
; 'randr' is the preferred method, 'vidmode' is an older API
; but works in some cases when 'randr' does not.
; The adjustment method settings are in a different section.
adjustment-method=wingdi

; Configuration of the location-provider:
; type 'redshift -l PROVIDER:help' to see the settings
; ex: 'redshift -l manual:help'
[manual]
lat=0
lon=0

; Configuration of the adjustment-method
; type 'redshift -m METHOD:help' to see the settings
; ex: 'redshift -m randr:help'
; In this example, randr is configured to adjust screen 1. 
; Note that the numbering starts from 0, so this is actually the second screen.
[randr]
screen=0
```

**Comment by LordJABA** [comment]
Have a same issue. The adjustment is working despite the errors. The problem is that after the error program exits - it's one time adjustment not continuous one, because of that. I got two screens in "expand" mode

**Comment by akuntsch** [comment]
Same issue as @LordJABA here. 

I'm on Windows 10 running a dual monitor setup in extended mode and I always get the following error messages:

    C:\Users\Alex\Desktop>redshift.exe -O 4500
    Using method `wingdi'.
    Unable to set gamma ramps.
    Temperature adjustment failed.

The manual temperature adjustment does however work on both screens. 
Continuous adjustment doesn't work because the program exits after the error messages.

**Comment by dev7355608** [comment]
This should be fixed in #524. #296 will not help.

**Comment by diegorodriguezv** [comment]
Hey. It seems to me this bug is fixed since version 1.11.

**Comment by diegorodriguezv** [comment]
Sorry. Version 1.11 wasn't available for windows. I was referring to the master branch build.

**Comment by dev7355608** [comment]
This bug was fixed in #524. The issue can be closed now.

**Comment by jonls** [comment]
Thanks, closing :+1:

**Comment by diegocr** [comment]
Some clue when can we expect a new Windows build please? :)

**Comment by jonls** [comment]
@diegocr The latest build from master branch already has this fixed (https://github.com/jonls/redshift#latest-builds-from-master-branch). There's going to be Windows builds for the [1.12](https://github.com/jonls/redshift/milestone/1) release which I think I'll be able to get out very soon.

**Comment by diegocr** [comment]
Oh, awesome! Thanks a lot!
