### ISSUE TITLE
Redshift doesn't consider ambient light sensor.

### ISSUE THREAD

**Issue by programmin1** [jonls/redshift#124]
Gtk-redshift is great - a very interesting application. One problem I noticed was that if internet isn't connected when starting, it doesn't work and doesn't seem to give a warning. I'm wondering why it uses geolocation instead of taking a picture from webcam or light sensor, to check if you're in bright sunlight, in bright indoor lights, or in a dark room.

**Comment by pickfire** [comment]
> Concerning light sensor, one could buy cheap light sensor and connect it to a Raspberry Pi or an Arduino, or other similar platform.

Actually, redshift doesn't work on Raspberry Pi currently.
https://github.com/jonls/redshift/issues/257

**Comment by Goury** [comment]
Any news on this one?

IMO, redshift shouldn't even attempt at accessing a webcam or something like this, but rather just read some sensor API and another piece of software should handle requests under that API.
This way (unix way, by the way) you won't have to add too too much stuff to redshift and it would (should) be easy for people with custom sensors to write a small program to just handle some API requests.

**Comment by cypa** [comment]
analyze manual brightness changes history?

**Comment by jonls** [comment]
@Goury if a library like this was available we could consider using it but I haven't heard of or seen anything like this. We can reconsider this issue if something like this becomes available.

**Comment by Goury** [comment]
@jonls 
TF are you closing this issue?
[Clightd](https://github.com/FedeDP/Clightd) is out there for almost a decade.

99% of people've never heard of GNU GPL v3, does this mean Redshift doesn't exist?
