### ISSUE TITLE
Continuously update position from location provider

### ISSUE THREAD

**Issue by jonls** [jonls/redshift#13]
Redshift should continuously update the position from the location provider instead of only updating when the program starts.

**Comment by darkk** [comment]
I use cron and several scripts to achieve desired behavior.

- [redshift.conf](https://github.com/darkk/home/blob/master/.config/upstart/redshift.conf) for `upstart` manages redshift process
- [env.session](https://github.com/darkk/home/blob/master/bin/env.session) creates proper environment for `cron` job
- [geolocate](https://github.com/darkk/home/blob/master/bin/geolocate) queries `NetworkManager` for WiFi AP list and fetches approximate location from Yandex and Mozilla API
- [update-geolocation](https://github.com/darkk/home/blob/master/bin/update-geolocation) glues these scripts together

**Comment by biji** [comment]
Yes,

redshift should only update once at start, or configurable manual location

![image](https://cloud.githubusercontent.com/assets/665559/15269421/1c42e2a8-1a28-11e6-8b20-a5a3dc7a7c3d.png)
