### ISSUE TITLE
1.9.1 And Opening nvidia-settings - Desktop Changes Brighter Then Darker...

### ISSUE THREAD

**Issue by ghost** [jonls/redshift#130]
Hi,

These are my specs;

Asus G75VW laptop - Nvidia GTX 660M
Slackware 14.1 x86_64
Redshift 1.9.1
python3-3.4.1
nvidia-driver-340.24

When I run, nvidia-settings the desktop gets brighter as if redshift wasn't running for a few seconds then it gets dark again, back to my defined settings in `~/..config/redshift.conf; temp-day=5700`

I'd like to be able to stop this so the desktop doesn't constantly change brightness when opening nvidia-settings...

**Comment by moulei** [comment]
Hi,

Did something change in 1.10? I wanted to report to say that if I run ```nvidia-settings``` now,  the brightness doesn't change! :)

**Comment by moulei** [comment]
My mistake, I forgot I was using the cmd; ```nvidia-settings --no-config```

The brightness still changes without --no-config
