### ISSUE TITLE
Dual Monitors don't seem to be supported

### ISSUE THREAD

**Issue by yjukaku** [jonls/redshift#14]
Only one of my monitors seem to change color. Can anyone else confirm this?

**Comment by CMCDragonkai** [comment]
My redshift shows drm, randr, vidmode and dummy. And when running it uses randr mode, however it is still only applied to one of my X screens, and not the other X screen.

**Comment by Ericson2314** [comment]
I have two "identical" screens, and it seems not to affect them all equally. I think the colors do seem the same with redshift off, which makes me think its not a color calibration issue, but let me confirm that when its less grating to look at both screens without redshift :).

**Comment by noah** [comment]
For me, this worked for dual-monitor setup using Awesome Window Manager:
`
redshift -m vidmode
`

**Comment by vlatkoB** [comment]
@noah Thanks. That works for me too, I'm on Arch

**Comment by br4nnigan** [comment]
try using a [conf](https://raw.githubusercontent.com/jonls/redshift/master/redshift.conf.sample) and the screen property

but you have to explicitly include it using -c option apparently
