### ISSUE TITLE
Screen sometimes briefly turns back to normal temperature

### ISSUE THREAD

**Issue by Chiel92** [jonls/redshift#143]
I'm using `redshift-gtk` on Ubuntu 14.04.

Sometimes when I do something, like starting a movie, deleting a file, starting a youtube video, the screens turns back to the normal temperature for a few seconds.
Then it turns to the redshifted temperature again.
This can be quite disturbing, especially if the difference in temperature is big.

Any ideas on what might cause this?

**Comment by jonls** [comment]
I'm closing this issue now. I have opened #154 to track the possible workaround of lowering the time between gamma adjustments.
