### ISSUE TITLE
Dark mode for Yosemite - OS X

### ISSUE THREAD

**Issue by DomT4** [jonls/redshift#148]
This is more of a 'feature request' than an issue, as such.

Your new OS X integration works great. No build errors, nothing even slightly not working as far as I can see. Builds fine, runs fine, even have a ` launchd ` script setup to run it automatically at login and that works fine. Awesome.

One feature I'd miss from ` f.lux ` though, and would be completely awesome to get integrated into ` redshift ` if possible, is the automatic shift to dark mode whenever a certain time or temperature is passed. There's some nifty code [here](https://github.com/sindresorhus/dark-mode) which explores how to trigger it from the command-line, which is permissively licensed, so perhaps that could be a useful resource to kick off from?

**Comment by jonls** [comment]
I have put the script in this Gist: https://gist.github.com/jonls/02ff1b9874c7f5e4203b
