### ISSUE TITLE
Geoclue2: Set DesktopId for compatibilty with Geoclue >= 2.1.0

### ISSUE THREAD

**Issue by selmf** [jonls/redshift#153]
Hi,

geoclue2 versions >= 2.1.0 need a mandatory DesktopID to be set or the client won't work. This is rather trivial, so please forgive me for not making a proper patch or doing a pull request. Adding the following code snippet after setting the distance threshold in location-geoclue2 does the trick:

```
/* Set DesktopId */
	error = NULL;
	GVariant *ret_d =
		g_dbus_proxy_call_sync(geoclue_client,
				       "org.freedesktop.DBus.Properties.Set",
				       g_variant_new("(ssv)",
						     "org.freedesktop.GeoClue2.Client",
						     "DesktopId",
						     g_variant_new("s", "redshift")),
				       G_DBUS_CALL_FLAGS_NONE,
				       -1, NULL, &error);
	if (ret_d == NULL) {
		g_printerr(_("Unable to set DesktopId: %s.\n"),
			   error->message);
		g_error_free(error);
		g_object_unref(geoclue_client);
		g_object_unref(geoclue_manager);
		return;
	}
```

Hope this helps.

Regards,

selmf

**Comment by jonls** [comment]
Thanks, fixed. Unfortunately this property was not defined for earlier version of GeoClue2 so your code didn't quite work in that case. I am simply ignoring the error for now.
