### ISSUE TITLE
redshift 1.10 goes to zero temp then rolls over to 4B k.

### ISSUE THREAD

**Issue by spikebike** [jonls/redshift#163]
I'm near Sacramento CA USA (38:-121).  I build 1.10 from source on an ubuntu-14.04 machine with the nvidia binary driver.

I tried this:
$ redshift -l 38:-121 -t 5700:3600 -g 0.8 -m randr -v 
Location: 38.00 N, 121.00 W
Temperatures: 5700K at day, 3600K at night
Solar elevations: day above 3.0, night below -6.0
Brightness: 1.00:1.00
Gamma (Daytime): 0.800, 0.800, 0.800
Gamma (Night): 0.800, 0.800, 0.800
Status: Enabled
Period: Night
Color temperature: 6317K
Brightness: 1.00
Color temperature: 6134K
Color temperature: 5951K
Color temperature: 5768K
Color temperature: 5585K
Color temperature: 5402K
Color temperature: 5219K
Color temperature: 5036K
Color temperature: 4853K
Color temperature: 4670K
Color temperature: 4487K
Color temperature: 4304K
Color temperature: 4121K
Color temperature: 3938K
Color temperature: 3755K
Color temperature: 3572K
Color temperature: 3389K
Color temperature: 3206K
Color temperature: 3023K
Color temperature: 2840K
Color temperature: 2657K
Color temperature: 2474K
Color temperature: 2291K
Color temperature: 2108K
Color temperature: 1925K
Color temperature: 1742K
Color temperature: 1559K
Color temperature: 1376K
Color temperature: 1193K
Color temperature: 1010K
Color temperature: 827K
Color temperature: 644K
Color temperature: 461K
Color temperature: 278K
Color temperature: 95K
Color temperature: 4294967209K
...

The result is the screen gets dimmer, dimmer, black, then starts flashing.  Sometimes I can recover it by killing it, sometimes not.

**Comment by jonls** [comment]
This might be related to #162?

**Comment by jonls** [comment]
This was fixed when merging the patch for #162.
