### ISSUE TITLE
Unable to run on Gnome 3.14

### ISSUE THREAD

**Issue by orschiro** [jonls/redshift#165]
Hi there,

Many thanks for this fantastic program!

I tried launching the `redshift` command on Gnome 3.14. However, it fails with the following message:

```
~ ❯ redshift
Screen 1 could not be found.
Failed to start adjustment method randr.
```

I only have one single laptop screen:

```
~ ❯ xrandr
Screen 0: minimum 8 x 8, current 1280 x 800, maximum 32767 x 32767
LVDS1 connected primary 1280x800+0+0 (normal left inverted right x axis y axis) 261mm x 163mm
   1280x800      60.00*+
   1024x768      60.00  
   800x600       60.32    56.25  
   640x480       59.94  
DP1 disconnected (normal left inverted right x axis y axis)
DP2 disconnected (normal left inverted right x axis y axis)
DP3 disconnected (normal left inverted right x axis y axis)
HDMI1 disconnected (normal left inverted right x axis y axis)
HDMI2 disconnected (normal left inverted right x axis y axis)
VGA1 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
```

Any ideas what goes wrong?

Thank you!

Robert

```
redshift 1.10-1
gnome-session 3.14.0-1
```

**Comment by jonls** [comment]
You don't have a screen 1, you only have screen 0 as you can see from the `xrandr` output. Check your configuration.

**Comment by orschiro** [comment]
What a stupid mistake. Sorry for that.

Changed screen=1 to screen=0

Regards,

Robert

On 01/20/2015 04:44 PM, Jon Lund Steffensen wrote:
>
> You don't have a screen 1, you only have screen 0 as you can see from 
> the |xrandr| output. Check your configuration.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jonls/redshift/issues/165#issuecomment-70674415>.
>

-- 
Sharing my passion & inspiration for

#sustasty lifestyles #transitions
#opensource #degrowth / Love
#bouldering

Flying is old-school and the
world cannot be saved part-time

Co-Creator of @MindfulMeerkats

www.robert.orzanna.de
twitter.com/@orschiro
