### ISSUE TITLE
Color temperature is temporarily reset constantly

### ISSUE THREAD

**Issue by RogerThiede** [jonls/redshift#166]
The color temperature of my screen is properly changed from the daytime setting to nighttime setting, but will often reset to the daytime setting for half a second.  It's possible that it is temporarily reseting to the screen's default color temperature regardless of what the daytime setting is.

I have not been able to reliably reproduce this issue, but it most often occurs when opening a new Google Chrome browser tab or opening a Microsoft Office Application.

redshift 1.10 using adjustment-method=quartz on OS X 10.10.1 (14B25) on MacBook Pro (Retina, Mid 2012)

**Comment by jonls** [comment]
See #143. In short, we cannot lock the gamma ramps so there is nothing we can do to disable the gamma adjustments made by other programs. The redness effect will kick back in after a few seconds when Redshift updates the gamma ramps.
