### ISSUE TITLE
README.md still refers to HACKING rather than HACKING.md

### ISSUE THREAD

**Issue by hartwork** [jonls/redshift#168]
Title says it all :)

Impressive list of changes for 1.10 by the way. Good work!

Best, Sebastian

**Comment by plsng** [comment]
https://github.com/jonls/redshift/pull/169/files

**Comment by jonls** [comment]
Fixed in 7818b4aa74ef84f2c68b27a5abbbd1d1d26eba73 by linking to HACKING.md.
