### ISSUE TITLE
redshift-1.10-windows-x86_64 doesn't work

### ISSUE THREAD

**Issue by Matthaiks** [jonls/redshift#171]
It refuses to start, gives no messages in cmd. I'm using Windows 8.1.

**Comment by mbaz** [comment]
I confirm; I have the same problem in Windows 7.

**Comment by jonls** [comment]
Thanks, I have compiled this one using the same setup with mingw (cross-compiling on linux) as I used for the previous versions. I don't have a Windows 7 or 8 box ready so I cannot do any tests right now. Any more information would be appreciated if anybody knows how to investigate this issue on Windows.

**Comment by mbaz** [comment]
Thanks for the reply. I can't install mingw on the only windows machine I
have access to, but I'll be happy to run any tests you need.

**Comment by SkyLined** [comment]
I ran it in a debugger: it is a clean exit. `redshift.exe -h` produces no output. Could it be that you are failing to output an error message? If you can build a version that outputs some debug logging, we could run that and tell you what it says...

**Comment by davidcie** [comment]
Can confirm the same behaviour on my Windows 7 x64. No output is produced irrespective of the command line options given, and nothing of interest appears in the Event Viewer. Earlier version, 1.9.1 x86 and 1.9.1 x64 work as expected.

Will try to have a look around to see what could be the problem if time permits.

**Comment by georgerbr** [comment]
Got the same behavior in Windows 8.1 Pro x64 - no output.
This is what I get when I run `redshift -l manual:help`:
```
C\redshift-1.10-x86_64>redshift -l manual:help
redshift:./.libs/lt-redshift.c:233: FATAL: couldn't find redshift.
```

1.9.1 works fine.

By the way, the executable file size for 1.9.1 is 210 kB, whereas for 1.10 it's 36 kB.

**Comment by davidcie** [comment]
Had a few moments to come back to the problem. The same thing happens when compiled under MSYS2 (can provide step-by-step instructions to more adventurous types if needed). But it struck me how all the right files were compiled, just not linked. This led me to trying the `--disable-shared` option for `./configure` and presto, `make` dutifully compiled a beefier, fully working redshift!

For the record, here is the full `./configure` command I used:

    ./configure --enable-wingdi --disable-shared --disable-geoclue2 --disable-nls

**Comment by jonls** [comment]
Thanks @davidcie ! I have rebuilt 1.10 using `--disable-shared` and it does indeed seem to be a more reasonable size (although still a bit smaller than 1.9.1). I cannot test it right now but I'll upload it under the 1.10 release. Please report back if any of you can test it.

**Comment by davidcie** [comment]
@jonls it works! Its size is a little weird — I got a 429KB file rather than 143KB but I guess it's down to compiler flags (I left them at their defaults). Thanks for looking into this and making this sweet little app available. You've gifted us all with countless hours of sleep.

**Comment by Matthaiks** [comment]
Yes, it works. Thanks!
