### ISSUE TITLE
Exposing if redshift is disabled or not via 'redshift -p'

### ISSUE THREAD

**Issue by sognetic** [jonls/redshift#172]
It would be nice if 'redshift -p' showed whether redshift has been paused via a SIGUSR1 inter-process signal.

**Comment by Epitrochoid** [comment]
I'd love this feature as well, it would make redshift-gtk style widgets easy for arbitrary applications. In my case I'd like to be able to toggle it through Bar Ain't Recursive without needing complicated methods of polling for current status.

**Comment by maandree** [comment]
USR1 is used for enabling/disabling redshift.
USR2 is proposed to be added via a pull request to reload settings.

`redshift -p` (and `redshift -pv`) prints what settings would be applied if redshift was to be started,
not what settings are currently applied. Remember, the settings can be edited in the command line
and the configuration file can be edited.

RTMIN (or INFO if available) (and a command line flag) could be added
to make redshift dump its state (enable, geolocation, sun's elevation, colour adjustments, &c).
However, I fail to see how this is useful. For the information to be disabled in the terminal,
you must have the terminal it was launched from open. And to parse the information you
need to be the process that started it (or have hijacked redshift's stderr), but if you are
the process that started redshift, you just need to add `-v` and you get everything from
redshift's stderr.

@Epitrochoid 
No, it is the local `int disabled` in `run_continual_mode`.

**Comment by jonls** [comment]
I know this would be really useful but we'll get this with D-Bus when we get to that. At this point I don't want to complicate the `-p` mode any further.
