### ISSUE TITLE
help

### ISSUE THREAD

**Issue by stevetwenty** [jonls/redshift#173]
fred@localhost redshift-1.10]$ redshift
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  150 (XFree86-VidModeExtension)
  Minor opcode of failed request:  19 (XF86VidModeGetGammaRampSize)
  Value in failed request:  0x17
  Serial number of failed request:  12
  Current serial number in output stream:  12
[fred@localhost redshift-1.10]$ redshift -V
redshift 1.10

**Comment by jonls** [comment]
Did you try the randr method?

**Comment by stevetwenty** [comment]
It seems to work fine with that, thanks.
