### ISSUE TITLE
Package on Ubuntu outdated?

### ISSUE THREAD

**Issue by acutbal** [jonls/redshift#187]
I'm not sure if this is the right place to ask, so I apologize if I cause some inconvenience... I wonder if could it be possible to update the app version on the Ubuntu repositories. The actual v. 1.8 is outdated, from March 2014.

Thank you very much and congrats for the app!! :D

**Comment by jonls** [comment]
Ubuntu is responsible for the official repositories so I have no influence on the version offered there. From [a search for redshift in packages.ubuntu.com](http://packages.ubuntu.com/search?keywords=redshift&searchon=names&suite=all&section=all) it does appear that 1.9.1 is available although for Vivid, the upcoming Ubuntu release. Ubuntu usually does not update Redshift in the middle of a release so you will only get an updated version of Redshift when you are updating to a new Ubuntu release.

**Comment by acutbal** [comment]
Ok, I didn't know this, I thought that developers updated themselves the apps, like Google Play o Appstore. Thank you very much for the info, very best regards!! :+1:
