### ISSUE TITLE
redshift picking color temperature far above range.

### ISSUE THREAD

**Issue by bj0** [jonls/redshift#188]
I just did a git checkout and built redshift, then ran it with:
./redshift -v -l 34:-112 -t 5700:2500 -o

The output shows it is reading the temperatures right, but then it sets the display to a temp of 19515K.

Here is the output:

>Location: 34.00 N, 112.00 W
>Temperatures: 5700K at day, 2500K at night
>Solar elevations: day above 3.0, night below -6.0
>Brightness: 1.00:1.00
>Gamma (Daytime): 1.000, 1.000, 1.000
>Gamma (Night): 1.000, 1.000, 1.000
>Solar elevation: 41.856279
>Period: Daytime
>Color temperature: 19515K
>Brightness: 1.00

**edit:** it is currently 3:30 pm

**Comment by forivall** [comment]
I haven't tested it, but looking through the forks, this looks like a fix: https://github.com/christian-burger/redshift/commit/c611b95ea0c47b459900929ba7828db2e006cec7
