### ISSUE TITLE
Philips Hue support?

### ISSUE THREAD

**Issue by maandree** [jonls/redshift#189]
I got some Philips Hue I intend to play with. Some I wonder if there is interest of Philips Hue support for redshift?

**Comment by nathan7** [comment]
@maandree I wrote this for myself https://gist.github.com/nathan7/999ba12ccb95312f3fb4, though it requires some customisation (it expects a `my-redshift` script that supplies the position and range, and expects you to want to shift group 2 of the Hue controller at `192.168.197.192`)

**Comment by splitbrain** [comment]
Any chance this could be reopened? The gist above is unfortunately no longer available. It would be awesome to have adjust the room lights with the monitor.

**Comment by edef1c** [comment]
@splitbrain fixed the link, sorry!
