### ISSUE TITLE
Avoid finding the location every time the app runs

### ISSUE THREAD

**Issue by thewhitetulip** [jonls/redshift#191]
Currently the app checks the location of the user daily, it would be great to either
1. Create a config file by default and storing the user location into it once 
2. Giving an option to the user to just turn redshift on when they need so without looking up the location, because as far as I have used this app, it feels really good and shouldn't have any side effects

**Comment by maandree** [comment]
You can set your location in ~/.config/redshift.conf:
```ini
[redshift]
location-provider=manual
[manual]
lat=-50
lon=20
```
or specify your location in the command line
`redshift -l -50:20`

In these examples the latitude is 50°E and 20°N.

If you fill in the configuration file as suggested above,
you can select to use GeoClue from the command line
by running `redshift -l geoclue`. If you do not set
`location-provider=manual` in the command line,
you run `redshift -l manual` to use the location
entered in the configuration file instead of using GeoClue.

**Comment by thewhitetulip** [comment]
I know that, I wanted to suggest making an auto config file so everyone won't have to hack the config file for making the app work, I found a detailed version of config file on arch linux's wiki page

**Comment by plsng** [comment]
Do you mean you want to make redshift save the location automatically and reuse it for a while, until a certain amount of time has passed or the user explicitly instructs it to change location?

**Comment by thewhitetulip** [comment]
I want to autogenerate a config file and use it as default unless the user explicitly wants to say, change the parameters. Because it is highly unlikely that all of redshift's users do inter hemisphere travel, so taking majority into consideration we should create a config file, and in give an option to change it to the user. The option to toggle redshift is already available.

Also the reason why I started this issue is that you maybe live in the part of the world where internet is ever present, for a day I wasn't having internet connection redshift used to not start because it coudn't resolve the gps provider that you use, it shouldn't happen because I had been using redshift for a week now and it should have stored my location or at least started redshift by default and provide a way to say pause it.

If you haven't please look into the Twilight android app, that app doesn't require the Internet for setting lattitude or logitude, they ask you when is the time you want this app to run, this is amazing because it won't require a dependency like the Internet! you can just provide the time in your local timezone in which you want the app to run.

**Comment by simonnagl** [comment]
I think it is not a good idea to generate a config file at the first start. It could make the user think red shift automatically detects the color temperature in the room. In my opinion it is important to make the user think what is the best configuration for him.

I am not quite sure what you mean with "when is the time you want this app to run". Normally redshift runs in the background and calculates the time for shifting temperature or brightness from the location.

What's many a good idea is to give add a parameter when to switch temperature.
For example in the morning someone works in a office with daylight. After lunch he always uses a lamp and no daylight for some reason. Then it should be great to switch the brightness at 12.

Is that the configuration you are looking for?

**Comment by thewhitetulip** [comment]
Yes, precisely, my point is that redshift should work without the Internet that's it. Doesn't matter actually how you handle the details.

**Comment by simonnagl** [comment]
Then @maandree already gave the answer. Set your location to redshift.conf manual. Then redshift won't do anything online.

**Comment by thewhitetulip** [comment]
My point is Redshift should do so automatically or start by default, why make the user create a text file you can do this simple thing

if internet is present then fetch the latitude/longitude else start redshift by default. Because without the internet and without the config file there won't be a point in installing redshift
