### ISSUE TITLE
Missing bootstrap script in source?

### ISSUE THREAD

**Issue by helgatheviking** [jonls/redshift#192]
I'm definitely a linux rookie, but when trying to install redshift from the 1.10 source, the instructions say to run the `bootstrap` script, but there doesn't appear to be a `bootstrap` script in the redshift-1.10.tar.xz.

**Comment by jonls** [comment]
You only need the `bootstrap` script when you check out the source from Github. When using the source from a tar-ball you can simply run `configure`.

**Comment by helgatheviking** [comment]
Thanks for clearing that up.
