### ISSUE TITLE
Install instructions for OSX

### ISSUE THREAD

**Issue by syndbg** [jonls/redshift#193]
As title suggests.

**Comment by jonls** [comment]
The easiest way to install it is probably using [Homebrew](http://brew.sh/). But if you decide to build it manually from source it is built [exactly as on other platforms](https://github.com/jonls/redshift/blob/master/HACKING.md). Note that none of the optional dependencies are supported on OS X, only the quartz gamma adjustment and the CoreLocation location provider will be compiled in. Also, the GUI is not supported either.

**Comment by syndbg** [comment]
@jonls Thank you very much!

I think about submitting a PR for README.md, describing the various methods of installing `redshift` on most platforms. What do you think about it?

**Comment by jonls** [comment]
@syndbg Sure, sounds good.
