### ISSUE TITLE
Brightness is wrong?

### ISSUE THREAD

**Issue by deterenkelt** [jonls/redshift#195]
When I adjust brightness with redshift, it seems like it decreases contrast as well. Brightness also looks different for same values set in redshift and in the monitor settings/PCI bus. It looks grayish, but the gamma is not changed, checked with `-pv`. 
Gentoo ~amd64, redshift v1.10.

**Comment by jonls** [comment]
Redshift does not adjust the screen backlight when you set brightness! This is probably why it looks different. It is simply changing the gamma ramps to simulate a lower brightness which is useful for screens that only allow very coarse brightness adjustments. You should really adjust your screen through the normal backlight settings if you can.

**Comment by deterenkelt** [comment]
> Redshift does not adjust the screen backlight when you set brightness!
Then why call it brightness.
> You should really adjust your screen through the normal backlight settings if you can.
I’d use redshift to decrease brightness after sunset, not the colour temperature. And I can’t do that wince this is not a laptop and xbacklight doesn’t work.

**Comment by jonls** [comment]
It should probably be called "fake brightness" or something. If xbacklight doesn't work then Redshift wouldn't be able to adjust the backlight either. If xbacklight does work you can use a hook to run any command at sunset.

**Comment by deterenkelt** [comment]
Er… Is there a way then to somehow fix the gamma adjustments so it wouldn’t look so grayish and contrast-less? In twilight it is okay, but at night I have to strain the sight sometimes.

**Comment by jonls** [comment]
Perhaps you can experiment with a different gamma setting at night? When you set the brightness Redshift simply scales the output values down to produce less light from the screen.

**Comment by deterenkelt** [comment]
I’ll look into it.
