### ISSUE TITLE
Redshift ignores custom ICC profiles on OSX

### ISSUE THREAD

**Issue by Argon-** [jonls/redshift#210]
Hi,
I'm using a custom ICC profile (I call the one auto-generated by OSX for each display "default" or non-custom) and tested redshift with a configuration file like

    transition=0
    temp-day=6500
    temp-night=6500
    ... (no brightness or gamma changes)

So in theory activating redshift now should change nothing at all.
However, activating redshift seems to apply the default, OSX-generated ICC profile which is noticeably more greenish than my normal one. As expected, there is no change in "brightness"/gamma or color temperature, but my own, custom ICC profile is no longer applied.
It would be great if redshift honored the user-selected ICC profile (per display).

**Comment by maandree** [comment]
This is true on all platforms. You have to specify the gamma adjustments to keep the colour correction. But this assumes that gamma adjustments will do.

This is a patch somewhere to solve this by assuming the colour correction is already applied. But that match cannot be merge at the moment. It is out of date.

**Comment by Argon-** [comment]
Unfortunately, gamma adjustments are not sufficient to approximate my ICC profile.

**Comment by maandree** [comment]
> Unfortunately, gamma adjustments are not sufficient to approximate my ICC profile

No, flatscreens do not actually have gamma curves.

> Ah, yes, this is probably easier than querying and using ICC profiles: just some kind of configuration option to define whether to apply color correction or not.

Precisely.

**Comment by maandree** [comment]
It appears the patch has already been applied. `preserve=1` under `[quartz]` section in the configuration file, or to the `-m` flag (`redshift -m quartz:preserve=1`).

**Comment by Argon-** [comment]
Oh, nice. It seems like this is not documented, though.
edit:// I take that back, it's just not present in the current 1.10 release. Going to test git HEAD, thanks!
