### ISSUE TITLE
.service files: invalid reference After=display-manager.service

### ISSUE THREAD

**Issue by genodeftest** [jonls/redshift#216]
redshift and redshift-gtk systemd service files both contain the line `After=display-manager.service`. Both are installed as systemd user files. display-manager.service is a systemd system service and thus cannot be found. Run `systemctl --user --all` to see it listed.

**Comment by aspiers** [comment]
I'm not sure this is (still) a problem; relevant links:

- https://superuser.com/a/1128905/104997
- https://www.youtube.com/watch?v=hq18daxTkLA

**Comment by genodeftest** [comment]
Me neither and I don't use redshift any more. I'll close this report then. Feel free to comment/reopen.
