### ISSUE TITLE
Current values

### ISSUE THREAD

**Issue by jornmo** [jonls/redshift#230]
If I run

    $ redshift -p

All I get is some standard values: 5500K brightness 1.0, even though I just ran

    $ redshift -O 3000 -b 0.6

Is there, or could we get a flag that returns the current setting?

**Comment by jonls** [comment]
You can run the second command line with `-v` to get more information about what is going on. The `redshift -p` does not connect to any currently running instances of redshift, instead it simply reports the values that would have been applied with the given parameters.

What specifically is the information you are looking for? It seems that you are using one-shot manual mode (`-O`) so there is no temperature calculation that `-p` could report on. You already have the temperature which is 3000K.

**Comment by jornmo** [comment]
I am trying to put together a GUI that can read the current status from one-shot mode, so that the user can know what Kelvin and brightness is being used at the moment.

**Comment by jornmo** [comment]
So, what I would like is a flag that returns the current values from the running instance :)

**Comment by jonls** [comment]
If you are using one-shot mode you already have the color temperature and the brightness, no? You supply them on the command line.

**Comment by jornmo** [comment]
Well, I could have. Or I could have used the GUI. If I only used the GUI and it never crashed or anything like that, it would just be a matter of keeping the values internally in the program. But, if I set it from the terminal at one point, and then decide to open the GUI, the GUI would not know what the current values Redshift is using.

**Comment by jornmo** [comment]
Hi again @jonls! Was my description clear enough? What do you think?

**Comment by jonls** [comment]
It's currently not possible to get the current values of a running redshift process, unless you do something like redshift-gtk where redshift is run as a child process and the stdout is continuously monitored for updates. There has been some work on a D-Bus solution in #54 which would probably let you do what you want, but there's no ETA on that feature.

**Comment by jornmo** [comment]
I see. OK, I will work with what's available then :) Takk for hjelpa :+1:
