### ISSUE TITLE
Redshift fails to autostart

### ISSUE THREAD

**Issue by Yanpas** [jonls/redshift#234]
Redshift or redshift-gtk do not start if they are ticked at autostart menu
redshift v 1.9.1
Linux Mint 17.1 XFCE

**Comment by Yanpas** [comment]
Workaround: <bash -c "redshift;killall redshift; redshift-ftk -t 3500:6500"

**Comment by potholiday** [comment]
I also have the same problem in Ubuntu 14.04 for the past one week

**Comment by Yanpas** [comment]
For me helped installing 1.10 packages from debian sid
https://packages.debian.org/testing/x11/redshift
https://packages.debian.org/testing/x11/redshift-gtk
