### ISSUE TITLE
Screen randomly flickers red-blue for a moment when shifting window focus or starting applications

### ISSUE THREAD

**Issue by pvsomebody** [jonls/redshift#243]
Hi. I am experiencing a minor issue with redshift 1.10 ran from CLI under Fedora 22 (Gnome 3.16, no Wayland, Intel open source drivers, some composition active) -- at random occasions when the focus shifts to a different window, or when I am launching a new applications the screen flickers with different temperatures of white, as if redshift paused for a second, but then rapidly recovered and went back to work.

Command I am running it with is 'redshift -l xx.xx:yy.yy -t 5700:3800 -g 0.8 -m vidmode -v' and the file to execute it was placed in the ~/.config/autostart/ and looks like this: https://paste.fedoraproject.org/251189/86412791/

This is but a minor imperfection, but it's slightly annoying, so if this is indeed a bug of some sort, no my mistake in configuration, please let me know what kind of logs can I provide to help.

**Comment by spaceisstrange** [comment]
Happens to me too, specially when playing videos.

**Comment by pvsomebody** [comment]
The one way how it almost always happens to me, is when you open a new window of Gedit with a a hotkey, then mouse click into it. As the window focus changes, the screen briefly flickers cold and warm, as if Redshift suddenly restarted.

**Comment by jonls** [comment]
It is a known issue, and there's really nothing we can do to fix it. Redshift uses the gamma ramps to apply the redness effect but it cannot prevent other applications from messing with the gamma ramps too. If you can determine which application it is that is manipulating the gamma ramps you can try to ask the developers not to do that.

**Comment by pvsomebody** [comment]
Thank you for the response. In my experience, it mostly happens when I 
open gedit, but I wasn't aware how and why would they manipulate gamma 
ramps.
