### ISSUE TITLE
Feature request: Artificial brightness control

### ISSUE THREAD

**Issue by batonac** [jonls/redshift#246]
If Redshift can apply color-filtering to the entire display, it seems reasonable that the existing mechanism could be used to control the brightness of the video stream as well as the color temperature.  I seldom am satisfied by the hardware-brightness controls on my monitors, both because of clumsy controls and because they don't allow me to go as dim as I prefer (especially for night-time work).  I think it would be great if Redshift would add the capability to artificially (i.e. software-only) manipulate the brightness of the display.  Additionally, I think it would be great if the brightness could be automatically repressed along with the red-filter at sunset.

Optimally, someday Redshift would be able to advertise itself to the OS as a brightness control in the absence of a hardware-brightness-control driver.

**Comment by jonls** [comment]
You can control the brightness with the `-b` option. It allows you to set a separate brightness for day and night.

**Comment by batonac** [comment]
Okay, that's awesome.  I'm embarrassed I didn't research this well enough before posting the request.  Sorry...

Is there any way to pass this option to the program without restarting the running instance?  I suppose the gui integration for all these options is on the roadmap?  Thanks for such a great program.

**Comment by batonac** [comment]
Hey, I'll just use the custom config file for now.  Sorry to trouble you.  I'm looking forward to a GUI that can configure all these options, but for now, thanks for the great software!
