### ISSUE TITLE
Update Redshift package for current Ubuntu

### ISSUE THREAD

**Issue by nMustaki** [jonls/redshift#25]
Hi,

I know creating packages is a pain, but could you update Redshift to 1.8 in Ubuntu's current release, Saucy ?

Thanks !

**Comment by seb-1204** [comment]
Hi all, its been a while. Any update on this?
Or is there a trustable PPA, website I can get the package from? or some guidance on what I need to do in Ubuntu 14.10 to build it?

**Comment by spikebike** [comment]
On 01/13/2015 02:42 AM, seb-1204 wrote:
> Hi all, its been a while. Any update on this?
> Or is there a trustable PPA, website I can get the package from? or some
> guidance on what I need to do in Ubuntu 14.10 to build it?

I suspect it's just something like:
apt-get install autopoint intltool
./bootstrap.sh
./configure
make
sudo make install

There's docs in the HACKING file, takes just a few seconds to compile.
If something is missing and not obvious just google the error.

**Comment by nMustaki** [comment]
There's a redshift package in the Universe repo, enjoy !


--
/*
** "What do you despise? By this you are truly known."
**	from Manual of Muad'Dib by the Princess Irulan.
*/
