### ISSUE TITLE
Web service

### ISSUE THREAD

**Issue by blueyed** [jonls/redshift#252]
Are there plans for or does there already exist a web service that you could query, with optional lat/long and it would respond back with "Daytime", "Night" or "Transition"?

I am using [some script](https://github.com/blueyed/dotfiles/blob/master/usr/bin/get-daytime-period) already, which makes use of redshift, but it falls short otherwise, e.g. when redshift is not installed on a remote server etc.. - a workaround for that use case would be to forward something through SSH, but it got me wondered if there is a service for this already.

**Comment by jonls** [comment]
Depends on how accurately you need to follow the definitions of daytime, night and transition that Redshift uses. If you only need to distinguish between daytime and night, you should be able to use any web service that provides the time for sunrise and sunset. I don't know of any particular web service that provides this information but I'd be surprised if it doesn't exist. If you need to also distinguish the "transition" period, you'll need a web service that provides solar elevation.
