### ISSUE TITLE
Cannot limit to one randr output

### ISSUE THREAD

**Issue by mbana** [jonls/redshift#26]
Using the example http://jonls.dk/redshift/:

```
[vidmode]
screen=0
```

in ~/.config/redshift.conf still applies redshift to my second monitor. I've tried variations of this, but they have no effect. I want to only apply redshift to my first screen. Not that it should make any difference but I use gtk-redshift to launch redshift.

Side note: If I start two instances of redshift then terminate the second, it segfaults.

```
$ redshift -V
redshift 1.7
```

**Comment by jonls** [comment]
This should be working now with the `crtc=...` option in the `randr` gamma adjustment method.
