### ISSUE TITLE
Redshift doesn't work on Wayland

### ISSUE THREAD

**Issue by frantisekz** [jonls/redshift#260]
Launching redshift on Wayland ends with:
```
Unable to start GeoClue client: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Access denied.
```

This error can be fixed by running redshift as root, which will fail soon after:
```
No protocol specified
`RANDR Query Version' returned error -1
Initialization of randr failed.
Trying next method...
No protocol specified
X request failed: XOpenDisplay
Initialization of vidmode failed.
Trying next method...
No more methods to try.
```

Tested OS was Fedora 23 Workstation.

**Comment by maandree** [comment]
Wayland does not support gamma correction, which is required.
You need a compositor that supports RandR or Vidmode through
a X compatibity layer.

If you happen to use the Wayland compositor Orbital, check out
https://github.com/giucam/redshift.

**Comment by frantisekz** [comment]
Compositor is mutter (Gnome Shell), shall I report bug there?

**Comment by maandree** [comment]
Yes.

**Comment by frantisekz** [comment]
Running redshift as root is probably not relevant atm: https://bugzilla.redhat.com/show_bug.cgi?id=1266792 .

So, the error is just: Unable to start GeoClue client: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Access denied. 

It doesn't looks like it's caused by compositor imo?

**Comment by genodeftest** [comment]
The `Unable to start GeoClue client: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Access denied.` issue is either a bug in GeoClue or your SELinux policy. I doubt any of these issues is compositor-related.
The "RANDR missing" issue is a duplicate of #55.

**Comment by genodeftest** [comment]
For the GeoClue issue: see #158 with a workaround setting the position manually. On https://bugzilla.redhat.com/show_bug.cgi?id=1214978#c21 you can find the Fedora bug for that, with another workaround for GeoClue2 configuration. This workaround is also available here (German): https://thomas-leister.de/open-source/linux/redshift-unter-arch-linux-startet-nicht/

So you might close this as a duplicate of #55 or #158.

**Comment by frantisekz** [comment]
Sorry for late reply.
After fixing GeoClue issue no error message had shown up but nothing has changed (redshift looked as it was working but it had no effect on screen in fact)

**Comment by genodeftest** [comment]
> After fixing GeoClue issue no error message had shown up but nothing has changed (redshift looked as it was working but it had no effect on screen in fact)

That's why you can close it as a duplicate of #55.

**Comment by frantisekz** [comment]
Yup, sorry.

**Comment by bmltp** [comment]
Looks like we have alternative for Redshift
![Gnome 3 36 2](https://user-images.githubusercontent.com/58697145/84214652-535dd300-ab07-11ea-9d27-2b0cd7f8c7fb.png)
![Night Light](https://user-images.githubusercontent.com/58697145/84214653-548f0000-ab07-11ea-9b2d-162d3249d45c.png)
