### ISSUE TITLE
manual page adjustments

### ISSUE THREAD

**Issue by rjc** [jonls/redshift#266]
Hi,

I had a quick look at the manual page and adjusted it slightly:

- colon (`:`) doesn't belong in `.TH TITLE`
- `man-pages(7)` suggests that the date should be in the `YYYY-MM-DD` format - `mandoc -T lint` doesn't complain any more :^)
- given that section 1 already designates particular manual page as `User/General command`, explicitly stating that in `.TH` seems redundant
- while there, I had also taken the liberty to remove unnecessary double-quotes
- everything in `.SH NAME` should be lowercase and no trailing dot (.)

Patch is trivial and, IMVHO, doesn't warrant a pull request :^):

    --- a/redshift.1
    +++ b/redshift.1
    @@ -1,6 +1,6 @@
    -.TH REDSHIFT: "1" "October 2011" "redshift" "User Commands"
    +.TH REDSHIFT 1 2011-10-01 redshift
     .SH NAME
    -redshift \- Set color temperature of display according to time of day.
    +redshift \- set color temperature of display according to time of day
     .SH SYNOPSIS
     .B redshift
     \fI[\-l LAT:LON | \-l PROVIDER:OPTIONS] [\-t DAY:NIGHT] \fR[\fIOPTIONS\fR...]

**Comment by jonls** [comment]
:+1: Any change warrants a pull request! :wink: Opened in #267.
