### ISSUE TITLE
Provide a -symbolic icon for redshift-gtk

### ISSUE THREAD

**Issue by Faelian** [jonls/redshift#275]
A lot of Linux desktop environment are using -symbolic icons for the indicators to give a monochrome look to their indicators.

Redshift-gtk should provide a -symbolic icon to fit better into theses desktop environments.

Joined a screenshot of redshit-gtk in [elementary OS](elementary.io)'s indicator's panel
![redshift-symbolic-icon](https://cloud.githubusercontent.com/assets/4268373/11151652/8cbe71ee-8a2e-11e5-888c-a2be6af36550.png)

**Comment by jonls** [comment]
The old Ubuntu icons (https://github.com/jonls/redshift/tree/master/data/icons/ubuntu-mono-light/scalable/apps) are in a style similar to the ones in your screenshot. Perhaps you can use those, or modify those to suit your desktop environment?

**Comment by tobias-kuendig** [comment]
I've just created new icons for elementary os. 

See [this gist](https://gist.github.com/tobias-kuendig/d055892720cf09ae1a9d82075fb0f408) for installation instructions.

**Comment by jonls** [comment]
Closing, since monochrome icons are already provided.
