### ISSUE TITLE
Geoclue makes things clunky

### ISSUE THREAD

**Issue by dev-brother** [jonls/redshift#280]
Does redshift still need geoclue if you specify the lat:lon manually like so?

```
redshift -l 53:34 -t 5200:3200
```

Thanks for the cool app!

**Comment by YogliB** [comment]
It's usually a dependency, but it doesn't really use it if you set it manually.

**Comment by jonls** [comment]
@dev-brother You can compile redshift without geoclue support if you don't want to use it.
