### ISSUE TITLE
Feature Request: day/night cycle by time, not location

### ISSUE THREAD

**Issue by TheWing** [jonls/redshift#283]
Living rather north (Finland), so during the winter and summer these aren't very usable, since the day/night cycle up here is very unbalanced. I'd like a static, time based thing doing the same.

**Comment by jonls** [comment]
Thanks for the feature request @TheWing. I think this feature has already been suggested in #9. Some people have suggested manually setting a lower latitude to get a more "balanced" day/night cycle.
