### ISSUE TITLE
Apply temp/color to cursor in Windows

### ISSUE THREAD

**Issue by skribb** [jonls/redshift#285]
Apply temp/color to cursor would be nice. The cursor is like a little beacon of light in "dark mode" as it stands right now.

**Comment by jonls** [comment]
This is a known limitation as mentioned on the web site and it is unfortunately not something we can easily fix. The gamma ramps do not affect the mouse cursors. There is a possibility that this could be accomplished by dynamically updating the cursor images but I do not plan on implementing this for Windows though.

**Comment by shunjou** [comment]
f.lux has the same issue and mentions a fix in its faq that references this url: http://photo.stackexchange.com/questions/3436/how-to-apply-color-management-to-the-windows-7-mouse-cursor

**Comment by skribb** [comment]
Thanks for the replies
