### ISSUE TITLE
Crashes on startup - Unable to run GeoClue client

### ISSUE THREAD

**Issue by forteller** [jonls/redshift#289]
Hi. I'm trying to run Redshift 1.10 installed from Synaptic on an almost brand new installation of Ubuntu Gnome 5.10 64-bit.

But every time I just get this error message:

```
$ redshift
Trying location provider `geoclue2'...
Using provider `geoclue2'.
Unable to start GeoClue client: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Geolocation disabled for UID 1000.
Unable to connect to GeoClue.
Unable to get location from provider.
```

When I try to run redshift-gtk I get this:

```
$ redshift-gtk 
/usr/lib/python3/dist-packages/redshift_gtk/statusicon.py:32: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GLib, GObject
/usr/lib/python3/dist-packages/redshift_gtk/statusicon.py:35: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as appindicator

(redshift-gtk:12943): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```

plus a popup with the same error message as I get in the terminal when running redshift.

I am not a very technical person, so I don't really understand any of this. I'm just hoping this bug report can help you fix this for everyone who might experience this in the next version. Thanks! :)

**Comment by auscompgeek** [comment]
Either enable location services in GNOME's privacy settings, or use the manual location provider.

**Comment by hackerb9** [comment]
@auscompgeek : Thanks, that worked for me. It'd be great if redshift actually said exactly what you did instead of the weirdness about GeoClue. I had gone on a wild goose chase checking group IDs.

**Comment by forteller** [comment]
Yes!

The way it is now Redshift, although it's a great application that I love, is actually unusable for most people on Gnome, because it's impossible to understand how to get it working.

**Comment by kevr** [comment]
@hackerb9 Problem is, redshift does not depend on GNOME. This could be caused by other location service provider issues, on a number of desktop environments, thus is it more general rather than specific to GNOME.

**Comment by forteller** [comment]
Well, this is no issue on Gnome any more. After Gnome added a similar function I don't think anyone would care to install Redshift in Gnome. But I hope it is/will be easier to start for the first time in other desktop environments!

The number of likes the first reply in this thread has received indicates that I'm not the only one who's had issues with this, even as one of the very small percentage of people nerdy enough to have a GitHub acount.

**Comment by hackerb9** [comment]
@kevr: Good point about it being a general problem. But there's no general solution, yet, right? Since the current error message (geoclue) leads people astray, the wording still needs to be changed. Would it be neutral enough to say "Please enable location services (for example, Privacy Settings in GNOME), or use the manual location provider." ?

I think it's important to at least give one example of a real solution instead of telling them some gobbledygook they're just going to have to Google.

**Comment by kevr** [comment]
I actually submitted a PR for you guys earlier this morning around 5AM with a note for gnome when that error occurs, maybe he will accept it :P

**Comment by jonls** [comment]
Thanks @kevr. I saw your PR and it seems reasonable. One concern I have is that distributions don't update Redshift very often so users will potentially be stuck with this message for a couple of years. With everything happening with location services lately I worry that this message will quickly become outdated.

**Comment by hackerb9** [comment]
@jonis: It's true the message may become outdated in some distributions, but if so, users will file a bug report with their distributions and it's up to the distribution to get the latest Redshift.

**Comment by jonls** [comment]
Thanks for your input. An improved error message has been added in #504 and an entry in the FAQ (https://github.com/jonls/redshift#faq) has been added for access denied issues with GeoClue.

**Comment by nithwith** [comment]
Thanks

**Comment by sunniboi** [comment]
pleas take this in config when crashed mit UID 1000 or geoclue 

/etc/geoclue/geoclue.conf 

[redshift]
allowed=true
system=false
users=
