### ISSUE TITLE
Restrict redshift to only a certain time slice

### ISSUE THREAD

**Issue by strelec** [jonls/redshift#290]
Since redshift has a bug that it removes the color calibration profile on the monitor, I'd like to set in the configuration file to restrict the activity to just a certain time slice, like from 8:00 PM to 7:00 AM.

This way I can have a proper color calibration during the day.

Could that be done somehow?

**Comment by maandree** [comment]
I wound not say it is a bug.

@jonls, didn't you merge in a feature that lets the user keep the calibrations?

In any case, you could use SIGSTOP and SIGCONT to pause and resume
redshift, and have cronjobs that do this for you.

**Comment by simonnagl** [comment]
You also can use systemd timers to achieve the START-STOP behavior.

**Comment by ayrieokx** [comment]
I think this should be the default behavior. If you install redshift in its default configuration, your screen will never look 'normal' again. This is different from virtually all other similar software, which only changes things at night.

**Comment by jonls** [comment]
In the latest version, the `preserve` option can be used to keep the existing color calibration of the monitor. This option will most likely be on by default in the next release.
