### ISSUE TITLE
No up to date PPA available

### ISSUE THREAD

**Issue by MichaelAquilina** [jonls/redshift#307]
The official ppa seems to be severely out of date https://launchpad.net/~jonls/+archive/ubuntu/redshift-ppa

The ppa provides packages up to Ubuntu Natty which is ages old.

Ubuntu 14.04 which has a relatively old 1.8 version of redshift and it would be nice to have an official ppa from which to get the latest versions. 1.8 does not provide support for geoclue2 for example which is a pretty big deal.

**Comment by patcon** [comment]
:+1:

**Comment by patcon** [comment]
Apparently it exists: https://launchpad.net/ubuntu/+source/redshift

Ref: https://github.com/jonls/redshift/issues/25

Close? :)

**Comment by MichaelAquilina** [comment]
That's not a ppa though, it's the official package in Ubuntu's repositories. If you check the version listed for Trusty Tahr (14.04) its redshift 1.8

**Comment by dobey** [comment]
I have daily builds set up. I just created a separate PPA for them. It's at https://launchpad.net/~dobey/+archive/ubuntu/redshift-daily/+packages

It has packages for 14.04, 15.10, and 16.04.

**Comment by patcon** [comment]
:+1:

**Comment by leycec** [comment]
@dobey Thanks for the intrepid PPA work. Have a cherry blossom. :cherry_blossom: 

Sadly, I have a related issue: all existing `redshift` packages, including both the [official packages](https://launchpad.net/ubuntu/+source/redshift) and dobey's [unofficially awesome packages](https://launchpad.net/%7Edobey/+archive/ubuntu/redshift-daily/+packages), **fail to install `systemd` units.** This renders `redshift` more or less ineffective under Ubuntu >= 15.04 – especially for those of us neglecting to manually start `redshift`. Cue yet another catastrophic chain of bleary-eyed, caffeine-fuelled hyper-productivity.

<sup>_This may have been me last night. **Oh, how I paid.**_</sup>

## `redshift` + `systemd` = Red Heaven

Until remedied, Ubuntu >= 15.04 users may manually install the userspace `systemd` unit as follows:

1. Create the `~/.config/systemd/user/redshift.service` file with the following contents:

        [Unit]
        Description=Redshift display colour temperature adjustment
        Documentation=http://jonls.dk/redshift/
        After=display-manager.service
        
        [Service]
        ExecStart=/usr/bin/redshift
        Restart=always
        
        [Install]
        WantedBy=default.target

1. Reload the userspace `systemd` daemon:

        systemctl --user daemon-reload

1. Start `redshift` for the current window manager session:

        systemctl --user start redshift

1. Start `redshift` on all subsequent user logins:

        systemctl --user enable redshift

`redshift` will then be autostarted as sanity requires.

**Comment by dobey** [comment]
@leycec Next update built from my PPA will have those systemd files installed in the packages.

**Comment by Kasijjuf** [comment]
Obligatory booing of systemd:
"Boo systemd!"

**Comment by furai** [comment]
So I've used the said PPA from @dobey (thanks for the amazing work). It had already systemd service for redshift, as per @leycec suggestion. Great job. 
To make it work I still had to enable service as user, I think that's expected. I'm not entirely sure how all of this works.
However, there was one problem. Everything worked until I added custom config in `~/.config/redshift.conf`. For some reason randr was failing to initialise. 

After a bit of searching the net, I found out that to the [service] section I needed to add:
`Environment=DISPLAY=:0`
Once I did that all worked perfectly.

My system is Linux Mint 18 Cinnamon x64 (Ubuntu 16.04 is base for it.).

**Comment by Kasijjuf** [comment]
Has this been resolved? Can this issue be closed?

**Comment by ViBE-HU** [comment]
i don't get this. the code is "up to date" but Jon still not updated the PPA.

**Comment by dobey** [comment]
@ViBE-HU My PPA is up to date.

**Comment by ViBE-HU** [comment]
@dobey I know but your release is buggy. Already tested.

**Comment by jonls** [comment]
@ViBE-HU Please let us know what the issue with the PPA is. Otherwise we can't fix it. I don't have the capacity to maintain a PPA so we should fix the PPA that @dobey is providing if there's an issue.

**Comment by ViBE-HU** [comment]
@jonls I can't check it now what is the exact problem but I remember that @dobey 's release cannot reach the service (geo...something) which provide the cords.

**Comment by dobey** [comment]
@ViBE-HU That's not an issue with my PPA. It's an issue with redshift and geoclue; you can specify coordinates in the config as a workaround. There are several open issues about the geoclue problem, but I don't know if they are being worked on.

**Comment by ViBE-HU** [comment]
@dobey I meant your release. And I guess you right but I did not know what code you use for build. I think I'm staying on latest release from the official Xential repository then.

**Comment by dobey** [comment]
@ViBE-HU The package in my PPA is literally the same as building straight from git. It's an automated build that gets rebuilt daily whenever git changes.

**Comment by boxesofdead** [comment]
So would @dobey use be

`sudo add-apt-repository ppa:dobey/redshift-daily `

**Comment by dobey** [comment]
Yes.

**Comment by jonls** [comment]
The PPA provided by @dobey is now mentioned in the README since 72a8fcbe054300f20ff05de01f288226fd8274f9

**Comment by bmaupin** [comment]
@dobey Any plans to include redshift 1.12 in your PPA?

**Comment by dobey** [comment]
It seems that some commits were made with gpg signatures in git, which broke the git->bzr import:

bzrlib.plugins.git.errors.UnknownCommitExtra: Unknown extra fields in <Commit 91e1d30a6f8f37e8a20575ac5e04dd0228080783>: ['gpgsig'].

So this will require a fair bit of work to switch over to a git->git import and moving the packaging into a git branch, in order to get the daily builds working again. :-/

**Comment by k1nghat** [comment]
> It seems that some commits were made with gpg signatures in git, which broke the git->bzr import:
> 
> bzrlib.plugins.git.errors.UnknownCommitExtra: Unknown extra fields in <Commit [91e1d30](https://github.com/jonls/redshift/commit/91e1d30a6f8f37e8a20575ac5e04dd0228080783)>: ['gpgsig'].
> 
> So this will require a fair bit of work to switch over to a git->git import and moving the packaging into a git branch, in order to get the daily builds working again. :-/

is this still an issue with your PPA? also, why not just build on new release vs daily?

**Comment by dobey** [comment]
> is this still an issue with your PPA? also, why not just build on new release vs daily?

No. I managed to move the import over to straight git. redshift doesn't get a lot of changes, and building only on releases is not easily automated in Launchpad recipes.

**Comment by k1nghat** [comment]
> > is this still an issue with your PPA? also, why not just build on new release vs daily?
> 
> No. I managed to move the import over to straight git. redshift doesn't get a lot of changes, and building only on releases is not easily automated in Launchpad recipes.

i see. tyvm for your work. does this mean i will be installing an update every day? maybe im just confused on what the daily build means for the end user?

**Comment by dobey** [comment]
> i see. tyvm for your work. does this mean i will be installing an update every day? maybe im just confused on what the daily build means for the end user?

The term "daily" is a misnomer. It does not necessarily mean there will be an update every day. However, as configured, that is the most often an update will be available in the PPA due to automatic builds (I can trigger some manual builds when necessary, which could result in more than one update for a given day). Only if there are new changes in the repository (either the main redshift repo, or if I make change to the packaging repo) for the previous day, will a new build happen automatically. The last change to github:redshift/redshift was in October.
