### ISSUE TITLE
Redshift and DisplayLink

### ISSUE THREAD

**Issue by eduncan911** [jonls/redshift#311]
Would it be possible to apply Redshift, or Redshift-like effects, to monitors connected via DisplayLink?

The F.lux guy said that DisplayLink does not expose any color temperature controls through the Windows drivers.

Under Linux, I was hoping Redshift could get around this somehow.  But as of today, it doesn't seem so.

I have three monitors:

DisplayLink - DisplayPort - DisplayLink

The LCD connected to the DisplayPort works fine with RedShift.  But the other two with DisplayLink does not.

**Comment by dobey** [comment]
Issue #303 being fixed would presumably allow this to work, without needing additional support from the DisplayLink driver.

**Comment by aiguofer** [comment]
I'm very interested in this! I'm really enjoying my two laptop displaylink dock, but I'm missing redshift. I tried messing with the monitor settings to remove a little blue light and it has helped some, but it's not quite as good as the real deal. I also tried @jonls' gnome-shell-extension (night-mode) but the colors are too far off to really be usable.

I'll keep an eye on this and 303

**Comment by i2000s** [comment]
DisplayLink's recent driver (8.3 M0 and 8.3 alpha) has supported f.lux on Windows. Could it be possible to benefit from their driver to make redshift work in Linux for DisplayLink and external monitors?

**Comment by benedikt-bartscher** [comment]
Same Problem here...

**Comment by Ericson2314** [comment]
Would the gamma support be something that needs to happen in the open source https://github.com/DisplayLink/evdi or elsewhere?

**Comment by finetype** [comment]
Also watching this one...

**Comment by awsaunier** [comment]
This would be amazing to have!

**Comment by jcgoble3** [comment]
@jonls I just got a new monitor that uses DisplayLink and this issue is going to drive me crazy. Any plans to fix this or #303 (which has been said above might fix it)?

**Comment by Jamie-505** [comment]
would love to see a solution for this. I"m on Arch Linux and everything works fine except for red shift

**Comment by kylebakerio** [comment]
Still following this. :(

**Comment by DrAxelbauer** [comment]
+1 Also on Linux Kubuntu 18.04 following this issue....Great Redshift fan!

**Comment by kecsap** [comment]
As I discussed on this bug:

https://github.com/DisplayLink/evdi/issues/44

Basically:
1. The gamma ramp/color temperature support must be implemented in the evdi kernel module for DisplayLink.
2. The user will still need a patched Xorg version (at least on Ubuntu) because Xorg added gamma ramp support to the modesetting driver previous year and at least it is not landed in Ubuntu 18.04. Modesetting driver is used by DisplayLink.

**Comment by eduncan911** [comment]
OP here. I long gave up on DisplayLink years ago due to various deficiencies and original hard stance against Linux.  After three laptops, various Linux distros (last was QubesOS which DL is a joke with), and different brands of DisplayLink adapters, I'm convinced it's the DisplayLink foundation itself trying to protect their copyright and HDCP protocol that they treat Linux as 3rd class citizens, or frankly don't care to just leave things as-is.

I've dropped DisplayLink all together regardless of cost for laptops with eGPUs and 3 monitor outputs. 
it's usually a combination of 2x DP + HDMI, like my current Thinkpad P1 with 2x USB-C TB3 + HDMI, supporting 4x external 4k monitors in addition to the 5th 4k LCD screen - on Linux, with full Redshift support across all of them.

 I know a lot of people are following this Issue in hopes that Redshift will support DisplayLink, but the problem is not with RedShift or any code they have - like mentioned above, it's a kernel driver limitation that RedShift will just start working with if they ever support it.

So at this time, I am closing this issue.

And I direct everyone to file a bug with the Displaylink foundation themselves to get then to support this feature.

**Comment by vratojr** [comment]
In case anybody is willing to press on displaylink to implement the feature, here's a link to vote:

https://support.displaylink.com/forums/287786-displaylink-feature-suggestions/suggestions/40626208-displaylink-add-debian-support-and-support-f-lux-a
