### ISSUE TITLE
unable to run redshift

### ISSUE THREAD

**Issue by gokulreddy07** [jonls/redshift#313]
unable to red redshift ![screenshot from 2016-02-07 20 49 31](https://cloud.githubusercontent.com/assets/6746715/12873156/6546dfd8-cddc-11e5-9397-e093106f7712.png)

**Comment by maandree** [comment]
What display server are you using, and what is the output of `redshift -m list`? Did you redshift compile it yourself or a you using a package?

**Comment by gokulreddy07** [comment]
Hi I'm using VGA compatible controller: Intel Corporation Atom Processor Z36xxx/Z37xxx Series Graphics & Display (rev 0e),output of redshift -m list 
![screenshot from 2016-02-08 00 22 36](https://cloud.githubusercontent.com/assets/6746715/12874515/6bf06150-cdfb-11e5-9510-cc45e99c5186.png)
i complied myself

**Comment by maandree** [comment]
Try to explicitly enable randr when compiling:
```
./configure --enable-randr
```

My guess is that you do not have the file `/usr/lib/pkgconfig/xcb-randr.pc`
which is a part of libxcb (possibly packaged as libxcb-randr). Perhaps
your distribution have it in a `-dev` or `-devel` package.

**Comment by gokulreddy07** [comment]
checking whether to enable DRM method... missing dependencies
checking whether to enable RANDR method... missing dependencies
configure: error: missing dependencies for RANDR method

i found these errrors while comilling

**Comment by maandree** [comment]
Have you tried installing a package libxcb-dev, libxcb-devel, libxcb-randr-dev, libxcb-randr-devel, or similar? Some distributions do not include header files and such, needed to compile a package uses the library, in the normal package, but in separate developer package. I would also need such corresponding package for libdrm for the DRM method which is used when you are not in a graphical environment.

**Comment by pca2** [comment]
Having the same issue on Ubuntu 14.04

**Comment by jonls** [comment]
This seems to be caused by not enabling any adjustment methods when running `./configure`. If this is still an issue after enabling adjustment methods, please reopen this issue with the new information.
