### ISSUE TITLE
Manually set color temperature

### ISSUE THREAD

**Issue by jluttine** [jonls/redshift#314]
Not sure if these have been suggested already but I'd like the following changes:

- add manual setting option so users can adjust color temperature manually

- redshift should work without location providing enabled (use time-based or manual setting instead)

Anyway, a great application, really helps working in darker environments. Thanks!

**Comment by tpenguinltg** [comment]
This is already possible using the command line tool by passing the `-O` flag.

**Comment by jluttine** [comment]
Ok, thanks! Would be nice to have it in the GUI but this works. :yum:
