### ISSUE TITLE
Icon doesn't display red bulb

### ISSUE THREAD

**Issue by Johnny-Metal** [jonls/redshift#317]
Hello,

I have recently installed Redshift from source code, the latest version to be more precise. Everything runs perfectly, except for one small detail: the status icon in the icon tray, despite being there and working, is just a rectangle, it is not the actual red bulb. Anyone know of any way to solve this?

I am running Lubuntu 14.03 LTS, which uses LXDE desktop environment.

**Comment by jonls** [comment]
I'm closing this since there hasn't been any activity with this issue for a while. Please reopen if new information becomes available.
