### ISSUE TITLE
Immediately apply adjustments on start with smooth transitioning afterwards

### ISSUE THREAD

**Issue by fdietze** [jonls/redshift#319]
When booting my computer in the evening, redshift smoothly applies its color adjustments.

Did I understand correctly, that one-shot mode keeps the color adjustments forever from the moment it was started?

What I would like to have is starting redshift with applying the adjustments instantly, but still react on the sun position over time. How can I achieve that?

**Comment by jotomo** [comment]
@fdietze there's an option
```-r		Disable temperature transitions```
which will adjust the temperature at start instantly and keep updating as time passes.

**Comment by fdietze** [comment]
That's what I was looking for, thank you. I was not able to figure it out from the documentation.
