### ISSUE TITLE
Redshift does not seem to work

### ISSUE THREAD

**Issue by danse** [jonls/redshift#322]
I think that it stopped working after updating Ubuntu. When i run it via the command line in a verbose mode, it prints temperatures decreasing down to 3500K, but i don't see any change in the screen colours. How can i get more useful info in order to debug?

**Comment by danse** [comment]
Alright, at least the version is useful. I found that i am running 1.10, i will try with 1.11

**Comment by danse** [comment]
Looks like the only related issue fixed in 1.11 is #271 though, which is not my problem. I can run `redshift-gtk` just fine

**Comment by danse** [comment]
Just a note: in the description of Redshift you write that a red light helps the eyes hurt less. Actually i believe that avoiding blue light is also helpful for the sleep cycles and in order to avoid insomnia. I don't have a reference about that though

**Comment by maedox** [comment]
I just noticed the same thing. There is no change what so ever in color temperature in Ubuntu 16.04 with the default (X) randr mode. It works with -m vidmode though. Not sure if there's any difference in performance.

**Comment by goodmami** [comment]
I get the same thing on Ubuntu 16.04, but unlike @maedox, nothing seems to work for me. It reports a temperature of, e.g., 2500K, but there is no change in color on the screen (i.e. it is still 6500K). It doesn't matter if I use `redshift -O2500`, `redshift -O2500 -m vidmode`, or use redshift-gtk.

**Comment by danse** [comment]
Hum. Now this works for me, but in the meantime i updated to Ubuntu 16.04, so i am not sure about what caused and what fixed the problem! :confounded:

**Comment by jonls** [comment]
Ok, thanks for reporting. I will close the issue since it seems to have been resolved.
