### ISSUE TITLE
Mac OS X "default values"

### ISSUE THREAD

**Issue by DrChr** [jonls/redshift#325]
Hi,

How could I e.g. daytime start redshift on my MacBook Air[*] _without_ getting a noticeable/visible change off the screen characteristics?  Basically I'd like the normal screen characteristics daytime, but redshifted at night.
I experimented with setting various colour temperatures in the range 5000K-7000K, but none seem to match the default screen characteristics.  

Here's an example of how I manually attempted to set the screen colour (I thought 6500K would leave it unchanged as per the web site)

```
redshift -o -O 6500
Using method `quartz'.
Press ctrl-c to stop...
```

Regards,
Christian

[*] It's an MacBook Air, early 2015, running Mac OS X, El Capitan, in case this matters.

**Comment by ayrieokx** [comment]
see #290

**Comment by DrChr** [comment]
Agreed, #290 covers this, I'm setting this to closed.
