### ISSUE TITLE
Tray icon clipped in GNOME 3.20 with HiDPI

### ISSUE THREAD

**Issue by benwaffle** [jonls/redshift#330]
![tray](https://cloud.githubusercontent.com/assets/1713819/14028118/4e6da152-f1d1-11e5-869f-c64286e4074c.png)

**Comment by MarcinWieczorek** [comment]
![selection_005](https://cloud.githubusercontent.com/assets/3466984/14654809/b6b092ac-067f-11e6-9490-a8a32d291094.png)
Doesn't seem to be redshift's fault. I don't have an icon at all.
Meh, too lazy to look for a solution.

**Comment by analbeard** [comment]
@MarcinWieczorek did you find a solution to this? I'm missing a couple of tray icons under gnome 3.20 and it's bugging me.

**Comment by MarcinWieczorek** [comment]
Nope. I don't use the icon anymore, just the daemon. Therefore it seems to be Gnome's issue rather than redshift's.

**Comment by bil-elmoussaoui** [comment]
It's a gnome 3.20 issue, i've that with other icons/applications too

**Comment by MarcinWieczorek** [comment]
yep. Any solutions?

**Comment by analbeard** [comment]
I eventually realised that my issues were due to the icon theme I was using
- it used symbolic icons for some statusicons and they were dark on a dark
background. Changed my icon theme and they're now light/back, albeit still
symbols.

**Comment by mattia-b89** [comment]
I confirm this bug, but...
...but, not always is present

gnome 3.20.2 on Arch Linux

**Comment by jonls** [comment]
Since this seems to be related to GNOME I will close this issue. Please reopen if this needs any fixes in Redshift.
