### ISSUE TITLE
Redshift takes a variable amount of time to work again when display settings are changed

### ISSUE THREAD

**Issue by TheMadCoder1** [jonls/redshift#332]
When I connect another monitor to my laptop, and I mess with some settings in the display settings, and then apply those changes, it takes a varying amount of seconds for redshift to get working again on both screens, leaving me with a painful blue sight for some time.

**Comment by jonls** [comment]
Thanks for your report. This is a known limitation. I think this may be fixed some day when Redshift can run a main loop that detects when displays are added and removed but there may always be a few seconds before the gamma adjustment kicks in.
