### ISSUE TITLE
Switches on and off in full screen game

### ISSUE THREAD

**Issue by ThornedRose** [jonls/redshift#334]
This is a long shot and possibly something more to do with an individual game but just in case --

When running Pillars of Creation (a Unity engine game), Redshift flickers off for several seconds and then back on for several seconds over and over.

So far in my testing this is the only full screen game to have this problem but it's also the only Unity based game I have so I have no way of testing to see if it's specific to Unity games or something else to do with full screen games.

Additionally, this only happens on Deepin Desktop and does not on OpenBox. Possibly something to do with the compositor?

 OS: Arch Linux 
 Kernel: x86_64 Linux 4.4.5-1-ARCH
 Uptime: 45m
 Packages: 1226
 Shell: bash 4.3.42
 Resolution: 1920x1200
 WM: Mutter(DeepinGala)
 WM Theme: Adwaita
 Icon Theme: deepin
 Font: Noto Sans 10
 CPU: Intel Core2 Quad CPU Q6600 @ 2.4GHz
 GPU: GeForce GTX 650 Ti
 RAM: 2185MiB / 6979MiB

**Comment by ThornedRose** [comment]
Ok, I have tested further. It happens on multiple full screen apps (some, not all). I have tried switching to vidmode but the problem remains. I have tried drm but it results in an error :
Failed to get DRM mode resources
Failed to start adjustment method drm.
(I have libdrm installed)

**Comment by ThornedRose** [comment]
I have also tried turning the compositor off but it makes no difference.

**Comment by zack112358** [comment]
I had a similar issue under Fluxbox. nvidia-settings gamma adjustments had the same problem. I uninstalled nVidia proprietary drivers and the problem disappeared.

**Comment by jonls** [comment]
Thanks for the report. This is a known limitation that Redshift unfortunately cannot prevent. Some applications will reset the gamma ramps which means that the redness effect disappears for a few seconds. If this only happens with nvidia proprietary drivers, please report this to nvidia directly. Otherwise, please report it to the software that causes the gamma reset.
