### ISSUE TITLE
run hooks on startup/exit, enable/disable

### ISSUE THREAD

**Issue by sj4** [jonls/redshift#335]
currently, hooks are only executed when the period changes, eg transition>night, etc.
it would be nice if the hooks are also executed when redshift starts

Example use case:
- the brightness hook sets brightness to 10% at night, this setting is stored
- laptop shuts down
- next day during day time, laptop starts, redshift starts, but brightness is still set to 10%, because no hook was executed on startup of redshift

If hooks are executed at startup, redshift does not know about the previous period, so 'none' would be an acceptable value.

**Comment by EvertonMelo** [comment]
Hello, 

you CMOS is OK? 
o GeoCLue use the Time Sytem the your Laptop.

you verify the *(real)date of the system?

**Comment by infernix** [comment]
In addition to startup, a hook when enabling/disabling (SIGUSR1) and a hook at exit would also be great. This way the display brightness hooks I'm using can be accurately correlated with the redshift of the screen.

**Comment by jonls** [comment]
Thanks, those are great suggestions! I would definitely merge a pull request with these additions.

**Comment by danielkza** [comment]
Hooks seem to run correctly for me, transitioning from "none" to "night" or "daytime" immediately when I start redshift.

**Comment by jonls** [comment]
It seems that Redshift correctly runs hooks on start and exit. The only thing not implemented is the hook when enabling/disabling as suggested by @infernix.

**Comment by mwstobo** [comment]
I can take a quick look at this one. When redshift is disabled, should the hooks be called with a new "Disabled" state, or should be just use the existing None state? I feel like it would be nice to have the semantic difference between the two, for maximum flexibility.
