### ISSUE TITLE
Suspends disable from command line

### ISSUE THREAD

**Issue by simonvanderveldt** [jonls/redshift#338]
Hi Jon! First of all, thanks for the great tool(s)!

I have small question/possible feature request: I'm using redshift-gtk, which starts on session startup. I know I can suspend redshift by clicking on the icon the tray, but I'd like to be able to suspend/disable and resume redshift from the command line so I can automate it when I launch a game for example.
Would that be possible?

**Comment by maandree** [comment]
Kill redshift with SIGUSR1.

```
pkill -USR1 '^redshift$'
```

**Comment by simonvanderveldt** [comment]
@maandree But then it's gone and I'd have to start it again. Or in other words than I ahve no way to have the icon in my tray to show redshift's state, correct?

**Comment by maandree** [comment]
No, redshift does not exit when it receives SIGUSR1, it disables or enables its effect. And the tray icon will be updated too when redshift recieves the signal.

**Comment by simonvanderveldt** [comment]
@maandree Awesome, exactly what I was looking for, thanks a lot!
Looked over it in the docs, but now that I know it's `USR1` I've found that it's mentioned in the docs as well. Will close this issue.
