### ISSUE TITLE
[bug] geoclue service restarted

### ISSUE THREAD

**Issue by mattia-b89** [jonls/redshift#340]
If I restart geoclue service `systemctl restart geoclue.service`, Redshift closes itself!
This only happens if geoclue has not yet provided a location.... that is the reason why I want to restart it!

**Comment by mattia-b89** [comment]
this is a screenshot of what I get:
http://i.imgur.com/s389tUN.png
then when I click on `Close` button, Redshift closes itself

**Comment by jonls** [comment]
Thanks. This is a know limitation that will be fixed when Redshift is able to continuously request location updates from Geoclue.
