### ISSUE TITLE
Windows 32-bit release

### ISSUE THREAD

**Issue by Immortalin** [jonls/redshift#342]
Any plans for a 32 bit windows release?

**Comment by EvertonMelo** [comment]
there is a FORK: 
f.lux 
font: https://justgetflux.com/ 
and:
http://jonls.dk/redshift/

**Comment by jonls** [comment]
Hi @Immortalin, I'm not set up to do cross-builds for Windows at the moment so unfortunately no plans at this time 😞

**Comment by Immortalin** [comment]
ok
