### ISSUE TITLE
Failed to run Redshift: No more methods to try

### ISSUE THREAD

**Issue by tyler-8** [jonls/redshift#346]
Executed `redshift-gtk`

Here's the output from the terminal:

`Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.`
`(redshift-gtk:16896): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed`

**Comment by agnivade** [comment]
Well, your title is different than that of the error message that you have given. 

The `GtkDialog mapped without a transient parent. ` error is known, but that does not stop you from running the app.

The error that you have mentioned in the title happens when you haven't mentioned any method. Can you run - `redshift-gtk -m randr` and see what happens ?

**Comment by tonehrk** [comment]
> redshift-gtk -m randr
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by jonls** [comment]
@tonehrk Did you compile Redshift yourself? If you are really seeing the error message that you posted in the title, you have to enable some adjustment method when you compile Redshift.

**Comment by suryabvsp** [comment]
I too get the message 'no more methods to try'. I get it when I enter in the terminal :
redshift -l 24.933860:79.923617
when I launch redshift or redshift-gtk, I get :
Failed to run Redshift
Trying location provider `manual'...
Latitude and longitude must be set.

**Comment by jonls** [comment]
Closing this issue since it seems to have been resolved.

@suryabvsp Thanks for your report. This is an unrelated issue though. Can you please open a new issue?

**Comment by IAM5K** [comment]
redshift -l 24.933860:79.923617
Could not connect to wayland display, exiting.
Failed to start adjustment method wayland.
Trying next method...
Using method `randr'.
Waiting for initial location to become available...
Location: 24.93 N, 79.92 E


![image](https://user-images.githubusercontent.com/43265495/114265855-bdd5ed00-9a10-11eb-907c-45b5de2f29af.png)


Still, Redshift is not working.

**Comment by IAM5K** [comment]
![image](https://user-images.githubusercontent.com/43265495/114265893-f5449980-9a10-11eb-9d0a-68ad4c154bf4.png)
