### ISSUE TITLE
Location and method Lists limited?

### ISSUE THREAD

**Issue by peteruithoven** [jonls/redshift#349]
So I installed Redshift 1.11 on Elementary OS Freya (Based on Ubuntu 14.04 LTS) but I noticed that requesting the location lists and methods they didn't mention all the options that are mentioned on the website, see bellow. What could cause that? Is this based on what my system supports? 
```
$ redshift -l list
Available location providers:
  geoclue2
  manual
```
```
$ redshift -m list
Available adjustment methods:
  dummy
```

**Comment by maandree** [comment]
It is based on what was available on your system when you built Redshift, and any flags used for ./configure.

**Comment by peteruithoven** [comment]
Thanks! I'll try to build it myself, see how that works out.
