### ISSUE TITLE
redshift.conf location on Windows

### ISSUE THREAD

**Issue by landroni** [jonls/redshift#350]
I am trying to run Redshift 1.9.1 on a Windows XP machine (`redshift-1.9.1-x86.zip`) but it fails to detect the config file. The main website recommends putting the config file in `~/.config/redshift.conf`, but what does this translate to on Windows? 

I tried creating it in `My Documents/.config` but that didn't work...

**Comment by maandree** [comment]
Perhaps you can run `echo ~` in PowerShell to get the answer.

**Comment by landroni** [comment]
I looked into PowerShell, but it doesn't seem to be installed on the machine, and since it's Windows XP it's no longer supported by Microsoft. Any ideas on how else I could get the answer (or what is a typical Windows location for the redshift config file)?

**Comment by maandree** [comment]
Perhaps it is My Documents's parent directory.

In the command prompt, you may be able to run `echo %userprofile%`.

If you have Python:
```
from os.path import expanduser
print(expanduser("~"))
```

If you have Java:
```
public class Main {
    public static void main(String[] a) {
        System.out.println(System.getProperty("user.home"));
    }
}
```

(And of course add /.config to your results.)

**Comment by maandree** [comment]
Nevermind the above, here is the relevant code from redshift:

```c
if (f == NULL && (env = getenv("localappdata")) != NULL && env[0] != '\0') {
    snprintf(cp, sizeof(cp), "%s\\redshift.conf", env);
    f = fopen(cp, "r");
}
```

Appearenly there is an environment variable name localappdata.
If think you can print it by running `echo %localappdata%`. Then
append '\redshift.conf' to the result.

**Comment by catb0t** [comment]
`%localappdata%` is probably `C:\Users\USERNAME\Local Settings\Application Data`, if such a place exists.

**Comment by landroni** [comment]
Thank you for this. I've tried `%localappdata%` from the command prompt, but it ends in an error this "isn't recognized as an internal command". 

I also don't see `C:\Users\USERNAME` in the dir structure, but instead there is `C:\Documents and Settings\USER\Local Settings\Application Data`. I created a `redshift.conf` file in that dir with the lat/lon specified, but `redshift.exe` still fails to see it and fails on start-up. 

Is there something else that I could try?

**Comment by Kasijjuf** [comment]
Typing SET by itself on the command line will output the values of all active environment variables.

**Comment by lcdss** [comment]
@landroni If the `echo %localappdata%` outputs `%localappdata%` it means `localappdata` variable isn't set on your system as a variable, so you can try set one manually opening the `cmd` as administrator:

`SETX localappdata C:\Users\YOUR_USERNAME\AppData\Local`

or you can go to `Control Panel\System and Security\System` -> Advanced System Settings -> Environment Variables.

**Comment by landroni** [comment]
`SET` worked nicely. There is no `%localappdata%` in the listing, but there is `%appdata%` which defaults to: 

    C:\Documents and Settings\USER\Application Data

From what I see, even if I placed the `redshift.conf` in that folder, `redshift` would still not be looking for it. Could this be thought of as a bug/enhancement request so that `redshift` also checks `%appdata%` for config data in the future?

**Comment by landroni** [comment]
@lcdss 

I tried `SETX localappdata C:\Users\YOUR_USERNAME\AppData\Local` but XP doesn't seem to recognize this command and ends up in an error ("not known as internal command").

**Comment by Kasijjuf** [comment]
Try ` SET localappdata=C:\Users\YOUR_USERNAME\AppData\Local`

**Comment by lcdss** [comment]
The SET command only set temporary variables while SETX can set permanent environment variables. SETX isn't available on XP, but you can still set the variable through the control panel.

**Comment by EvertonMelo** [comment]
Try SET localappdata=C:\Users\YOUR_USERNAME\AppData\Local

Or better:

SET localappdata=%userprofile\AppData\Local

**Comment by jonls** [comment]
I'm closing this since it seems to have been resolved. Please reopen if that is not the case.

**Comment by landroni** [comment]
Yes! In the end I managed to get it to work. 

For future reference for hapless XP users, I had to: 

- `SET localappdata=C:\Users\YOUR_USERNAME\AppData\Local` (the `%userprofile` didn't seem to work) 
- place `redshift.conf` in `C:\Users\YOUR_USERNAME\AppData\Local` 
- edit `redshift.conf` to specify `adjustment-method=wingdi` (see `redshift -m list`)
- run `redshift.exe` in `cmd`


===
A couple of follow-up questions if I may: 

- Does redshift on Windows have a tray icon? Here none seems to appear...
- (Somewhat related to the above) how do you gracefully close redshift once you open it in `cmd.exe`? I tried `ctrl+c`, but I suspect that didn't do anything (and the colors didn't shift)
- It looks that the `SET` hack above is only temporary and I will have to run it on every start. Any ideas on how to automate this and make it simpler to launch redshift? 

Thanks!

**Comment by landroni** [comment]
A small update. I found a more permanent way to set the environment variable, namely by following these instructions for XP: 
http://www.computerhope.com/issues/ch000549.htm

In short, `right-click My Computer > Properties > Advanced > Environment Variables`. 


![](http://www.computerhope.com/issues/pictures/winpath.jpg)

This way the var is set permanently and I only need to run `redshift.exe` upon reboot.
