### ISSUE TITLE
No indicator icon on Linux Mint 18 w/ Cinnamon 3.0.7

### ISSUE THREAD

**Issue by ruppalsingh** [jonls/redshift#351]
I was using RedShift GTK on Linux Mint 17.3 and it worked fine. The icon was visible, even though auto-start never worked. However, that's a different issue and irrelevant to the matter at hand.

I recently made a fresh install of Linux Mint 18 which is running Cinnamon 3.0.7, and although the applet works as intended, there is no visible icon even though it takes up space in the tray. I am able to use it as normal. Autostart works out of the box. But the icon is missing.

I have tried to reinstall but that did not fix the issue.

**Comment by ruppalsingh** [comment]
The icon exists, but is so dark you can't see it on the default Linux Mint themes.

**Comment by catb0t** [comment]
Really? I can see the default icon on a dark panel, because it's pale red and white.

**Comment by ruppalsingh** [comment]
Yes, here is how it looks on my panel:

![app](https://cloud.githubusercontent.com/assets/3974019/16913406/ac29b29a-4d07-11e6-8833-f2c8c26be597.png)

**Comment by catb0t** [comment]
![icon](https://cloud.githubusercontent.com/assets/3238748/16920756/f5a125aa-4cdc-11e6-96cb-89dc73a2b851.png)

Maybe I have a different icon theme, or you do?
