### ISSUE TITLE
Screen temperature doesn't adjust until suspend-resume cycle

### ISSUE THREAD

**Issue by chiraag-nataraj** [jonls/redshift#354]
I'm using redshift 1.9 (according to redshift -V) on Debian Sid/Experimental. When redshift adjusts the color temperature, the changes don't take effect until I suspend and resume my computer (basically, the monitor is turned off and back on).
First, why would this be happening?
Second, if this is a bug, is there a way to mitigate this without having to suspend-resume?

[EDIT] I tried using sct instead and it seems the same problem holds. This is most likely an xrandr bug.

**Comment by kaipoethkow** [comment]
I am observing the same behaviour on ubuntu 16.04.

**Comment by jonpolak** [comment]
I have the same problem on Ubuntu - but it's working fine on Debian testing

**Comment by joiharalds** [comment]
I am having the same problem on Ubuntu Gnome 16.04 with redshift version 1.10 (redshift -V). I'm on a Dell xps 13 with Intel Corporation Sky Lake Integrated Graphics (rev 07).

**Comment by simontheflutist** [comment]
Same problem on 16.04 with redshift 1.1. Dell Precision 5510 with Nvidia graphics.

**Comment by kaipoethkow** [comment]
Anyone found a workaround? Switching a screen off and on again in display settings updates the temperature. But this is only feasible in a multi monitor system.

**Comment by jonpolak** [comment]
Does it change only the screen that you turn OFF/ON or all at once? You use
arandr?

**Comment by denpad** [comment]
I have the same problem.Ubuntu 16.04 and RedShift Version 1.10, screen temperature settings are not applied until suspend/resume. I found a workaround: Use display settings to change resolution of the screen. After resolution switch color temperature settings are applied.

**Comment by kaipoethkow** [comment]
I agree that the resolution switch is the better workaround (also works for single screen systems).

Anyone knowledgable enough about X to figure out a real fix for this?

**Comment by chiraag-nataraj** [comment]
Even easier actually - rotate your screen using xrandr -o inverted && xrandr -o normal. But yeah, there's something else going on here on X's part.

**Comment by thob** [comment]
for the record: f.lux doesn't work either on LM 18 (16.04)

**Comment by inactivist** [comment]
Similar problems on LM 18 -- After a reboot, Redshift's current settings take effect only after resume from suspend.  @chiraag-nataraj's  `xrandr -o inverted && xrandr -o normal` seems to have no effect here.

**Comment by thob** [comment]
Seems [Kernel related](https://bugs.launchpad.net/launchpad/+bug/1617686)

**Comment by chiraag-nataraj** [comment]
Huh interesting. That would explain why other programs like this aren't working either and why it stopped working even though I didn't update anything to do with X.

**Comment by kaipoethkow** [comment]
It works again normally for me! :)

Latest 4.4 Kernel on Ubuntu 16.04 seems to have fixed this issue. (installed it yesterday)

**Comment by jonpolak** [comment]
4.7 kernel from yakkety latest build has same problems.

**Comment by denpad** [comment]
I can confirm that since the latest update of thr 4.4 Kernel on ubuntu 16.04 changing of the screen temperature works again.

Am 1. September 2016 20:10:28 MESZ, schrieb kaipoethkow <notifications@github.com>:
>It works again normally for me! :)
>
>Latest 4.4 Kernel on Ubuntu 16.04 seems to have fixed this issue.
>(installed it yesterday)
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/jonls/redshift/issues/354#issuecomment-244163687

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by chiraag-nataraj** [comment]
Latest 4.7 kernel fixed this issue (4.7.2).
