### ISSUE TITLE
Feature request: adjust brightness based on screen content

### ISSUE THREAD

**Issue by davorb** [jonls/redshift#355]
Please see the following link to get an idea of what I think would be a great addition to redshift.

https://github.com/anishathalye/lumen

**Comment by EvertonMelo** [comment]
Hello, 
both projects has positive points, and license equals:
( RedShift )
https://github.com/jonls/redshift/blob/master/COPYING
( lumen )
https://github.com/anishathalye/lumen/blob/master/LICENSE.txt

but the structure of the projects is quite different:
( RedShift )
https://github.com/jonls/redshift/blob/master/DESIGN
( Lumen ) 
https://github.com/EvertonMelo/lumen/blob/master/README.md

It will be interesting to a fork that concentrates if these two projects.
one of the factors that prevent this, is the support of the lumen (Only OS X)

**Comment by simgunz** [comment]
These are clone of lumen for unix systems:
https://github.com/meh/dux
https://github.com/autolume/autolux

**Comment by jonls** [comment]
Thanks for reporting this. This seems to be better handled as a separate software package so I will not consider this for inclusion into Redshift at this point.
