### ISSUE TITLE
Redshift does not work on ARM based C201

### ISSUE THREAD

**Issue by ballifatih** [jonls/redshift#356]
Hello,
I succesfully compiled redshift on my ARM based RK3288 on Gentoo (Asus C201 Chromebook). When I run redshift:

`redshift -l 40:30 -m randr -v`

Location: 40.00 N, 30.00 E
Temperatures: 5500K at day, 3500K at night
Solar elevations: day above 3.0, night below -6.0
Brightness: 1.00:1.00
Gamma (Daytime): 1.000, 1.000, 1.000
Gamma (Night): 1.000, 1.000, 1.000
Status: Enabled
Period: Daytime
Color temperature: 6490K
Brightness: 1.00
Color temperature: 6480K
Color temperature: 6470K
Color temperature: 6460K
Color temperature: 6450K
Color temperature: 6440K
Color temperature: 6430K
Color temperature: 6419K
Color temperature: 6410K
Color temperature: 6400K
Color temperature: 6390K
Color temperature: 6380K
...

However the color does not change at all, even the color reported below 3000K. I tried other modes: drm, randr, vidmode, dummy -- none of them are working. However drm reports (when run as root): 

Location: 40.00 N, 130.00 E
Temperatures: 5500K at day, 3500K at night
Solar elevations: day above 3.0, night below -6.0
Brightness: 1.00:1.00
Gamma (Daytime): 1.000, 1.000, 1.000
Gamma (Night): 1.000, 1.000, 1.000
Failed to get DRM mode resources
Failed to start adjustment method drm.

My compilation configuration:

    redshift 1.11

    prefix:		/usr/local
    compiler:		gcc -std=gnu99
    cflags:		-g -O2
    ldflags:		

    Adjustment methods:
    DRM:		yes
    RANDR:		yes
    VidMode:		yes
    Quartz (OSX):	no
    WinGDI (Windows):	no

    Location providers:
    Geoclue:		no
    Geoclue2:		yes
    CoreLocation (OSX)	no

    GUI:		yes
    Ubuntu icons:	no
    systemd units:	no

**Comment by jonls** [comment]
Most likely the hardware or the video driver does not support gamma adjustments and silently ignores the requests from Redshift. This is the case for other ARM-based Chromebooks.

**Comment by ballifatih** [comment]
`xrandr --output eDP-1 --gamma 0.7:0.8:0.9` does not make any effect so randr interface is being ignored. Do you think I still have change with drm interface or is it hopeless?

**Comment by jonls** [comment]
Honesty I would be surprised if the drm method worked. I never got redshift to work on my ARM Chromebook.
