### ISSUE TITLE
redshift-gtk incompatible with xcalib

### ISSUE THREAD

**Issue by monperrus** [jonls/redshift#358]
I notice that redshift-gtk is not compatible with `xcalib -invert -alter`. It resets to normal after a few seconds.

What would be a good solution?

**Comment by maandree** [comment]
Not yet, but I'm working on it. Until then you can use [blueshift](https://github.com/maandree/blueshift).

**Comment by monperrus** [comment]
> Until then you can use blueshift <https://github.com/maandree/blueshift>.
is it better?

**Comment by maandree** [comment]
It is very flexible, but it is not user friendly. You configure it using Python, there are some example scripts that should cover most uses. It also has a small CPU and RAM overhead because it is written in Python.

**Comment by jonls** [comment]
You can run `xcalib -invert -alter` then afterwards run `redshift` with the preserve option, e.g if you are using the `randr` method add the line `preserve=1` under `[randr]` in your configuration (`~/.config/redshift.conf`). This should apply the redness on top of the inverted gamma ramps.

**Comment by v217** [comment]
This does not work on ubuntu 16.10 (If transition=1 the screen flickers, if transition=0 the screen gets darker and darker with each call to xcalib -i -a, only a reboot helps.)

    pkill redshift ; sleep 0.3 ; xcalib -i -a ; redshift &

This works:

    xcalib -i -a ; redshift

Is there a background-process solution or even better a gui solution?

By the way transition means the changes are applied slowly when calling, or the transition between minimum redshift during mid-day to maximum redshift during midnight are applied continously?

My ~/.config/redshift.conf:

    [redshift]
    adjustment-method=randr
    location-provider=manual
    transition=1
    
    [randr]
    preserve=1
    
    [manual]
    lat=48.2
    lon=16.3
