### ISSUE TITLE
Redshift strange autostart

### ISSUE THREAD

**Issue by dunnodun** [jonls/redshift#359]
So I have Redshift running on Arch Linux from the official repository. 

I start Xfce4 from my xinit with Awesome as WM. 
In Xfce4-Settings under "Application Autostart"  I've removed Redshift. My systemctl also has no redshift.service running or enabled or whatever. 
But this application still comes up after I initialized X. And that's not all, when I try to kill it it just calls it self again. 

This is really annoying because I can't use Redshift the way I want to use it. I want to dim the brightness of multiple monitors attached to my computer with Redshift running. That's not possible because xrandr and Redshift don't interact well. I have to call redshift with the b flag and that isn't possible if Redshift already runs.

**Comment by EvertonMelo** [comment]
would you like more detail the environment?

I see that if we use a script to get around this;

**Comment by jonls** [comment]
Can you check which is the parent process of the running `redshift` instance? Perhaps knowing the parent process will let you track down why Redshift keeps getting started?

**Comment by dunnodun** [comment]
pstree tells me that systemd is the parent. But "systemctl list-units --all" doesn't list redshift. 
Redshift isn't enabled or started by systemd. 

```bash
#( 2.10.16@12:52 )( dun@Arch64L ):~ systemctl stop redshift.service        
Failed to stop redshift.service: Unit redshift.service not loaded.
```

But the xfce4-taskmanager shows me a process running called "redshift" using 5,7MB RAM. I can use "pkill redshift" but then the process restarts. To kill it definitely I have to recall the kill command several times in a short period of time. Otherwise the process always restarts itself.
