### ISSUE TITLE
Left/right-click in redshift-gtk fails [KDE Plasma 5.7.4]

### ISSUE THREAD

**Issue by z3ntu** [jonls/redshift#363]
When I launch redshift-gtk on my Arch Linux computer with KDE Plasma 5.7.4, everything works as expected except that left and right-clicking the tray icon doesn't do anything.
Console doesn't output anything except Gtk deprecation warnings.

**Comment by EvertonMelo** [comment]
Insert the logs warnings here, please.

you try install Gtk Environment?

**Comment by z3ntu** [comment]
There is no terminal output if you mean that (except GTK CSS warnings, where the only non-deprecation warning is `(redshift-gtk:3063): Gtk-WARNING **: Theme directory aplets/64 of theme breeze-dark has no size field`).
And yes, I have the package `gtk3 3.20.9-1` installed.

**Comment by jonls** [comment]
Does clicking work with other tray icons? It seems that tray icons work very differently across desktop environments so perhaps this is KDE specific?

**Comment by z3ntu** [comment]
Left-clicking other entries open the respective menu and also right-clicking reveals a menu for all.

**Comment by BlackDragon84731** [comment]
Same issue on Plasma 5.8.2. Right click works for other tray icons (e.g. Steam).

**Comment by gcomes** [comment]
To restore right click functionality you need to install libappindicator3. On opensuse 42.2 that means:
`zypper in libappindicator3-1 typelib-1_0-AppIndicator3-0_1`
You also need a recent plasma release (I think 5.7 or newer).
Left click still does not work.

**Comment by z3ntu** [comment]
`sudo pacman -S libappindicator-gtk3` worked on Arch Linux too, thanks.

**Comment by BlackDragonK99** [comment]
Package libappindicator-gtk3 (Arch Linux) fixed the issue for me too.

**Comment by jonls** [comment]
@gcomes Thanks.
