### ISSUE TITLE
[Enhancement Request] Additional Color Adjustment Modes

### ISSUE THREAD

**Issue by jkulesza** [jonls/redshift#364]
Could other color adjustment modes be introduced?  For example, an application like this could also be useful for checking how graphics display under conditions such as 

- Desaturated / greyscale (e.g., printed on a non-color printer)
- Various forms of colorblindness (see https://gist.github.com/jcdickinson/580b7fb5cc145cee8740 for example color conversions)

**Comment by jonls** [comment]
Yes, this is definitely possible. Feel free to play around with the code or use the code to create such an app. However, the purpose of Redshift is specifically to apply a redness effect at night so it's unlikely that I will include such features in Redshift.

**Comment by mrpewpew** [comment]
I am interested in getting a greyscale display. Any hint on how to implement it ?

**Comment by jkulesza** [comment]
Necessary RGB transformations are here: https://github.com/jkulesza/peacock

Note that the algorithms are only for non-commercial use. I’d run incorporating them by the fellow I cite in the license information.

**Comment by jonls** [comment]
@mrpewpew @jkulesza Looking at this again, I'll have to add that some transformations will be possible but there's a limit to what you can do with the gamma ramps. For example, grayscale is not possible. I haven't looked into the other transformations you proposed, they may or may not be possible.
