### ISSUE TITLE
[Issue] Redshift flashing after launch.

### ISSUE THREAD

**Issue by bknie1** [jonls/redshift#375]
I'm having an issue with Redshift wherein, upon starting, the screen will gradually flash and dim until it hits the very warm candlelight setting and then immediately cools to 0. Every few seconds Redshift will flash back to that candlelight setting for a split second before returning to the cooler setting. I've uninstalled/reinstalled multiple times; both the standard terminal and GUI versions.

Fairly new to Redshift and Linux. I'm running Mint Sarah and have tried both installing via available distro packages and manually using the tarball on the Redshift site. I have also tried both my integrated Intel GPU and the NVIDIA GPU to no avail. I've also tried specifically running as root to see if there was a permissions problem.

If you have any specific questions I will try to oblige. F.lux is mandatory for me (on Windows) so I was excited to see something similar here! Hopefully I can get it working.

Thank you.

**Comment by bknie1** [comment]
Update: It may have something to do with using my conservative Intel GPU and my performance NVIDIA GPU. I checked for conflicting processes as well. Right now, things are running fine. However, I'm going to do some more testing.

**Comment by catb0t** [comment]
I'm having this issue too, and I do have an integrated Intel GPU (no other GPUS), and I'd like to know how to make it stop.
