### ISSUE TITLE
Failed to start adjustment method randr.

### ISSUE THREAD

**Issue by TurtleDogBird** [jonls/redshift#376]
Starting redshift gives me the following error:
```
Gamma ramp size too small: 0
Failed to start adjustment method randr.
Trying next method...
Using method `vidmode'.
```
No color change is noticed.

uname -a shows:
`4.4.0-42-generic #62-Ubuntu SMP Fri Oct 7 23:11:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

Redshift used to run fine, it just stopped the last day(s).

**Comment by TurtleDogBird** [comment]
Solved by reinstalling Nvidia video driver.

Redshift did not cause this problem, something was wrong with the display/video drivers (i guess). The command `sudo lshw -c video` told me the display was unclaimed. Reinstalling drivers fixes this.

**Comment by willbush** [comment]
@TurtleDogBird I had the same issue, and it was also solved by reinstalling my Nvidia driver. My driver acting up was also jacking up alacritty terminal.
