### ISSUE TITLE
ERROR: randr set crtc gamma 148

### ISSUE THREAD

**Issue by mattia-b89** [jonls/redshift#380]
I'm on Arch Linux with latest Gnome (3.22)

when DE starts I get this error `geoclue: randr set crtc gamma 148`
there is neither the tray icon or a color temperature change

if I try to launch manually from terminal and with the verbose switch I can see `redshift` that decreases colour temperature but nothing happens!

I'm here for further information

**Comment by mattia-b89** [comment]
I attach the screenshot of error message: http://imgur.com/a/ZE678

**Comment by mattia-b89** [comment]
I want to add that I can see this message only when I change the monitor configuration, using key combination:
I have an external monitor connected via DP<->HDMI;
I power on my laptop and it automatically uses the internal monitor extended with the external one;
Now, if I change the monitor configuration I can see the error message;

anyhow, `redshift` doesn't work both before and after the switch.

**Comment by mattia-b89** [comment]
EDIT:
I'm on Wayland
If I switch back to Xorg, everything works like a charm

**Comment by jonls** [comment]
The 148 is the error code from randr. I haven't yet been able to determine what that means.

**Comment by jonls** [comment]
This seems to be related to Wayland. Closing this issue as it is a known limitation.
