### ISSUE TITLE
Unknown adjustment method `randr'.

### ISSUE THREAD

**Issue by MingYueRuYa** [jonls/redshift#381]
my os is CentOS7，I download source code and compile.then I run redshift, output this message "Unknown adjustment method `randr'.".so, What should I do?

**Comment by jonls** [comment]
If you want to use randr you have to enable it during compile, i.e. `./configure --enable-randr`. This will probably fail because you are missing a dependency but it should tell you which one.

**Comment by MingYueRuYa** [comment]
Hi, Thank you very much. I do what you said, and recompiled. the problem was resolved.
