### ISSUE TITLE
Redshift stops for a couple of seconds after playing a Youtube video at night

### ISSUE THREAD

**Issue by matteocoder** [jonls/redshift#388]
If I start my machine at night and thus Redshift is active right after startup, the first time I play a Youtube video the filter would go away for a couple of seconds and then come back. I'm using Ubuntu 16.04 with the Unity 7 DE. _

**Comment by erhkim** [comment]
I get an issue very similar to this in that when I boot into my machine, Redshift turns off for a few seconds when I launch nautilus (file manager) or Google Chrome. It happens every single time I boot into Fedora.

OS: Fedora 24
Machine: Thinkpad T450s
Triggers: Launching Chrome / Nautlus (there may be more but I haven't tested beyond this)

**Comment by fmeynadier** [comment]
Same symptom (even during day) when launching rhythmbox on gnome 3 / ubuntu 16.10 : color temperature briefly gets back to bluer value, which makes me think redshift briefly loses control on this parameter.

This only occurs at first launch (i.e. if I quit and launch rhythmbox again, no changes in color temperature are seen).

**Comment by jonls** [comment]
This is known limitation that Redshift unfortunately cannot prevent. Other software will sometimes try to reset the gamma ramps which will override the redness effect applied by Redshift. Please report this to the developers of the software that does this.
