### ISSUE TITLE
Redshift not changing color on Arch with Gnome

### ISSUE THREAD

**Issue by ForsakenHarmony** [jonls/redshift#390]
Arch 4.8.4-1
Redshift 1.11-3
GDM 3.22.1

As said in the title, it runs, gets the location and according to the verbose output, changes the color temp, but in reality nothing changes

**Comment by cisoun** [comment]
Are you currently using Wayland ? It's written in ArchLinux's wiki that it only works with Xorg.
Switching to Xorg from GDM should do the trick.

**Comment by pseudoj** [comment]
Also having the same problem, using the latest packages at the time of writing. Like OP, I'm running GNOME and gdm. Graphics wise, I'm running an AMD RX 480 with the `xf86-video-ati` driver.

**Comment by joaojotta** [comment]
I'm using Arch (Antergos with Cinnamon) and have everything up to date. Redshift never worked for me except one day when some program crashed my system and when it came back it just started working.

**Comment by jonls** [comment]
This seems to be related to Arch switching Wayland on by default. I'm closing this as this is a known issue.
