### ISSUE TITLE
redshift-gtk does not start automatically on linux mint / MATE 

### ISSUE THREAD

**Issue by unxed** [jonls/redshift#391]
I'm using Linux Mint 18 with MATE desktop.

Default autorun option does not starts redshift-gtk on system startup.

Had to add second autostart shortcut manually into ~/.config/autostart for redshift-gtk to start correctly.

**Comment by unxed** [comment]
seems that redshift-gtk fails to start only if internet connection is unavailable/unstable. see #393

**Comment by Kcchouette** [comment]
@unxed you can start `redshift-gtk` with the coordinate: `redshift-gtk -l LAT:LON`
