### ISSUE TITLE
redshift-gtk: ubuntu/mint packaging/dependencies problem

### ISSUE THREAD

**Issue by unxed** [jonls/redshift#392]
redshift-gtk depends on packages "geoclue-2.0" and "geoclue-hostip"
had to install them by hand
guess those two should be added as package dependencies

**Comment by Shagon94** [comment]
Can confirm that installing those 2 dependencies fixes the issue and runs the application normally.

**Comment by jonls** [comment]
This seems to be a distribution-related issue. If the Ubuntu/Mint package does not install geoclue-2.0 and geoclue-hostip, please report this to the distribution.
