### ISSUE TITLE
Set hours of effect's start and end

### ISSUE THREAD

**Issue by Kern3l** [jonls/redshift#397]
Hey,

the main benefit of Redshift is melatonin production. The hormone is a natural "go to sleep" signal and it's crucial for our rest. On the other hand, we need to not have it when we want to remember or concentrate, because it's harmful for these. So in the perfect world we would have long waking hours and proper time for rest - without melatonin and with plenty, respectively. Ratio of 16:8 would seem quite nice, if not idealistic. But melatonin is produced only when there's no blue light. That's where Redshift is helping a lot. 

The trouble is - Redshift uses natural day/night ratio, which is not optimal for our daily schedules. The best would be if Redshift turned on 1-3h prior to our sleep time's start (I don't know how much hours exactly) and turned off just before our alarm. But now it just aligns with natural day-night cycle, so it's almost always not optimal. For example in my case I'd love to have it turning on at 23 and stop around 6-7. To achieve that, I have to fake my location. Currently I pretend to be at King Edward Point while really I'm in Europe. 

The problem with this faking is that it stops working very quickly, because Redshift is actively working against it. So hacking approach would be to just automatically, periodically update longitude to follow sun.

Could you stop that madness and allow us to set start-end hours in configuration files? Thank you in advance! This would be a great feature that others don't have.

**Comment by ttyusupov** [comment]
:+1:  - that would be vey usefull, it is too early to have night starting at 3PM in Winter.

**Comment by Kern3l** [comment]
BTW the easier hack for this is a check in cron what hour it is and `pgrep redshift || redshift &` to turn it on and `pkill redshift` to turn it off. You can do it with oneliner using `if` or with two entries in the crontab.

**Comment by Lamieur** [comment]
However, normal redshift-gtk operation is taking a long time for a very gradual switch from blue to red (perhaps shorter where you live - here up north the curvature of the planet means it's still reasonably bright for hours after sunset in the summer - I believe redshift takes the over-horizon refraction into account, that's how smart it is!)

But if you just manually start from cron when it's already in full "night" mode (midnight in the example, but even now at 16:00, we're like 1 minute off from shortest day of the year still), it drops from 6500K to 3500K in just 10 seconds, which is really disturbing visually, I feel very uncomfortable after such quick switch. This is not the case with the normal gradual reddening that redshift provides.

What redshift needs then is "working hours", when I have 3500 lm of lights in the room anyways even though it's "night" outside. Let that transition start at 22:00 (in my case, many people will prefer 20:00) but take an hour.

PS. You don't need to `pkill redshift` every minute, it's already dead :)

**Comment by chrylis** [comment]
I just found Redshift after using Twilight on my phone for a long time, and this is the main downside I found: I'd like to be able to adjust the color to my own schedule and not necessarily follow outdoors.

**Comment by jonls** [comment]
Thanks for your suggestion. This has been suggested a number of times in the past. Please continue any constructive discussion towards this feature in #9. As I've mentioned in that issue, I'm not personally interested in using the feature that you are suggesting but I'm not against including the option to use such a feature in Redshift provided that someone implements it in a reasonable and maintainable way. I have previously suggested that the D-Bus support could be used to support this feature, though I haven't had time to finish that and nobody else has taken up that work. If you want to contribute to getting this feature included, the D-Bus support branch could be the place to start.
