### ISSUE TITLE
Feature Request: Sample OS X launchd plist

### ISSUE THREAD

**Issue by Kithop** [jonls/redshift#398]
Hi,
I've got a suggestion for those of us compiling and running this on OS X (tested with macOS Sierra 10.12.1) - while a MenuItem icon for enabling/disabling would be great, I've managed to put together something for running redshift on startup (_without_ leaving an ugly Terminal window up you can't kill) with a couple commands to start and stop it properly the 'macOS way':
```
$HOME/Library/LaunchAgents/dk.jonls.redshift.plist
--------------------------------------------------

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>dk.jonls.redshift</string>

	<key>ProgramArguments</key>
	<array>
		<string>/usr/local/bin/redshift</string>
	</array>

	<key>Nice</key>
	<integer>20</integer>

	<key>RunAtLoad</key>
	<true/>

	<key>KeepAlive</key>
	<true/>
</dict>
</plist>
```

You can just log out and back in to have this take effect immediately, or also try:
`launchctl load $HOME/Library/LaunchAgents/dk.jonls.redshift.plist`
It will auto-start on load (as per that 'RunAtLoad' tag - which you could also omit if you don't want that behaviour).

Then you can use the commands:
`launchctl stop dk.jonls.redshift`
`launchctl start dk.jonls.redshift`
to stop and start the process (verified with `ps -u $USER | grep redshift`) while logged in.

If you make changes to the plist file, you can use I believe `launchctl unload $HOME/Library/LaunchAgents/dk.jonls.redshift.plist` to remove it, then reload it as above.

It does seem to load `$HOME/.config/redshift.conf` properly as well, so this way it's installed only as your user and can be customized that way (e.g. with that handy new quartz preserve mode!)

_If you've changed your $PREFIX when installing, you'll need to update the path in the plist file above to wherever redshift resides, of course._

**Comment by jonls** [comment]
Thanks :+1: I'll add this file in the `contrib` directory (#419).
