### ISSUE TITLE
OpenSUSE package installed in /usr/lib/ - not /usr/lib64

### ISSUE THREAD

**Issue by cbcoutinho** [jonls/redshift#401]
I installed all the required depedencies of redshift using openSUSE's package manager; however it installed everything into /usr/lib/python.... instead of /usr/lib64/python....

Now it won't start up because there's an error at `import gi`, which is supplied by pygobject

I'm not sure if this can be solved by you or if it's an openSUSE problem, can you point me in the right direction?

**Comment by cbcoutinho** [comment]
So looking further into the issue, it looks like redshift was using my Anaconda-installed version of python instead of the openSUSE generic version. my solution is pretty kludgey, and won't be valid when redshift is updated on my system.

I had to change the crashbang of redshift-gtk from:

```
#!/usr/bin/env python3
```
to 

```
#!/usr/bin/python3
```


Do you have a better idea?

**Comment by cbcoutinho** [comment]
I also had to follow the steps in #158 by adding the following lines to `/etc/geoclue/geoclue.config`

```
[redshift]
allowed=true
system=false
users=
```

**Comment by jonls** [comment]
Thanks for your issue report. This seems to be related to that way OpenSUSE packages Redshift so I would ask on the OpenSUSE forums or report it to OpenSUSE developers.
