### ISSUE TITLE
Can't neither access Redshift nor edit any information on it

### ISSUE THREAD

**Issue by kenkao70508** [jonls/redshift#404]
OS: Fedora 25.
After open up os, my screen's temperature doesn't seem to change at all.
Therefore, I try to **access redshift** and **set the location** from my terminal.

However, I can't open redshift from my terminal. It just stopped moving.

![screenshot from 2016-11-27 01-11-03](https://cloud.githubusercontent.com/assets/24192773/20642004/b3ba4000-b3c9-11e6-8d1b-8072efac1156.png)

Secondly, I can't change the location. It just stopped moving.

![screenshot from 2016-11-27 01-19-54](https://cloud.githubusercontent.com/assets/24192773/20642025/4f56a5b2-b3ca-11e6-8b22-4581fd0fb09d.png)

one of actions I can do is  opening up the instruction menu.

![screenshot from 2016-11-27 01-25-34](https://cloud.githubusercontent.com/assets/24192773/20642048/184d5c22-b3cb-11e6-9ab5-ecdad3c18a99.png)

 I really don't know how to fix former two problems!

**Comment by jonls** [comment]
Fedora 25 uses Wayland be default which does not support Redshift adjustments. I suspect you are not seeing any adjustments for this reason. You can switch back to X11 which should make Redshift work again.
