### ISSUE TITLE
Option to only activate Redshift at Nightime

### ISSUE THREAD

**Issue by magiruuvelvet** [jonls/redshift#406]
I'd like to see an option to instruct Redshift to only change settings at Nighttime and stay deactivated at Daytime without actually terminating it. Currently I use f.lux and it only changes the color temp at nighttime (my prefered behavior).

I want to use Redshift as systemd service without starting/stopping it manually all the time.

**Comment by maandree** [comment]
Not precisely sure what you are asking for. Do you define night by solar elevation or time?
If you define it by solar elevation, you set that in the configuration file. If you are defining it
by time, the best thing you can do is use cron to send SIGUSR1 to redshift.

**Comment by GhettoGirl** [comment]
Thats my current config file. Redshift changes settings at daytime too and basically makes everything weird looking (white/very light tint?).

```
[redshift]
temp-night=3500
transition=1
gamma-night=0.730
location-provider=manual
adjustment-method=randr

[manual]
lat=(removed)
lon=(removed)
```

**Comment by maandree** [comment]
Add `temp-day = 6500` under `[redshift]`.

**Comment by GhettoGirl** [comment]
`6500` is too bright on my laptop screen. It's definitely a lower value, but I couldn't find it :(
I guess I will just continue using f.lux as I never had any problems with it and I don't want any temp/gamma manipulation during day.

**Comment by maandree** [comment]
6500, should be like redshift is inactive, 6500 is the neutral colour temperature, if you change it to something between 5500 and 6500 if the default temperature during the day for redshift is too red but the neutral colour too white. If you want the colour to be white, but less bright, you can use change `brightness-day` and `brightness-night` in the configuration file.

But I would recommend removing everything except your location from the configuration file, and try to get used to the default settings. If your monitor is too bright you can set the backlight manually and have it static.

**Comment by Immortalin** [comment]
@GhettoGirl just put redshift in a cron job and have it activate at night, another cron job to kill it during daytime.

**Comment by Immortalin** [comment]
lintltool

**Comment by jonls** [comment]
@magiruuvelvet Thanks for your suggestion. As @maandree mentioned, the temperature setting at 6500 is literally interpreted by Redshift as no redness adjustment. If you still have issues with the adjustment at 6500, please reopen this issues.
