### ISSUE TITLE
Redshift should discriminate according with current location weather.

### ISSUE THREAD

**Issue by sackery** [jonls/redshift#411]
Example: if current day is cloudy sky then display will dimished a little.

**Comment by maandree** [comment]
I'm not sure this is something that should be in redshift, however,
here is some relevant information for interpreting whether reports:
https://www.youtube.com/watch?v=TGeGVd7J6dQ

**Comment by jonls** [comment]
@maandree 👍 

@sackery Thanks for the suggestion. As far as I can tell this would require Redshift to get local cloud cover data from a weather API. I don't think this is something I want to include at this point. I don't think the value of such  a feature is worth the development and maintenance effort.
