### ISSUE TITLE
Ensure -p always prevents modifying terminal

### ISSUE THREAD

**Issue by jidanni** [jonls/redshift#414]
Man page says -p won't mess with my terminal, but
```
redshift -p -l 24:121 -o
```
does anyway.

**Comment by jonls** [comment]
This is because you are specifying print mode (`-p`) but then later you specify one-shot mode (`-o`). The last mode selection on the command line is the one used by Redshift.

**Comment by jidanni** [comment]
Well I hope all that is documented. Also it should print a warning perhaps.
