### ISSUE TITLE
Ensure -r always prevents modifying temperature

### ISSUE THREAD

**Issue by jidanni** [jonls/redshift#415]
Man page says

```
       -r     Disable temperature transitions
```
but
```
redshift -o -l 24.2:120.8 -r -b 0.9:0.8
```
changes them anyway. So maybe "transitions" doesn't mean changing...

**Comment by jonls** [comment]
Transition is the 10 second period after starting Redshift where the redness effect is gradually applied. With `-r`, the redness effect is instantly switched on. In your example, you are using one-shot mode (`-o`) so transitions are disabled in any case.

**Comment by jidanni** [comment]
Well I hope all that is documented. Also it should print a warning perhaps.
