### ISSUE TITLE
Use Ubuntu Systray icons on ElementaryOS

### ISSUE THREAD

**Issue by thesleort** [jonls/redshift#431]
I find the white single color icons far more pleasant to look at. especially on elementaryOS where colored icons such as hicolor icons don't fit well with the design.

I will therefore propose a change, so that redshift shows the ubuntu-mono-light/dark on elementaryOS too, like it does on Ubuntu. Remember that elementaryOS changes to dark icons when the background is very light (done automatically). It simply means that both icons should be available for elementaryOS.

**Comment by alexgleason** [comment]
I second this, but is this elementary OS's fault? I'm not 100% how themes work but I think the fact it prefers hicolor after its own theme is an OS issue. Ideally it would go: elementary, ubuntu-mono-dark, hicolor. We could probably fix this by creating a symlink from the mono-dark icon into the elementary icons directory.

**Comment by jonls** [comment]
I'm not sure if this can be fixed from our end but if someone can provide a way to do so we can implement it. It may be easier to fix in the elementaryOS packaging though.
