### ISSUE TITLE
How to permanently change color temperature?

### ISSUE THREAD

**Issue by nucamoz** [jonls/redshift#433]
Thank you for awesome software, switched from f.lux. But here's the problem - I can't find how to permanently change color temperature.

`redshift -O 3700`

This command change color until the reboot, but I want to change it permanently.

**Comment by maandree** [comment]
Put that command in your `.xinitrc` and if you use the TTY in /etc/rc.local (or whatever your init system uses).

**Comment by nucamoz** [comment]
I am using Ubuntu, not so long. Can you please provide more details where to put this command? As I understand that command will perform every boot?

**Comment by maandree** [comment]
I assume you use a graphical login manager. In this case I think you should add `redshift -O 3700` to some auto-start the login manager provides (so the temperature is set when the the login manager starts). But I'm not sure how you do this.

**Comment by nucamoz** [comment]
What is that "graphical login manager"? Do you intend to use such words?))

**Comment by nucamoz** [comment]
Anyway, I fixed this with redshift.conf file.

**Comment by maandree** [comment]
Well, the proper name is display manager, but I think that is a confusing term.

Ah, I think you also wanted redshift autostart.
