### ISSUE TITLE
Temperature adjustment failed in Windows

### ISSUE THREAD

**Issue by pauby** [jonls/redshift#435]
When I run this:
```
redshift -l 55:-3 -t 5700:3600 -v -g 0.8
```

I get this:

```
Location: 55.00 N, 3.00 W
Temperatures: 5700K at day, 3600K at night
Solar elevations: day above 3.0, night below -6.0
Brightness: 1.00:1.00
Gamma (Daytime): 0.800, 0.800, 0.800
Gamma (Night): 0.800, 0.800, 0.800
Using method `wingdi'.
Status: Enabled
Period: Night
Color temperature: 6471K
Brightness: 1.00
Unable to set gamma ramps.
Temperature adjustment failed.
```

I did see that this has already been fixed under #121 but I'm still getting the error. I've not found anything else to help with it hence raising this issue.

The command `redshift -O 4800` works fine.

I'm running Windows 10 with an Nvidia GTX 1080 and three monitors.

**Comment by shunjou** [comment]
Are you using a build that includes [the commit](https://github.com/arnej/redshift/commit/cd4f7865bd9876b5520f9478eb35467270d94a44) from #296? That pull request never got merged since I think it wasn't quite complete yet.

**Comment by pauby** [comment]
I've moved away from Redshift now so I can't provide any more on this. Closing.

**Comment by diegorodriguezv** [comment]
Hi. It seems like this bug has been fixed in version 1.11.

**Comment by jonls** [comment]
@diegorodriguezv Thanks, yes this should hopefully not occur anymore since #524 was merged.

**Comment by zvezdochiot** [comment]
Win10.  
redshift 1.12  
```sh
redshift -c redshift.conf
Waiting for initial location to become available...
Location: 55.75 N, 37.62 E
Unable to set gamma ramps.
Temperature adjustment failed.
```
`redshift.conf`
```sh
[redshift]
temp-day=5700
temp-night=3500
fade=1
gamma=0.8
location-provider=manual
adjustment-method=wingdi

[manual]
lat=55.75
lon=37.62

[randr]
screen=0
```

**Comment by AKVsn** [comment]
Enabling Duplicating displays may cause the problem.
