### ISSUE TITLE
Setup Windows build on AppVeyor

### ISSUE THREAD

**Issue by shunjou** [jonls/redshift#438]
There have been windows binaries released up to version 1.10 but not for the 1.11 release. Is it possible to get an updated windows binary?

EDIT: I just noticed [the simple build instructions](https://github.com/jonls/redshift/blob/master/HACKING.md) and compiled [my own binary](https://dl.dropboxusercontent.com/s/b1j327cohyxzofv/redshift-1.11-windows.zip).

**Comment by fohrums** [comment]
+1 as per release, should have windows install variant (as you said, binary).

**We request a .exe for every new redshift update**

**Comment by jonls** [comment]
I think we can build windows binaries on AppVeyor so they are built automatically. Someone needs to create an `appveyor.yml` file for this.

**Comment by manuc66** [comment]
I tried to do it in https://github.com/manuc66/redshift/tree/build-release-1.10 but it seems to generate an executable that does nothing: https://ci.appveyor.com/project/manuc66/redshift/build/artifacts 

What did I missed ?

**Comment by jonls** [comment]
@manuc66 Thanks for looking into this 👍  The build seems to have failed with "configure: error: Your intltool is too old.  You need intltool 0.50 or later.": https://ci.appveyor.com/project/manuc66/redshift

**Comment by manuc66** [comment]
@jonls the build you saw was not on the same branch (I made several tries), this have you an idea regarding this build: https://ci.appveyor.com/project/manuc66/redshift/build/1.0.80

Thanks
