### ISSUE TITLE
New limitation found with DRM backend

### ISSUE THREAD

**Issue by maandree** [jonls/redshift#441]
DRM disables Linux VT's colour palette on some machines, which means that whilst DRM is in use, you will have the default palette. Your custom palette is reinstated automatically once DRM is not in use any more.

**Comment by maandree** [comment]
I think this is fixed by updating the graphics driver.

I found a related limitation that seem to appear on all machines, it is not possible to change the palette whilst DRM is in use.

**Comment by jonls** [comment]
Ok, thanks for documenting this. This could be added to the documentation or FAQ if this question comes up again in the future.
