### ISSUE TITLE
Redshift shows no effect under Xfce

### ISSUE THREAD

**Issue by sidamos** [jonls/redshift#443]
Without logging any errors, the adjustment of Redshift 1.11 has no visible effect when running under Xfce.

On the same machine, with the same xorg.conf, it has visible effect (is working fine) under KDE 4 and 5.

I tried without "-m" and with "-m vidmode" and "-m randr".

I also tried switching compositing off.

I am using the Nvidia binary driver.

This is the output of "redshift -v":

Location: 48.89 N, 8.33 E
Temperatures: 6500K at day, 3700K at night
Solar elevations: day above 3.0, night below -6.0
Brightness: 1.00:1.00
Gamma (Daytime): 1.000, 1.000, 1.000
Gamma (Night): 1.000, 1.000, 1.000
Using method `randr'.
Status: Enabled
Period: Night
Color temperature: 6472K
Brightness: 1.00
Color temperature: 6444K
Color temperature: 6416K
Color temperature: 6388K
Color temperature: 6360K
Color temperature: 6332K
Color temperature: 6304K
Color temperature: 6275K
Color temperature: 6247K
Color temperature: 6219K
Color temperature: 6191K
Color temperature: 6163K
Color temperature: 6136K
Color temperature: 6108K
Color temperature: 6080K
Color temperature: 6052K
Color temperature: 6024K
Color temperature: 5996K
Color temperature: 5968K
Color temperature: 5940K
Color temperature: 5912K
Color temperature: 5884K
Color temperature: 5856K
Color temperature: 5827K
Color temperature: 5799K
Color temperature: 5771K
Color temperature: 5743K
Color temperature: 5715K
Color temperature: 5687K
Color temperature: 5659K
Color temperature: 5631K
Color temperature: 5603K
Color temperature: 5575K
Color temperature: 5547K
Color temperature: 5519K
Color temperature: 5491K
Color temperature: 5463K
Color temperature: 5435K
Color temperature: 5407K
Color temperature: 5379K
Color temperature: 5351K
Color temperature: 5323K
Color temperature: 5295K
Color temperature: 5267K
Color temperature: 5239K
Color temperature: 5211K
Color temperature: 5183K
Color temperature: 5155K
Color temperature: 5127K
Color temperature: 5099K
Color temperature: 5071K
Color temperature: 5043K
Color temperature: 5015K
Color temperature: 4987K
Color temperature: 4959K
Color temperature: 4931K
Color temperature: 4903K
Color temperature: 4875K
Color temperature: 4847K
Color temperature: 4819K
Color temperature: 4791K
Color temperature: 4763K
Color temperature: 4735K
Color temperature: 4707K
Color temperature: 4679K
Color temperature: 4651K
Color temperature: 4623K
Color temperature: 4595K
Color temperature: 4567K
Color temperature: 4539K
Color temperature: 4511K
Color temperature: 4483K
Color temperature: 4455K
Color temperature: 4427K
Color temperature: 4399K
Color temperature: 4371K
Color temperature: 4343K
Color temperature: 4315K
Color temperature: 4287K
Color temperature: 4259K
Color temperature: 4231K
Color temperature: 4203K
Color temperature: 4175K
Color temperature: 4147K
Color temperature: 4119K
Color temperature: 4091K
Color temperature: 4063K
Color temperature: 4035K
Color temperature: 4007K
Color temperature: 3979K
Color temperature: 3951K
Color temperature: 3923K
Color temperature: 3895K
Color temperature: 3867K
Color temperature: 3839K
Color temperature: 3811K
Color temperature: 3783K
Color temperature: 3755K
Color temperature: 3727K
Color temperature: 3700K

**Comment by Kalagon** [comment]
Do you use the ForceFullCompositionPipeline Metamode option in your /etc/x11/* configs? Enabling this for both monitors seems to break Redshift with newer nvidia drivers/xorg servers. I'm trying to find out why this happens, as it's annoying but so far I've found no solution other than not setting the MetaMode option.

**Comment by Kalagon** [comment]
Okay, I can definitely say that not setting "ForceFullCompositionPipeline" in the xorg configs solves this probem. I don't know what causes it, as enabling the option in the Nvidia X Server settings after logging in works fine.
Setting this on only one monitor breaks redshift on that one, but the other one works fine.
This is not restricted to xfce though, as I get the same behavior in Cinnamon.
I'm on Arch Linux with a GTX 760, dual monitors, completely up-to-date. Versions are:
nvidia-378.13-2
xorg-server-1.19.2-1

**Comment by sidamos** [comment]
I am using { ForceCompositionPipeline = On } in xorg.conf (so, not "Full", but similar) to prevent screen tearing under Xfce.

But even with this option in xorg.conf, Redshift still works fine under KDE 5.

**Comment by sidamos** [comment]
Today it works and I don't know, what I changed...

**Comment by nick-s-b** [comment]
Can confirm: ForceCompositionPipeline disables Redshift with Nvidia binary driver.

After using Nvidia binary driver for few months without ForceCompositionPipeline, I had to enable it because sometimes some windows in GNOME would flicker. Settin ForceCompositionPipeline=On fixed that... but now Redshift doesn't work.

**Comment by jonls** [comment]
Ok, this seems be related to the nVidia binary driver and `ForceFullCompositionPipeline`. Please keep posting if a workaround is found.

**Comment by ajwbae** [comment]
I seem to have found a workaround, where if you make a **.desktop** file in your "~/.config/autostart" folder, then edit its properties and set the command as:

`nvidia-settings --assign CurrentMetaMode="nvidia-auto-select +0+0 { ForceFullCompositionPipeline = On }"`

it will allow Redshift to work with _ForceFullCompositionPipeline_, and it will be enabled on login.

Alternatively, on XFCE, you can do this through **Session and Startup -> Application Autostart**, and add an item with the _command_ field having the code shown above. Hope this helps.

**Comment by ng0177** [comment]
Under aarch64 4.19.89-1-MANJARO-ARM Xfce, redshift is not working either.
