### ISSUE TITLE
Mention redshift-gtk in the man page

### ISSUE THREAD

**Issue by Powersource** [jonls/redshift#448]
The only reason I found it now was because it's on the path.

**Comment by jonls** [comment]
Thanks for the suggestion 👍  This seems like a reasonable addition to the man page.

**Comment by lepatrick714** [comment]
Hello, 

Just saw this issue. Maybe we could include this when the user downloads redshift? 

https://askubuntu.com/questions/244809/how-do-i-manually-install-a-man-page

**Comment by Powersource** [comment]
@lepatrick714 I think you are misunderstanding, we have a manpage already. I am proposing a change to it. https://github.com/jonls/redshift/blob/master/redshift.1

**Comment by lepatrick714** [comment]
Ahh! my apologizes!
