### ISSUE TITLE
Add maintainers to the project

### ISSUE THREAD

**Issue by Powersource** [jonls/redshift#449]
Not complaining about the current ones, but there are many old PRs right now with passing builds but no comments. I think it would be good for the project to get some new maintainers to not have the project stall.  
(I'm not volunteering btw, but people who are interested could comment here I guess?)

**Comment by jonls** [comment]
I agree, additional contributors or maintainers are most welcome. Any suggestions on what is needed to make it easier to help out?

**Comment by Powersource** [comment]
The project seems more active now but my concern wasn't with how easy it was to help out, as I said there were plenty of PRs. The problem was that the PRs needed someone with merge  rights to take a look at them and approve/decline them.

**Comment by ingochris** [comment]
Yeah, open PRs are definitely aging (I noticed several from 2013).

**Comment by jonls** [comment]
Another issue was opened with a similar question here (https://github.com/jonls/redshift/issues/556) where I provided a longer reply. The tl;dr is that just because a PR has been open since 2013 doesn't mean it's ready to merged.
