### ISSUE TITLE
Redshift causes screen to blink on running redshift-gtk

### ISSUE THREAD

**Issue by lazyy** [jonls/redshift#451]
On running the command -> redshift-gtk, redshift gets started but with below warning :
/usr/lib/python3/dist-packages/redshift_gtk/statusicon.py:32: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GLib, GObject
/usr/lib/python3/dist-packages/redshift_gtk/statusicon.py:35: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as appindicator
Now, the screen blinks regularly getting red and then again normal.
Redshift version : 1.10
Kernel version : 4.4.0-66-generic

**Comment by chiraag-nataraj** [comment]
Make sure you're not running two instances: `pgrep -x redshift` and make sure there's only one instance. I've seen this behavior when I accidentally started multiple instances.

**Comment by jonls** [comment]
Since there has been no more activity on this, I'm going to close this issue.
