### ISSUE TITLE
Control redshift via terminal?

### ISSUE THREAD

**Issue by Trollwut** [jonls/redshift#452]
Hi folks!

Are there ways to control redshift via terminal?

In particular I'd need two commands:

1. One to toogle `redshift` on/off (like clicking the GTK icon)

2. One to check in which state (on/off) redshift currently is

Did I miss something when reading about available commands? :x

**Comment by marsjaninzmarsa** [comment]
Probably the best way to do that will be via DBus, if I'm right you can look into `redshirt-gtk` code for reference.

**Comment by maandree** [comment]
You cannot get the current state, but you can use `pkill -x -USR1 redshift` to toggle.
I have also written some interfaces: https://github.com/maandree/nightshift, https://github.com/maandree/redshift-adjust

**Comment by peterhoeg** [comment]
IMHO, dbus support would be a killer feature here.

It would allow all the various frontends (gtk/plasma/cli) to be exactly that - frontends - that interface with one process that handles the actual changing. Nobody has to reinvent the wheel.

@jonls, is this the direction you would want to move in? If so, I'll take a stab at adding dbus support.

**Comment by jonls** [comment]
@peterhoeg I agree. There is a partial D-Bus implementation in #54 that I never found time to finish but it is working quite well.

**Comment by epgfm** [comment]
Other cool thing querying state by terminal would allow for:
-> tying keyboard backlit to redshift state

**Comment by peterhoeg** [comment]
I haven't had the time to work on dbus at all, just FYI.

**Comment by jonls** [comment]
Let's move any future discussion to #54. Closing this issue.
