### ISSUE TITLE
Change Icon

### ISSUE THREAD

**Issue by nebutron** [jonls/redshift#457]
Wondering how I can change the icon used in the system tray (using cinnamon DE).

I want to use my own icon for it. Sorry if this isn't the right place to ask.

**Comment by sedrubal** [comment]
Usually there are `.desktop` files in `/usr/share/applications/`. If you change the `Icon=` value, the icon should change. :wink:

**Comment by nebutron** [comment]
That folder only has applications (actual icons to open the apps). I am showing all hidden, nothing like that there.

I am talking about the system tray or applet icons....

**Comment by nebutron** [comment]
Any other ideas? I have looked everywhere and have not been able to find them. This is on cinnamon desktop environment and Antergos.

**Comment by nebutron** [comment]
I found it finally. For my cinnamon desktop it was under

/usr/share/icons/hicolor/scalable/apps.

Thanks

**Comment by sedrubal** [comment]
I can recommend `rpm -ql $packagename` or `dpkg -l $packagename` :wink:
