### ISSUE TITLE
setting gamma via cli

### ISSUE THREAD

**Issue by Tadly** [jonls/redshift#458]
Out of boredom I started writing a kodi addon for redshift allowing it to be turned on/off bla bla...

Rather than relying on a config-file I wanted it to be configurable via kodi itself to than supply all the options via cli.

The question now.
I currently see no way of specifying gamma correction on a Day/Night basis like it is possible with e.g. brightness and the temperature.

Am I missing something?

**Comment by maandree** [comment]
You seem to be correct, but why not just generate the config file?

**Comment by maandree** [comment]
You seem to be correct, but why not just generate the config file?

**Comment by maandree** [comment]
Also, I advise against changing the gamma, I think it should just be used for colour correction.

**Comment by Tadly** [comment]
I thought about generating the config too (which might be what I end up doing).

It's not that I **want** to change gamma values, but more that I wanted a complete implementation of all features available (on my side that is) :)

**Comment by maandree** [comment]
I think it would be best to have it edit the config file (that is, both read it and write it), that why it is also possible to SSH into the machine and edit the config file.

**Comment by Tadly** [comment]
Looks like I got some re-writing to do than.
Either way thanks. I'll close this issue :)

**Comment by mehkera** [comment]
Hi tadly , have you succed to create a redshift plugin for kodi ?

**Comment by tadly** [comment]
Uhm.. kinda.
I did create one but there are some edge-cases where things where acting up IIRC.

I myself am not using it and though about nuking the repository a few times already.
I just kept forgetting ':D

https://github.com/linuxwhatelse/service.linuxwhatelse.redshift
