### ISSUE TITLE
Save current location

### ISSUE THREAD

**Issue by callitgeorge** [jonls/redshift#464]
It would be awesome if redshift would save the currently loaded location for use later when/if there is no internet connection.  I often use my laptop at Cafes that may not have internet access. So it would be nice if the app still remembered the last used location info to automatically adjust the color temperature.  Currently it does not.

**Comment by EvertonMelo** [comment]
Do you Cant it, only change Manually this file:

`~/.config/redshift.conf`

GEOCLUE passes parameters based on UTC, it does not monitor its location, it does not generate LOGS with it.

Have you ever thought about security if you adopted this suggestion?

**Comment by jonls** [comment]
@callitgeorge Thanks for the suggestion 👍  This seems to be similar to a suggestion that was already posted so I'm going to close this issue. Please join the discussion in the existing issue:  https://github.com/jonls/redshift/issues/36
