### ISSUE TITLE
Oracle Java GTK applications has green fonts

### ISSUE THREAD

**Issue by deric** [jonls/redshift#469]
With Gamma setting e.g. `0.9,0.9,0.9` Oracle Java 8 apps looks ugly - any text is getting green shadows. All other applications seem to be fine. Also I didn't reproduce such issue with OpenJDK 8.

![screenshot_20170609_105410](https://user-images.githubusercontent.com/138573/26968391-27db2d4c-4d02-11e7-8879-5a2da1320354.png)

**Comment by EvertonMelo** [comment]
Hi, 

Please describe the environment:
Redshift has limitations:

> Certain video drivers do not support adjustable gamma ramps. In some cases Redshift will fail with an error message, but other drivers silently ignore adjustments to the gamma ramp.

>Redshift has a brightness adjustment setting, but it does not work the way most people might expect. In fact it is a fake brightness adjustment obtained by manipulating the gamma ramps, which means that it does not reduce the backlight of the screen. Preferable only use it if your normal backlight adjustment is too coarse-grained.

**### fonte: http://jonls.dk/redshift/**

**Comment by jonls** [comment]
@deric It seems that Java has its own way of doing font anti-aliasing (cf. https://stackoverflow.com/questions/17510099/ugly-fonts-in-java-applications-on-ubuntu) and probably the implementation in OpenJDK is different from the one on Oracle Java. This could have some interaction with the gamma settings depending on how the anti-aliasing is done. It seems like this is not particularly related to anything Redshift is doing, so I'm going to close this issue for now. Please reopen if you find that this is not the case.
