### ISSUE TITLE
(CLI) Configure the strength/intensity

### ISSUE THREAD

**Issue by Ploppz** [jonls/redshift#470]
Maybe I haven't looked well enough, but I am missing a way to specify the strength of the color transformation. With a given temperature, and brightness I don't care so much about - I often want to have a stronger effect, e.g. more red-ish colors.

**Comment by jonls** [comment]
A lower temperature is what you're looking for then.

**Comment by Ploppz** [comment]
Yes.. you are right. Thanks for pointing that out.

I'm having a little problem now. I typed `redshift -O 2000` to test, but can't find the process in order to kill it.
