### ISSUE TITLE
Translation errors in Spanish

### ISSUE THREAD

**Issue by mguzmann** [jonls/redshift#471]
In:

"This program provides a status icon that allows the user to control Redshift."
"Este programa provee de un ícono de estado, que permite al usuario controlar "
"Redshift."

it should be "provee un ícono de estado"

In:

"Suspend for"
"Suspender para"

it should be "Suspender por".

In: 

msgid "2 hours"
msgstr "2  horas"

there is an extra blank space

**Comment by jonls** [comment]
Thanks. I have applied you suggestions at https://translations.launchpad.net/redshift/trunk/+pots/redshift/es/+translate
