### ISSUE TITLE
Paragraph about temperature in help can be better formatted

### ISSUE THREAD

**Issue by faheel** [jonls/redshift#474]
The paragraph about the temperature, near the bottom of the help text (using `redshift -h`):
> The neutral temperature is 6500K. Using this value will not
change the color temperature of the display. Setting the
color temperature to a value higher than this results in
more blue light, and setting a lower value will result in
more red light.

has lines with linebreaks at some fixed width (60, I guess) which makes it unresponsive to the terminal's width. This doesn't look so good :confused:. Here's a screenshot on a terminal with a width of 80 chars:
![image](https://user-images.githubusercontent.com/11466676/27814301-26fce4ec-6099-11e7-81b1-b41cc3402f7b.png)

I figured that to solve this the `\n` at the end of each line [here](https://github.com/jonls/redshift/blob/master/src/redshift.c#L464-L468) would need to be replaced with a space. The translation files and the man-page would also need to be updated with the same.

If it's alright, can I send a PR to fix this issue?

**Comment by EvertonMelo** [comment]
Hi, 

you look the Original file?

`https://github.com/jonls/redshift/blob/master/redshift.1`

or combine the help and MORE_Command ?

# sample:
`redshift -h | more `

for the change Settings local, change this file:
`~/.config/redshift.conf`

more information:
http://jonls.dk/redshift/

**Comment by jonls** [comment]
The convention for help output from command line tools is to cap it at 80 characters. I would be ok with reformatting this paragraph to a width of 80. I would prefer not to have lines longer than 80 as that would go against conventions.

**Comment by faheel** [comment]
Yep, reformatting the paragraph to a width of 80 rather than the current 60-something would make it better.

**Comment by jonls** [comment]
@faheel Yes!
