### ISSUE TITLE
hello,Can you tell me which part of the code is directly controlling the display color temperature? 

### ISSUE THREAD

**Issue by wanlon** [jonls/redshift#475]

**Comment by EvertonMelo** [comment]
Hi,

Screen color setting, by what means?

With DRM? No DRM? With Geoclue? Without Geoclue?

Be more specific in your questions please.

The Files the adjust are:

https://github.com/jonls/redshift/tree/master/src

**Comment by jonls** [comment]
The gamma ramps for a specific color temperature is calculated in https://github.com/jonls/redshift/blob/master/src/colorramp.c. The gamma ramps are applied using one of many adjustment methods, for example using randr: https://github.com/jonls/redshift/blob/master/src/gamma-randr.c.
