### ISSUE TITLE
redshift NOT startup on IPv6 

### ISSUE THREAD

**Issue by EvertonMelo** [jonls/redshift#478]
Hi, 

redshift not running in ipv6 mode. 
alternate for ipv6, running normal.

but is a question: Geoclue and Redshift running in hosts and network IPv6 ???

I try read documentation:
https://www.freedesktop.org/wiki/Software/GeoClue/ 
but I did not find about it. 

Is it possible to implement this natively?

**Comment by jonls** [comment]
Whether IPv6 or IPv4 is used is complete outside the scope of Redshift. Please post this question to the GeoClue developers.
