### ISSUE TITLE
Broken Windows x64 build from "Latest builds from master branch"

### ISSUE THREAD

**Issue by xesarni** [jonls/redshift#485]
Nice to see that Redshift for Windows is back, but the latest build doesn't work at all. redshift.exe is only 37,0 KB. 

BTW, could you also provide x32 versions?

**Comment by jonls** [comment]
@manuc66 Did you run into this issue as well?

**Comment by jonls** [comment]
@xesarni What is the issue or error message? What did you try and what happened?

**Comment by jonls** [comment]
It seems that the executable that is being packaged is in fact a libtool "shortcut" that is only valid in the build environment. @xesarni Can you try this statically built version instead? https://ci.appveyor.com/api/buildjobs/ufdrn40cb0vjh1i3/artifacts/redshift.zip

**Comment by xesarni** [comment]
The original one shows nothing at all. The second one throws "Missing libintl-8.dll" error.

**Comment by jonls** [comment]
@xesarni Ok, so it appears that libintl is still not statically linked. Can you try this version with NLS disabled? https://ci.appveyor.com/api/buildjobs/k086impkkevwkt4a/artifacts/redshift.zip

**Comment by xesarni** [comment]
It's working now.

**Comment by jonls** [comment]
@xesarni Thanks! I'll merge the fix soon.

**Comment by manuc66** [comment]
> @manuc66 Did you run into this issue as well?
Yes I did that's the reason why I did not submited a PR. Thanks for having fix the issue !
