### ISSUE TITLE
More frequent release cycle?

### ISSUE THREAD

**Issue by baimafeima** [jonls/redshift#505]
Could you make a new GitHub release so that distribution maintainers can bring updates quicker to their users? The last release was made on Jan 3, 2016 with now 72 commits to master since this release.

**Comment by Ktar5** [comment]
Would be nice

**Comment by jonls** [comment]
Thanks for the suggestion. Unfortunately, new releases take a lot of time to prepare and since I only have varying and limited time to dedicate, I cannot guarantee a specific release schedule. A new release will happen eventually.
