### ISSUE TITLE
Sample config file crashes redshift

### ISSUE THREAD

**Issue by CottonEaster** [jonls/redshift#509]
My version of redshift included a sample config file. I pasted into where it was meant to go - after I worked out where that was . . - in order manually to specify my location. The result: a crash with a fairly cryptic error message. The reason? The default config file includes a reference to a second screen.

Lots of people will do what I did. You might want to spare them the pain.

**Comment by jonls** [comment]
Thanks for the suggestion. I too noticed this earlier today and was about to make the change as you suggested 👍
