### ISSUE TITLE
redshift -m METHOD:<any> yields: Ukendt justeringsmetode: `METHOD'.

### ISSUE THREAD

**Issue by epodata** [jonls/redshift#515]
man redshift is in English. redshift command "speaks" Danish. Ex:

redshift -m list
Tilgængelige justeringsmetoder:
  drm
  randr
  vidmode
  dummy

Specificer indstillinger separeret med kolon: `-m METODE:VALG'.
Prøv `-m METODE:help' for at få hjælp.

Neither redshift -m METODE:help nor redshift -m METHOD:help yields any help.

**Comment by jonls** [comment]
@epodata Are you literally running `redshift -m METODE:help` or are you trying to get help on one of the methods listed, e.g. `redshift -m randr:help` or `redshift -m vidmode:help`?

**Comment by epodata** [comment]
On 2017-09-14 at 18:42:41 Jon Lund Steffensen wrote:

> @epodata Are you literally running `redshift -m METODE:help` or are
> you trying to get help on one of the methods listed, e.g. `redshift
> -m randr:help` or `redshift -m vidmode:help`?
> 

Hm, it looks like I've misunderstood the command description. Sorry
for the noise. 

--
Venlig hilsen,
Erik P. Olsen

**Comment by jonls** [comment]
No problem 😄
