### ISSUE TITLE
Unable to start GeoClue client: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Geolocation disabled for UID 0.

### ISSUE THREAD

**Issue by a1exus** [jonls/redshift#522]
while trying to run _redshift_ on my linux, I'm getting following error, although I didn't had any issues running it for the first time though)

```
root@suey:~# redshift -V
redshift 1.11
root@suey:~/Downloads# redshift 
Trying location provider `geoclue2'...
Using provider `geoclue2'.
Using method `randr'.
^Croot@suey:~#
root@suey:~# redshift 
Trying location provider `geoclue2'...
Using provider `geoclue2'.
Unable to start GeoClue client: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Geolocation disabled for UID 0.
Unable to connect to GeoClue.
Unable to get location from provider.
root@suey:~# 
```

Please advise.

**Comment by jonls** [comment]
https://github.com/jonls/redshift#faq

**Comment by RafaelCz** [comment]
> Unable to start GeoClue client: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: **Geolocation disabled for UID 0**.

> root@suey:~#

that hint should be enough

**Comment by jonls** [comment]
@a1exus As was pointed out above, it seems that you are running Redshift as root. It appears that GeoClue will not provide location updates to the root user. In any case, it is not recommended to run Redshift as root. Please try to run as a normal user. If the AccessDenied error persists, please see the FAQ: https://github.com/jonls/redshift#faq

**Comment by a1exus** [comment]
@jonls 

I use live system and for better or worse root is the way to go and since I login as root, redshift runs under root as well, let's put message aside for a moment, when I ran redshift for the very first time, redshift ran without any messages such as this *AND* it was working fine, when I tried second time I couldn't get it to work and I got that message now...

**Comment by jonls** [comment]
@a1exus That's all fine, you can of course run Redshift in any way you want but if you do, you're on your own when any issues occur. Did you take a look at the FAQ, specifically the entry about GeoClue access denied?

**Comment by mrpwner** [comment]
@jonls Thank you. It worked for me. All I had to do is to reactivate the location services under system>privacy  as stated in the FAQ
