### ISSUE TITLE
redshift on ubuntu 17.10

### ISSUE THREAD

**Issue by vertexLord** [jonls/redshift#543]
Switched to ubuntu 17.10 and installed `redshift-gtk` via

`apt-get install redshift-gtk`

After launch it just doesn't do anything. Am I being stupid here or is this
a gnome thing?

**Comment by jonls** [comment]
This is probably because Ubuntu 17.10 defaults to Wayland which Redshift cannot support at the moment. If you're using GNOME you can try the built-in Night Light feature instead of using Redshift.

**Comment by select** [comment]
Hey thanks, but I really wish I had redshift back. The gamma and brighness settings made quite a difference :D

**Comment by stefanos82** [comment]
I had the same problem on my system (Debian). The issue is with `geoclue-2.0` package and I resolved my issue by manually creating a `redshift.conf` file under `$HOME/.config` directory with my own settings.

Now I can use it without depending on `geoclue-2.0`:

```text
; Global settings for redshift
[redshift]
; Set the day and night screen temperatures
temp-day=5700
temp-night=3500

; Enable/Disable a smooth transition between day and night
; 0 will cause a direct change from day to night screen temperature.
; 1 will gradually increase or decrease the screen temperature.
transition=1

; Set the screen brightness. Default is 1.0.
;brightness=0.9
; It is also possible to use different settings for day and night
; since version 1.8.
;brightness-day=0.7
;brightness-night=0.4
; Set the screen gamma (for all colors, or each color channel
; individually)
gamma=0.8

;gamma=0.8:0.7:0.8
; This can also be set individually for day and night since
; version 1.10.
;gamma-day=0.8:0.7:0.8
;gamma-night=0.6

; Set the location-provider: 'geoclue', 'geoclue2', 'manual'
; type 'redshift -l list' to see possible values.
; The location provider settings are in a different section.
location-provider=manual

; Set the adjustment-method: 'randr', 'vidmode'
; type 'redshift -m list' to see all possible values.
; 'randr' is the preferred method, 'vidmode' is an older API.
; but works in some cases when 'randr' does not.
; The adjustment method settings are in a different section.
adjustment-method=randr

; Configuration of the location-provider:
; type 'redshift -l PROVIDER:help' to see the settings.
; ex: 'redshift -l manual:help'
; Keep in mind that longitudes west of Greenwich (e.g. the Americas)
; are negative numbers.
[manual]
lat=<your country's latitude>
lon=<your country's longitude>
; Find more about your country's / city's geolocation from http://www.geonames.org/
; Configuration of the adjustment-method
; type 'redshift -m METHOD:help' to see the settings.
; ex: 'redshift -m randr:help'
; In this example, randr is configured to adjust screen 1.
; Note that the numbering starts from 0, so this is actually the
; second screen. If this option is not specified, Redshift will try
; to adjust _all_ screens.
[randr]
screen=0
```

**Comment by Russell-Jones** [comment]
See also 
Settings > Devices > Displays > Night Light

**Comment by MaxValue** [comment]
I have the same problem. I couldn't even turn of the `geoclue-2.0` provider, because redshift just takes the built-in default values (meaning it **does not** create a config file at `~/.config/redshift.conf`), tries to start, fails and shows this error:

![screenshot from 2018-01-15 17-57-19](https://user-images.githubusercontent.com/1447159/34953954-d5e6ffd2-fa1e-11e7-93aa-a966b3988837.png)

Suggestion: Copy the default config file to the users dir if it does not exist, **before** even running. This way users can change the defaults if redshift should crash because of those. Also maybe use the config options from @stefanos82 specifically for wayland patients.

**Comment by ciskeboekelo** [comment]
Thank you @stefanos82 ! your config worked for me :-)
Might be good to mention that you've left the latitude and longitude up to the user to insert /edit it. I blindly copied your config and it took me a while before I realized that that was causing it not to run.

**Comment by stefanos82** [comment]
No worries mate. Oh I have mentioned that right below `[manual]`.

**Comment by stefanos82** [comment]
@ciskeboekelo Done.

**Comment by ciskeboekelo** [comment]
@stefanos82 Awesome.

**Comment by rubo77** [comment]
I used your script and now it starts. also the information page sais color temperature  should be now at 3500 but it doesn't work!

the color is not changing!

Do I have to restart the computer for it to work?

**Comment by ciskeboekelo** [comment]
When I made changes in the config file I did find that I needed to close
and restart redshift for the changes to take effect. I didn't need to
restart my computer.

Op di 8 mei 2018 om 23:46 schreef Ruben Barkow <notifications@github.com>:

**Comment by jonls** [comment]
@rubo77 This is expected, Wayland doesn't support Redshift: https://github.com/jonls/redshift/blob/master/README.md#faq. Both the Wayland issue and then geoclue issue should be documented in the FAQ now.
