### ISSUE TITLE
No way to configure "scheme.use_time"

### ISSUE THREAD

**Issue by valsoray17** [jonls/redshift#559]
There is an option of use_time in scheme object, but there is no way to set it to anything, but false.

This is slightly related to https://github.com/jonls/redshift/issues/525

**Comment by jonls** [comment]
https://github.com/jonls/redshift/blob/master/src/redshift.c#L980

It is set when `dawn-time` and `dusk-time` are specified in the configuration file (on the master branch, not yet in a released version of Redshift).
