### ISSUE TITLE
Make redshift always in night period

### ISSUE THREAD

**Issue by amosbird** [jonls/redshift#562]
Hi, is there a setting to make redshift always in night period? regards.

**Comment by jonls** [comment]
You can set the daytime color temperature to the same value as the nighttime color temperature. Would that work?

**Comment by amosbird** [comment]
Oh, what would the config look like :)

**Comment by jonls** [comment]
Set `temp-day` and `temp-night` to the same value: https://github.com/jonls/redshift/blob/master/redshift.conf.sample#L5

**Comment by amosbird** [comment]
thanks!
