### ISSUE TITLE
"Brightness values must be between 0.1 and 1.0."

### ISSUE THREAD

**Issue by daf0x** [jonls/redshift#565]
When starting redshift, it now gives the following error:
``"Brightness values must be between 0.1 and 1.0."``
I have checked the configuration file, and everything seemed OK. I replaced my configuration file with the example, but the problem remained. The is on Gentoo, with the following software versions:

```
$ eix -I redshift
[I] x11-misc/redshift
    Available versions:  1.11-r1 {appindicator geoclue gtk nls PYTHON_TARGETS="python3_4 python3_5 python3_6"}
     Installed versions:  1.11-r1(01:08:33 PM 12/03/2017)(gtk nls -appindicator -geoclue PYTHON_TARGETS="python3_4 -python3_5 -python3_6")
     Homepage:            http://jonls.dk/redshift/
     Description:         A screen color temperature adjusting software
```

```
$ gcc --version:
gcc (Gentoo 7.2.0 p1.1) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
 warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I think the problem is in these lines:
- https://github.com/jonls/redshift/blob/b210813c7ffdd0eae75eb60c7bbbb62b6b109ebe/src/options.c#L307
- https://github.com/jonls/redshift/blob/b210813c7ffdd0eae75eb60c7bbbb62b6b109ebe/src/options.c#L530

When this is compiled with `-ffast-math`, the comparison with `isnan()` is probably always going to fail. After recompiling without `-ffast-math` the problem goes away.

I see two solutions:
1. Since it is known that the valid range for `brightness` is [0.0..1.0], a negative value (e.g. -1.0) can be used as the sentinel rather than `NaN`.
2. Remove the test for `isnan()` before the assignment. All this does is prevent a later setting in the `.ini` file from overriding an earlier setting. However, this does not add any real value, since setting the same value twice doesn't make sense anyway (so whether the first or the last value in the `.ini` file is used doesn't really matter).

**Comment by jonls** [comment]
The solution is to not compile with `-ffast-math`.
