### ISSUE TITLE
Please make it possible to define the time of day when night starts, instead of relying on the sunset.

### ISSUE THREAD

**Issue by mortie** [jonls/redshift#570]
I live in Norway. Today, the sun set around 15:30, many many hours before I consider it to be "night", yet redshift activated night mode because it rightly detected that the sun had set.

For us far north, relying on the time of the sunset and sunrise doesn't work well for detecting whether it's night or day. Just a bit farther north from where I am at the moment, there's days or weeks where the sun doesn't rise at all during the winter, and days or weeks where the sun doesn't set at all during the summer. It would be really nice to be able to just define night to start at, say, 21:00, and day to start at 07:00.

**Comment by vierlex** [comment]
Hi mortie,

With the latest build from the master branch, you can already do exactly that.
They links are a bit hidden though: https://github.com/jonls/redshift
scroll down all the way.

Open up the config and you will see settings for that. Havent tried them myself though.

**Comment by mortie** [comment]
I finally got around installing the version from git, and the dawn-time and dusk-time settings seem exactly like what I wanted. Thanks :D
