### ISSUE TITLE
Redshift doesn't work when using sample config

### ISSUE THREAD

**Issue by gamalan** [jonls/redshift#571]
Unable running redshift 1.11 using [sample config](https://github.com/jonls/redshift/blob/master/redshift.conf.sample) with error message.
`
Malformed assignment in config file.
Unable to load config file.
`

But, when running without config `redshift -v`. It is working, with output.

Trying location provider 'geoclue2'...
Using provider 'geoclue2'.
Location: 6.99 S, 110.42 E
Temperatures: 5500K at day, 3500K at night
Solar elevations: day above 3.0, night below -6.0
Brightness: 1.00:1.00
Gamma (Daytime): 1.000, 1.000, 1.000
Gamma (Night): 1.000, 1.000, 1.000
Using method 'randr'.
Status: Enabled
Period: Daytime
Color temperature: 6490K
Brightness: 1.00

Tested in Archlinux, using Xfce Desktop

**Comment by NunoAlexandre** [comment]
What command are you using to run it?

**Comment by Alix35301** [comment]
@gamalan have you found a way to resolve the issue?

**Comment by jonls** [comment]
@gamalan Use the config for 1.11 when you run Redshift 1.11: https://github.com/jonls/redshift/blob/v1.11/redshift.conf.sample

The config in the master branch is never guaranteed to work with older version because new options may have been added in the development branch.

**Comment by huulien** [comment]
it works!! :)
