### ISSUE TITLE
Multiple crtc values are not parsed

### ISSUE THREAD

**Issue by C-Higgins** [jonls/redshift#581]
Fedora 27, Redshift 1.11, AMD drivers

I have in config file:
```
[randr]
screen=0
crtc=0,1
```

But only crtc 0 is affected. If I change the orders around, only the first number is ever affected. I can individually affect any monitor this way, but not more than one at a time. If I do not set this option, all monitors are working. There is no error message; config file is accepted and used, just this comma separated list of values is not parsed past the first.

I have 6 available crtcs and am using 4, all 4 are on screen 0.

**Comment by jonls** [comment]
This was added in Redshift 1.12: https://github.com/jonls/redshift/releases/tag/v1.12
