### ISSUE TITLE
Alternative trigger: screen brightness

### ISSUE THREAD

**Issue by eMPee584** [jonls/redshift#583]
I found reducing color temperature on my electronic screens as well as my room lighting **shortly** before going to bed to be a really effective way to induce sleepiness. Hence, I love the basic idea of this program.

However, even though the location/sunset based trigger `redshift` uses _seems_ clever, at least to petty me, it has proven not so useful in real life™. F.e. during winter, more often than not one will stay up several hours after sunset, or needs to get started way before sunrise. In these cases, redshift is rather annoying than helpful, because it has to be overridden _every_ day, which is not very convenient.

What actually would seem more useful is screen temperature scaling with brightness — because if my screen is still bright, chances are, I want to do something which needs my full wakefulness. If I turn it down low however, chances are, ambient lights are down as well and I'm about to go to bed.

Just realizing this is mostly useful for notebooks, which have hardware keys for screen brightness. But that's probably majority of home computers these days.

**Comment by jonls** [comment]
That's an interesting idea but I'm not sure if it works universally. I have the brightness pretty much set to the same setting all day. Feel free to open a PR if you end up implementing some of this.
