### ISSUE TITLE
Redshift toggle to turn ON in Fedora 27 not working

### ISSUE THREAD

**Issue by BlackWolf95** [jonls/redshift#584]
Hello everybody,
I tried to use Redshift but somehow the toggle to turn it on doesn't work. I read some possible reasons, one of which suggests this:

[http://jonls.dk/redshift/]
In the Known Bugs and Issues section, it says 

> this:
Ins some cases Redshift will fail with an error message, but other drivers silently ignore adjustments to the gamma ramp.
Is this my case?? Please help.

**Comment by jonls** [comment]
You are likely running in Wayland which is not supported: https://github.com/jonls/redshift#faq

**Comment by etem** [comment]
If you're talking about Redshift Gnome shell extension, It's also not working under X server: 

> ➜  ~ loginctl show-session 2 -p Type
> Type=x11
> 

Redshift-gtk works fine but no icon appears under Gnome taskbar. So it's not possible to adjust settings from GUI.

**Comment by jonls** [comment]
@etem Redshift Gnome shell extension appears to be a different project. I have no knowledge of how that works so you should report an issue directly to that project. If you're using Gnome you can use the built-in night light feature instead of Redshift.
