### ISSUE TITLE
USR2 signal to know if active

### ISSUE THREAD

**Issue by schtibe** [jonls/redshift#585]
I often turn redshift off with the USR1 signal (`killall -USR1 redshift`) when doing stuff that requires natural colors, like photography stuff. I'd like to have some script in my status bar to toggle it with a simple click.

In order to know whether redshift is on or not for the script, it would be nice to have a way of asking the redshift process. I'm thinking of maybe using the USR2 signal that outputs some status would be nice?

**Edit**
I just realized that using USR2 would be useless because we can't send the state to the signal caller.

**Comment by jonls** [comment]
Yeah USR2 would probably not work. I think, with all the different functionality that people want to add, the most sensible approach is to build a complete dbus service. There is already some work done towards this in #54.
