### ISSUE TITLE
Redshift causing screen flicker after linux kernel update to 4.15

### ISSUE THREAD

**Issue by dekay** [jonls/redshift#588]
Redshift is causing screen flicker ever since I updated my Linux kernel to 4.15.  I have an AMD 560 and am running KDE on Arch Linux.  [Others are seeing the same problem](https://www.reddit.com/r/archlinux/comments/7vxnam/redshift_flickering_display_after_415_kernel/).  The poster described it as follows:

> I see random flickering between night and day colour temperatures when night should be constant. This happens intermittently with sometimes long periods of time between flickers. I'm using the open source drivers for AMD, with a RX-480 card.

[Manjaro users see it too](https://forum.manjaro.org/t/redshift-color-transition-flickers/39428/22).

Redshift is version 1.11-5 and kernel is 4.15.2-2.  I have amdgpu.dc=1, enabling the AMD kernel code that was merging in in 4.15.

I get flashing every few minutes with these settings in the Plasma applet:
- smooth transitions not selected
- auto mode

resulting in this (obfuscating my lat / long)
```
[dk@ryzen ~]$ ps -ef |grep shift
dk        1607   778  0 20:13 ?        00:00:00 /usr/bin/redshift -l xx.xxxx -yy.yyyy -t 6500 4000 -b 1 1 -g 1 1 1 -r
dk        1619  1392  0 20:14 pts/0    00:00:00 grep shift
```
Redshift worked flawlessly before this update.

**Comment by jonls** [comment]
Probably the same issue as other people have reported in #221

**Comment by dekay** [comment]
I have recently upgraded to Arch kernel 4.15.6-1 and it seems like the flickering has gone away.  I'll monitor this for a while longer and close the issue if the problem has indeed gone away.

**Comment by etam** [comment]
I have openSUSE Tumbleweed with kernel 4.15.7-1 with amdgpu.dc=1 and flickering is still present.

**Comment by ashleybone** [comment]
Arch kernel 4.15.17-1 here, flickering still present with amdgpu.dc=1.

**Comment by dekay** [comment]
@etam @ashleybone Are you running KDE or something else.  Maybe the desktop environment comes into play?

**Comment by etam** [comment]
I use KDE session with plasma desktop disabled, window manager is i3wm and compton.

As discussed in #221 it's not only KDE.

**Comment by ashleybone** [comment]
I run KDE, more or less vanilla.  Seen reports of this across many DE/WMs, though.

**Comment by dekay** [comment]
It looks like a spoke a bit too soon.  I still get the odd flicker, but it is much less frequent than before.  Maybe once an hour or so, on average.  Used to be I'd get flicker every couple minutes.

**Comment by Kommynct** [comment]
i'm also running 4.15.12 on arch, it's not gone for me.

**Comment by etam** [comment]
After upgrading to 4.16.0 it got worse.

**Comment by pager72** [comment]
Much worse with 4.16.0 on gentoo/kde-5

**Comment by Quoor8ee** [comment]
Fluxbox on Archlinux (anything since about 4.15.12) here.
Flickering: yes @ RX 550; no on Raven Ridge (2500U) (both amdgpu).
I noticed that prior to 4.15 (and on other GPUs), the mouse cursor is/was not tinted by redshift at all (method "randr"), but now it is has the same color as the screen (RX 550), or appears even to be red-shifted twice (RR). Maybe this helps in localizing the reasons.

Adding ```amdgpu.dc=0``` to the kernel commandline did stop the flickering.

**Comment by dekay** [comment]
Upgrading to 4.16 from 4.15 made it significantly worse for me as well.

**Comment by Xerus2000** [comment]
just upgraded my Linux Mint Cinnamon to Kernel 16.2 and experienced flickering too

**Comment by Quoor8ee** [comment]
Flickering is gone for me on Polaris with ```amdgpu.dc=1``` on Linux 4.17-rc1

**Comment by jpotier** [comment]
Happening on 4.16.3 still.

**Comment by pager72** [comment]
I have standard laptop display with ordinary refresh rate.

**Comment by Kommynct** [comment]
Well that throws my theory out.

**Comment by jpotier** [comment]
Can confirm that the problem is gone in linux 4.17.1_ rc1

**Comment by jonls** [comment]
Thanks for reporting this issue. This seems to be related to graphics drivers and not directly related to Redshift. While it's nice to have this information available for the users of Redshift, ultimately it's not the right place to discuss kernel/graphics driver issues since it's not something Redshift can do anything about. Please report this issue to your distribution or to the graphics driver maintainers.

**Comment by dekay** [comment]
I opened this issue and just wanted to let you know that the problem indeed went away in kernel 4.17.  Really happy that I can now resume using redshift.  It's wonderful!  That you for your work!

**Comment by Hasilt** [comment]
I'm on kernel 4.19.4 and experiences flickering with xfce de
