### ISSUE TITLE
Disable Redshift on just one monitor

### ISSUE THREAD

**Issue by jeffersondarcy** [jonls/redshift#596]
I have bought an e-ink monitor and would like to have redshift enabled just on the other two normal monitors - how would it be possible to configure?

**Comment by jeffersondarcy** [comment]
okay, I figured out a solution for me:
run
`redshift  -m randr:crtc=2 -O 9000` for the redshift-disabled third monitor (sometimes I use 8000)
and run
```
redshift  -m randr:crtc=0 -O 3000
redshift  -m randr:crtc=1 -O 3000
```
It's my color temp for both other monitors

**Comment by jonls** [comment]
👍
