### ISSUE TITLE
Sequential redshift -O calls accumulate the filtering effect

### ISSUE THREAD

**Issue by vstepaniuk** [jonls/redshift#598]
Ubuntu 17.10 x64, Redshift 1.11+r380.12
Sequential `redshift -O` calls accumulate the filtering effect...

**Comment by vstepaniuk** [comment]
Or is it what `preserve=1` meant for?
You see, there is lack of information in the help pages
https://github.com/jonls/redshift/issues/597

**Comment by jonls** [comment]
Thanks for reporting this. When using `-O` the effect was indeed accumulated and this was fixed recently and should be fixed in the next release.
