### ISSUE TITLE
[redshift-gtk] Tooltip on tray icon does not show

### ISSUE THREAD

**Issue by frademacher** [jonls/redshift#602]
Hello everybody,

first and foremost, Redshift is a really nice piece of software that clearly improved my everyday life. Hence, I'm having it running all the time on each of my machines. Kudos to everybody involved in its development!

However, I recognized a minor flaw regarding the tray icon of Redshift. When I run the program on Linux Mint 18.3 with Cinnamon 3.6.7 and Redshift 1.10, hovering over the icon does not have any effect. In contrast, for other DEs, a tooltip is shown stating the color temperature and period when hovering over the tray icon. I consider both behaviors somewhat inconsistent regarding user experience.

Therefore, I tried to investigate the issue, which seems related to `redshift-gtk`, and came to the conclusion that it's using (py)Gtk's `AppIndicator3` class to display the icon. If for some reason `AppIndicator3` is not available in the installed Python repository, `redshift-gtk` falls back to (py)Gtk's `StatusIcon`. However, apparently for Cinnamon 3.6.7, `StatusIcon` is capable of displaying tooltips. 

As in may daily work I partially rely on having the tooltip available, I implemented a solution that works fine for me on Cinnamon 3.6.7 for quite some time. After recently having found the time to polish it, I want to share it with the Redshift developing community and would be happy to receive some feedback on its applicability to upstream `redshift-gtk`. Maybe you can even consider its inclusion in the upstream version of Redshift, eventually? :-)

My solution relies on adding a new configuration section `[redshift-gtk]` and an option `use-appindicator-icon` for it. The default value of `use-appindicator-icon` is `1` (use `AppIndicator3` for tray icon if available). A value of `0` would in contrast deactivate the usage of `AppIndicator3`, even it is available. This is the value I use for myself to have the tooltip available on Cinnamon. Additionally, I extended the menu of `AppIndicator3`-based icons in that it now includes two entries, which display the information usually available in the tooltip.

You may find my proposed solution in my Redshift fork on branch [`appindicator-config-entry`](https://github.com/frademacher/redshift/tree/appindicator-config-entry). The chronologically first three commits ([`b68afdb`](https://github.com/frademacher/redshift/commit/b68afdb759cd4cf26370afa32e59c5f70d134d8f), [`0699455`](https://github.com/frademacher/redshift/commit/0699455a0bc9ea1564df0752e725fe376993afae), [`d56a877`](https://github.com/frademacher/redshift/commit/d56a8770abc31c2ca2866d88aad5e06421736f6a)) add a Python-based configuration parser to `redshift-gtk`, which aims to deal with configuration options for `redshift-gtk`. The fourth commit [`daa6ab1`](https://github.com/frademacher/redshift/commit/daa6ab13953cd3f43b8d82abfe5270f7f5ca8bd2) updates `redshift.conf.sample` to include the new section and option. The fifth commit [`05923f4`](https://github.com/frademacher/redshift/commit/05923f490c2bc4e2ce26ed531bb0d71e16a3d6e9) extends `AppIndicator3`-based tray icons with the otherwise missing information usually shown in a tooltip.

If a PR would be better for you to have a look on my changes to `redshift-gtk` please let me know.

**Comment by jonls** [comment]
Thanks, please open a separate PR for each change. I think some of the ideas would probably be easy to merge and some may require more discussion.
