### ISSUE TITLE
[ASK] RedShift can't detect Location after my computer restarted

### ISSUE THREAD

**Issue by vandpurnama** [jonls/redshift#603]
it cant detect my location after my pc restart or shutdown...

![image](https://user-images.githubusercontent.com/33601181/38812049-6a50a370-41b5-11e8-8c98-c5693e027280.png)

and i can't find redshift config...

**Comment by jonls** [comment]
Please provide more information. Is there an error message if you run `redshift` in the terminal? You can copy the sample configuration to `~/.config/redshift.conf`, Redshift won't create it automatically for you.

**Comment by vandpurnama** [comment]
Here redshift config ..
[redshift.conf.zip](https://github.com/jonls/redshift/files/1987846/redshift.conf.zip)

**Comment by jonls** [comment]
Please try running redshift in a terminal and provide any output that's relevant.

**Comment by pprw** [comment]
Could be the same issue than me. It seems there is a change in permissions for geoclue:

```
Unable to start GeoClue client: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: 'redshift' disallowed, no agent for UID 1000.
Unable to connect to GeoClue.
```

**Comment by jonls** [comment]
It might be related to geoclue but there's no way to know without more information from the OP. Closing.

**Comment by pprw** [comment]
I can provide information (or open a new issue)
