### ISSUE TITLE
Compiling on FreeBSD

### ISSUE THREAD

**Issue by schijtreiger** [jonls/redshift#605]
In case any of you dudes run FreeBSD 11/12:

Pull the repo with "git clone <whatever-version-is-master-right-now>.git"
follow with:
$ ./bootstrap
$ ./configure
(do your prefixes here, *if* you have any. I don't use any, so haven't tried, YMMV)
$ gmake   (note: you might need a '$ sudo gmake' here, depending on your account limitations )
$ sudo gmake install

Profit. Now get back to tinkering with other things. The current version of cmake I use, was not happy, hence reverted to archaic gmake.

**Comment by jonls** [comment]
Thanks. Cmake is not supposed to work on an automake project as far as I know, so this would be entirely expected.
