### ISSUE TITLE
Windows: Unknown adjustment method 'randr' 

### ISSUE THREAD

**Issue by skygate2012** [jonls/redshift#607]
I downloaded the compiled redshift.exe for windows from the releases, and put `redshift.conf` in `%localappdata%`. But when I run the program through command-line window it returned the error `Unknown adjustment method 'randr' `

**Comment by thejustsoul** [comment]
Try change `randr` to `wingdi`:
`adjustment-method=wingdi` in `redshift.conf`

**Comment by yaoghu** [comment]
can confirm this is a problem on my system as well.

![sun_may__6_16 24 30_ist_2018](https://user-images.githubusercontent.com/29171250/39672559-088c3830-514a-11e8-9360-d67b059b5d4c.jpg)

randr,drm,vidmode,dummy are the adjustment methods available.problem goes away with vidmode.drm/randr does not work.

**Comment by jonls** [comment]
As @thejustsoul said, use `wingdi` on Windows. This is the only adjustment method that works on Windows. @yaoghu On Linux, use `randr` or `vidmode` depending on what you graphics driver supports. (If you don't know what DRM is, the `drm` method is probably not useful to you).
