### ISSUE TITLE
DRM adjustment method prevents changing framebuffer console colors

### ISSUE THREAD

**Issue by remexre** [jonls/redshift#616]
redshift works in the framebuffer with the drm adjustment method. However, setting framebuffer console colors by writing to `/sys/module/vt/parameters/default_{red,grn,blu}` and running `reset` doesn't work while redshift is running. `systemctl stop --user redshift; printf '\e]R\ec'; systemctl start --user redshift` applies the change properly, though.

**Comment by maandree** [comment]
Duplicate of #441

**Comment by jonls** [comment]
Thanks for reporting, apparently this is a known limitation.
