### ISSUE TITLE
Manual timepoints for sunrise/sunset

### ISSUE THREAD

**Issue by mortenfyhn** [jonls/redshift#617]
If you live far north/south, the sun sets very late during summer. Based on location, Redshift may stay blue until late evening, which for me and probably others is not desirable as I need to sleep even though the sun doesn't. My current workaround is to set the manual location to somewhere in Libya (happens to be directly south from here), but maybe it would be an idea to allow defining the start/stop times for "night temperature" manually.

The same happens during winter, of course, when my monitor is fully red in early afternoon.

**Comment by jonls** [comment]
You can use the time-based adjustment in the new 1.12 release.

**Comment by mortenfyhn** [comment]
Great! Thanks.
