### ISSUE TITLE
Redshift adjustment not working correctly

### ISSUE THREAD

**Issue by oyhel** [jonls/redshift#620]
When trying to adjust the temperature and brightness, the resulting brightness and temp. will only decrease. Eg. if I do redshift -O 5000 and then the same command command again, the temperature will continue to lower. If I do redshift -O 6500 it does not revert back to "normal", but it does not reduce the temperature further. It looks to me like redshift neglects the currently set value. 

Using Redshift 1.12 (arch).

**Comment by michael-n0813** [comment]
Use "redshift -P -O xxxxK" new command "-P" resets gamma before setting new colour which was default behavior before update.
