### ISSUE TITLE
tray icon scrolling - color temperature only decreasing 

### ISSUE THREAD

**Issue by ebelsx7** [jonls/redshift#622]
hi there, haven't found a bug report on it so i hope i'm in the right place here

since version 1.12-1 the tray icon does not work right for me, when scrolling it just decreases the color temperature, no matter if i scroll up or down
having to click on it to disable it and reenable to start from the default value but not being able to increase it

the middle mouse button works (the icons shows the color change to blue, to being able to change the brightness) but scrolling just does again only decrease the color temperature

i'm using:
latest manjaro with KDE on the stable repository
plasma5-applets-redshift-control 1.0.18-1
redshift-1.12-1

downgrading redshift to version 1.11-5 fixes this problem for me

thanks for all the hard work on redshift, it's an awesome piece of software :)

**Comment by grmat** [comment]
The applet uses one-shot mode for handling mouse scrolling and redshift requires `-P` to be added to one-shot actions nowadays. Also see #513 

So your bug might be closed here, but I've already informed the developer of the plasma applet to fix the issue.

**Comment by ebelsx7** [comment]
good to know it's not on your end, thank you!

**Comment by christophschw** [comment]
Thanks for the hint. 
Adding `-P` in Line 70 of  `/usr/share/plasma/plasmoids/org.kde.redshiftControl/contents/ui/main.qml` fixes the issue for me :+1:
