### ISSUE TITLE
Enable Redshift on specific displays

### ISSUE THREAD

**Issue by ThePreviousOne** [jonls/redshift#625]
I have a single screen made up of 3 displays. One is a pen tablet so I would rather not have redshift on it as is where I draw, but my other screens are too bright at night so I would prefer to keep redshift enabled.

**Comment by jonls** [comment]
The randr adjustment method has some options for setting which screen/display to affect (I'm assuming this is Linux since you didn't specify). Did you try those?

**Comment by ThePreviousOne** [comment]
Oops, sorry, yes its GNU/Linux. How would I do that I don't see it in the manpages. Also I meant monitors not displays.

**Comment by jonls** [comment]
Run `redshift -m randr:help` and try the options listed there.

**Comment by ThePreviousOne** [comment]
Is there a deamon mode? if I run `redshift  -c ~/.config/redshift.conf -m randr:crtc=0` in the terminal it doesn't close and I am forced to leave the terminal open, `redshift -m randr:crtc=0 -O 3000` is fine though
