### ISSUE TITLE
Getting error "Invalid dawn/dusk time configuration!"

### ISSUE THREAD

**Issue by infokiller** [jonls/redshift#627]
I'm trying to use the new time parameters by having this snippet in my config:
```
dawn-time=08:00-10:00
dusk-time=01:00-03:00
```

That is, I want redshift to do the transition from night to day over 08:00-10:00, and the transition from day to night over 01:00-03:00 (I usually go to sleep and wake up late and I want redshift to honor that).

However, I get an error: "Invalid dawn/dusk time configuration!".

**Comment by jonls** [comment]
This is a known limitation at the moment and I think also documented in the man page. If I remember correctly the calculations are somewhat simpler if we assume that the dusk time is always before midnight (this is a trade-off between a simpler implementation and maintenance for a limitation that will probably not be a hindrance to most people). That being said, I think if someone volunteers to implement this I'd be open to merging it.

**Comment by barrowsys** [comment]
i might (read: probably wont) get around to fixing this but in the meantime if anyone comes across this issue needing a workaround: swap dawn-time and dusk-time (so dawn < dusk) and then swap temp-day and temp-night (so temp-day is your night temperature and temp-night is your day temperature).

its semantically hacky, and doesn't let you transition across the 00:00 boundary,, but it works.
