### ISSUE TITLE
Redshift not working with .conf file

### ISSUE THREAD

**Issue by Alix35301** [jonls/redshift#628]
**here is the ouput..**

Solar elevations: day above 3.0, night below -6.0
Temperatures: 5800K at day, 2000K at night
Brightness: 1.00:1.00
Gamma (Daytime): 0.900, 0.900, 0.900
Gamma (Night): 0.900, 0.900, 0.900
Waiting for initial location to become available...
Location: 4.00 N, 73.00 E
Color temperature: 6500K
Brightness: 1.00
Status: Enabled
Period: Night

but nothing happens.

**Comment by Alix35301** [comment]
command i ran = redshift -v

**Comment by Futureknows** [comment]
Same issue, I cut/paste/saved the redshift.config file and only change the night temperature to 2000. It still defaults to 3500k.

redshift -v
Trying location provider `geoclue2'...
Using provider `geoclue2'.
Location: 36.17 N, 115.14 W
Temperatures: 5500K at day, 3500K at night
Solar elevations: day above 3.0, night below -6.0
Brightness: 1.00:1.00
Gamma (Daytime): 1.000, 1.000, 1.000
Gamma (Night): 1.000, 1.000, 1.000
Using method `randr'.
Status: Enabled
Period: Night
Color temperature: 6470K
Brightness: 1.00

/.config/redshift.conf
Global settings for redshift
[redshift]
; Set the day and night screen temperatures
temp-day=5700
temp-night=2000

**Comment by jonls** [comment]
@Alix35301 Are you positive that your graphics driver/desktop environment supports gamma adjustments? Have you checked everything related to this in the FAQ? https://github.com/jonls/redshift#faq 

@Futureknows this looks like a different issue. Please open a new issue report.

**Comment by Futureknows** [comment]
Thanks I fixed it I think by specifying` -c /.config/redshift.conf` on the launcher works like a charm.

**Comment by jonls** [comment]
@Futureknows well, there's your problem right there, if the config file is in `/.config/redshift.conf`. You should put it in `~/.config/redshift.conf` or `~/.config/redshift/redshift.conf` instead if you want it to be found automatically.

**Comment by Alix35301** [comment]
@jonls yeah. It was due to the desktop environment. I used it on gnome. Switched to plasma and it worked. Thanks though 😁
