### ISSUE TITLE
100% colors not dimmed with amdgpu

### ISSUE THREAD

**Issue by blaueente** [jonls/redshift#630]
I have installed amdgpu 18.20 (opensource variant)  on ubuntu 18.04, 
according to https://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-for-Linux-Release-Notes.aspx
using amdgpu-install -y

redshift seems to work fine in general, except that 100% white color  (and probably any color with one 100% component) is not dimmed. See attached photo.
Note that even the antialiasing pixels around text is dimmed.
![redshift](https://user-images.githubusercontent.com/10434139/41511615-d45984b2-727a-11e8-9659-b295f4fca5d3.jpg)

**Comment by LukeMoll** [comment]
Same issue on Ubuntu 16.04. Looking at pages on `redshift -O 1000` seems to confirm your theory about 100% components

**Comment by gislikarl** [comment]
I have the same problem, any solutions?

**Comment by jonls** [comment]
This seems like a driver issue so please report this to the amdgpu developers. There's nothing redshift can do about this.
