### ISSUE TITLE
Incomplete man page [configuration file]

### ISSUE THREAD

**Issue by VirtualTorus** [jonls/redshift#633]
Hi,

Are there are a couple of items missing from the CONFIGURATION FILE section of the man page, such as `brightness` and `transition`, and perhaps others?

Are these deprecated options?

If not, I think they should be added.

**Comment by jonls** [comment]
`brightness` is found here: https://github.com/jonls/redshift/blob/01139a15bfd9c2882871f26d915495e14dd2ba7a/redshift.1#L111

`transition` still works but the name is deprecated. The new name in 1.12 is `fade` and is documented in the man page too.

Please let me know if other options are missing or even better: create a PR to fix them.
