### ISSUE TITLE
Custom fade duration

### ISSUE THREAD

**Issue by IiroP** [jonls/redshift#640]
**Feature idea**: Option to set fade duration in config file. Currently you can just toggle fade on and off using `fade=1` and `fade=0`

**Comment by stpeters00** [comment]
Note that the `fade` option only affects how redshift adjusts the color temperature when redshift starts up or stops.  If you use the `dawn-time` and `dusk-time` config options, you get to specify the **transition duration** - e.g. `dawn-time=07:00-08:00` for a morning transition beginning at 07:00 and ending at 08:00.

**Comment by IiroP** [comment]
Oh, thanks for the info. The sample configuration wasn't clear about this, but that was exactly what I was looking for.

**Comment by resuser** [comment]
I'm also looking for the option originally requested.  Specifically, a longer transition time, but still tied to location.  

While manual dawn and dusk duration is useful, they need to be adjusted throughout the year.  The location function is very useful, but it assumes the user has a direct view of the horizon on a clear day.  Setting the duration of the transition would allow the user to match the screen transition to their individual sunlight exposure.
