### ISSUE TITLE
Redshift-gtk fails when launched automatically during Gnome shell startup, but works if launched manually

### ISSUE THREAD

**Issue by rastersoft** [jonls/redshift#657]
I'm using redshift in a Debian Sid system with Gnome Shell, but redshift-gtk fails when I try to launch it automatically on startup: I receive an access denied error.

If I launch it manually it works fine.

I added a time.sleep(5) in redshift-gtk.in and now it works sometimes.

I suspect there is a delay during login in Gnome shell before the location service is available, and those 5 seconds are the limit to make it work.

**Comment by jonls** [comment]
Do you see the same error messages as in this issue: https://github.com/jonls/redshift/issues/645 ?

**Comment by rastersoft** [comment]
Yes, looks the same. Sorry, closing this.

**Comment by rastersoft** [comment]
Sorry. Fat fingers.
