### ISSUE TITLE
'redshift -O' stacks gamma adjustments each run

### ISSUE THREAD

**Issue by cyphar** [jonls/redshift#659]
**Describe the bug**
When using `redshift -O`, I noticed that subsequent attempts to change the colour temperature don't work as expected. They appear to stack on top of each other -- leading me to believe that the colour temperature adjustment is done based on the pre-existing gamma value rather than basing it on `1:1:1`.

This means that if you wish to manually adjust your temperature, you need to reset the gamma with `xrandr --output $OUTPUT --gamma 1:1:1` each time before you run `redshift -O`. This is somewhat related #477, in that it means resetting the colour temperature requires manual involvement, but I think the solution doesn't require having a long-running process -- you just have to add a knob that allows the gamma calculation to be done from `1:1:1` rather than the current gamma setting.

- [x] [I have checked the FAQ](https://github.com/jonls/redshift/blob/master/README.md#faq) and my issue is not mention there.

**To Reproduce**
1. Call `redshift -O 1500K -b 1:1`.
2. Call `redshift -O 6500K -b 1:1`.
3. Note that the screen's colour temperature is unchanged.

**Expected behavior**
The colour temperature should switch back to 6500K rather than staying at 1500K.

**Software versions (please complete the following information):**
 - OS: Linux
 - Redshift version: 1.12
 - Distribution: openSUSE Tumbleweed
 - Redshift installed from: Distribution repositories (zypper).

**Comment by sambiohazard** [comment]
I believe that same issue is present in latest (v1.12) windows build. When i start the program and then quit (Ctrl+C) it, then it wont change the temprature settings back to normal. Also if you restart the program again then it starts makes the screen temp even "redder" i.e. taking current redshifted settings and redshifting it further. I guess this is same issue as described above.
P.S.: i am not a programmer so sorry for lack of proper terminology.

**Comment by jonls** [comment]
Thanks for the issue report. This is intended behavior in 1.12 as the `preserve` option has been enabled by default (because it makes it easier to apply Redshift on top of existing gamma corrections).  If you use the one-shot modes, you can either reset the gamma ramps with (`redshift -x`) or you can run with the new `-P` option, e.g.: `redshift -O 3000 -P`.
