### ISSUE TITLE
Redshift failed to run but still works?

### ISSUE THREAD

**Issue by Dzyn641** [jonls/redshift#662]
Everytime I login to i3 or KDE I get a popup that says "Failed to run RedshiftInvalid MIT-MAGIC-COOKIE-1 key RANDR Query Verion' returned error -1 initialization of randr failed." After I close this popup redshift then works, how can I stop this?

**Comment by Dzyn641** [comment]
Fixed by remove systemd service and starting the program by other means.

**Comment by CSRaghunandan** [comment]
I have the same issue. Any idea why this is happening? It used to work fine until today and now I'm getting this error everytime I logout and login or wake from suspend
