### ISSUE TITLE
Redshift ignores `redshift.conf` by default

### ISSUE THREAD

**Issue by IAMtheIAM** [jonls/redshift#666]
**Describe the bug**
Adding `~/.config/redshift/redshfit.conf` does nothing when loading redshift or redshift-gtk. It must be explicitly loaded like `redshift-gtk -c /home/user/.config/redshift/redshift.conf` (from the menu or panel) or `redshift-gtk -c ~/.config/redshift/redshift.conf` (from the cli)

- [x] [I have checked the FAQ](https://github.com/jonls/redshift/blob/master/README.md#faq) and my issue is not mention there.

**To Reproduce**
1. Add `~/.config/redshift/redshfit.conf` with valid config
2. Run command `redshift`

**Expected behavior**
It should load the conf file by default, and it should already exist instead of needing to create it from the sample provided here.

**Software versions (please complete the following information):**
 - OS: [e.g. Linux/Windows/macOS] Linux
 - Redshift version: [e.g. 1.11, run `redshift -V` in a terminal] 1.11
 - Distribution: [e.g. Ubuntu] Mint 19
 - Redshift installed from: [e.g. "using apt-get", "built from source"] apt

**Comment by jonls** [comment]
You are using Redshift 1.11. Please refer to the documentation for Redshift 1.11. The config file was located in `~/.config/redshift.conf` prior to Redshift 1.12. Starting from Redshift 1.12 the config file can be located in either `~/.config/redshift.conf` or preferably `~/.config/redshift/redshift.conf`. Until you are able to upgrade to 1.12 please keep the config file at `~/.config/redshift.conf`.

**Comment by IAMtheIAM** [comment]
Alright, I wonder how I got 1.11 - maybe the PPA was not yet up to date. I'll try again, thanks!
