### ISSUE TITLE
Unknown configuration setting `fade'.

### ISSUE THREAD

**Issue by IAMtheIAM** [jonls/redshift#668]
**Describe the bug**
Using config file, set `fade=0` and start redshift. Results in `Unknown configuration setting 'fade'.`

**Software versions (please complete the following information):**
 - OS: [e.g. Linux/Windows/macOS] Linux
 - Redshift version: [e.g. 1.11, run `redshift -V` in a terminal] 1.11
 - Distribution: [e.g. Ubuntu] Mint 19 
 - Redshift installed from: [e.g. "using apt-get", "built from source"] apt

**Comment by jonls** [comment]
You're using redshift 1.11. Please refer to the documentation for redshift 1.11. The `fade` option was added in 1.12. Since there are multiple other people reporting this issue, please search for those issue reports if you need more details on this issue.
