### ISSUE TITLE
Update Ubuntu PPA to 1.12

### ISSUE THREAD

**Issue by nikolayhg** [jonls/redshift#677]
**Is your feature request related to a problem? Please describe.**
[Ubuntu PPA](https://launchpad.net/%7Edobey/+archive/ubuntu/redshift-daily/+packages) contains the 1.11 version.

**Describe the solution you'd like**
Add the 1.12 version to the [Ubuntu PPA](https://launchpad.net/%7Edobey/+archive/ubuntu/redshift-daily/+packages).

**Comment by jonls** [comment]
@dobey Would you be able to update the PPA?

**Comment by dobey** [comment]
Managed to get builds working again. You can close this.
