### ISSUE TITLE
Redshift won't use config file

### ISSUE THREAD

**Issue by geckon** [jonls/redshift#680]
**Redshift won't use config file**

- [x] [I have checked the FAQ](https://github.com/jonls/redshift/blob/master/README.md#faq) and my issue is not mention there.

**To Reproduce**
1. Create a conf file in `~/.config/redshift/redshift.conf`
2. Run `redshift`
3. Notice that the conf file is not used

**Expected behavior**
The conf file is used.

**Error output/logs/screenshots**
Specifically I set these options among others:
```
location-provider=manual

[manual]
lat=50.1
lon=14.5
```

If I run redshift though, it will still try and use `geoclue2` and fail:
```
$ redshift -v
Trying location provider `geoclue2'...
Using provider `geoclue2'.
Unable to start GeoClue client: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Geolocation disabled for UID 1000.
Unable to connect to GeoClue.
Unable to get location from provider.
```

If I require the conf file explicitly, it will work as expected though:
```
$ redshift -v -c ~/.config/redshift/redshift.conf 
Location: 50.10 N, 14.50 E
Temperatures: 5700K at day, 3500K at night
Solar elevations: day above 3.0, night below -6.0
Brightness: 1.00:1.00
Gamma (Daytime): 0.800, 0.800, 0.800
Gamma (Night): 0.800, 0.800, 0.800
Status: Enabled
Period: Daytime
Color temperature: 6492K
Brightness: 1.00
Color temperature: 6484K
Color temperature: 6476K
Color temperature: 6468K
Color temperature: 6460K
Color temperature: 6452K
(...)
```

**Software versions (please complete the following information):**
 - OS: Linux
 - Redshift version: 1.11
 - Distribution: OpenSUSE Leap 15.0
 - Redshift installed from: using `zypper`

**Comment by geckon** [comment]
I found out that if I move the config file to `~/.config/redshift.conf`, it's used and everything works as expected.

**Comment by jonls** [comment]
Since you're using Redshift 1.11, `~/.config/redshift.conf` is the only place that's supported.
