### ISSUE TITLE
Lubuntu 18.10 and geoclue2

### ISSUE THREAD

**Issue by dcalixto** [jonls/redshift#683]
After install the lubuntu 18.10 and install redshift from the applications program
Redshift start to complain about geoclue2

please somoeone can indicate a fix for this:
thx

![redshift](https://user-images.githubusercontent.com/1009077/47682984-e5bc9780-dbac-11e8-9f28-012038449811.png)

**Software versions (please complete the following information):**
 - OS: [e.g. Linux]
 - Redshift version: [e.g. 1.11, run Features`redshift -V` in a terminal]
 - Distribution: [e.g. Lubuntu 18.10]
 - Redshift installed from: [e.g. "using apt-get", "built from source"]

**Comment by barkingbandicoot** [comment]
Same issue on Kubuntu 18.10

**Comment by jonls** [comment]
Thanks for the issue report. Please see issue https://github.com/jonls/redshift/issues/636. The last comment has a summary: https://github.com/jonls/redshift/issues/636#issuecomment-412295941. You're likely missing the geoclue agent.
