### ISSUE TITLE
Reduce the amount of blue light

### ISSUE THREAD

**Issue by birdie-github** [jonls/redshift#691]
I'm now running `redshift -O 3000` and I've just made a photo of my laptop monitor and I cannot say that the blue component of the light has measurably been decreased - I mostly see that the red component is larger than the green/blue components.

My question is, can you add an option to just reduce the blue light intensity while leaving red and green intact?

I tried running `xgamma -bgamma 0.1` but it doesn't and shouldn't work as expected for completely white images like most websites and most applications.

I'm asking this because my laptop monitor is extremely bluish - so I don't really need to adjust the red component intensity - it would be great if I could just negate the blue light.

My OS is Fedora Linux. Redshift is at version 1.11.

**Comment by marcospb19** [comment]
Seems like -O option will always make the red intensity go up, if you want to just decrease blue light, maybe you should set the color using -O to a value closer to the default temperature, and use -g option to gamma correction (Works to me)
-b (red):(green):(blue), values go from 0 to 1.0
See if this works to you
Something like `redshift -g 1:0.75:1 -O 5500`

**Comment by birdie-github** [comment]
This almost works except:

1) It makes green dimmer for the reasons which are beyond my understanding
2) it changes the blue color gamma only slightly while I either want to make it substantially dimmer, i.e. change its brightness instead

I'm now using `redshift -g 1:0.5:1 -O 5500` but I'm far from content.

If Linux or/and redshift cannot/doesn't allow to change color brightness then this issue might be safely closed :-(

**Comment by birdie-github** [comment]
`xcalib -blue 1 10 10 -alter`

does exactly what I need.
