### ISSUE TITLE
Redshift Doesn't Recognize lat and lon or time issues?

### ISSUE THREAD

**Issue by kawaiiamber** [jonls/redshift#699]
In ~/.config/redshift.conf , I set lat=39.7 and lon=-104.9 , yet Redshift doesn't seem to recognize it.

This is my redshift.conf file:

[redshift]
temp-day=6500
temp-night=4500
fade=1
brightness-day=1.0
brightness-night=0.6
dawn-time=06:30-07:00
dusk-time=20:30-21:00
adjustment-method=randr
location-provider=manual

[manual]
lat=39.7
lon=-104.9

Running $ redshift doesn't do anything. Running $ sudo redshift produces the error.

Trying location provider `manual'...
Latitude and longitude must be set.

I've tried being more specific with lat and lon vars, but that didn't do anything.

Something else is interesting, I set my .conf file as similar to the example from the man page as possible as:

[redshift]
temp-day=6500
temp-night=4500
fade=1
brightness-day=1.0
brightness-night=0.6
adjustment-method=randr
location-provider=manual

[manual]
lat=39.7
lon=-104.9

Running $ redshift , the program  seems to work. However, running $ sudo redshift , it doesn't seem to recognize the lat lon again saying:

Trying location provider `manual'...
Latitude and longitude must be set.

Why would running redshift as root make it bug out like this? Why would adding these time vars cause it to bug out? In both cases, running as root makes it bug out. Giving it a specific time to transition makes it not work at all when running as anon.

 - OS: Linux
 - Redshift version: 1.12
 - Distribution: VOID
 - Redshift installed from: xbps (X Binary Package System from VOID)

**Comment by sim590** [comment]
May be related to this, I have noticed that redshift doesn't adjust screen temperature when time changes. I have a service running :

**Comment by zackarycw** [comment]
> May be related to this, I have noticed that redshift doesn't adjust screen temperature when time changes. I have a service running :
> 
> ```
> # /usr/lib/systemd/user/redshift.service

Possibly. I don't use systemd to start my services. I use the runit init system. If these things are related, it would seem that it spans beyond the init system.

**Comment by sim590** [comment]
I don't see the trouble anymore since I added variables `DISPLAY` and `XAUTHORITY` to the running environment (see [this][post] for details).

[post]: https://github.com/jonls/redshift/issues/273#issuecomment-462095152

**Comment by astralchan** [comment]
Oops, I just realised this is still open. This was quite a while ago and I no longer have this issue.
