### ISSUE TITLE
No process to kill even though multiple instances have turned screen very red

### ISSUE THREAD

**Issue by 6lancmange** [jonls/redshift#700]
I was trying to find a way to make Redshift alter the laptop screen, but not the connected TV. Looking at the issues, I found the command xrandr which I tried, but at some point I thought I would maybe get some help, but ended up accidentally running another instance of Redshift. The screen got redder. I think I panicked and I closed the (correctly running, autostarted) Redshift with the drop-down menu. The accidental, non-gui one was still running, though. I closed the terminal with the X in the corner, hoping that it would close Redshift – since normally, it would. I've had a problem with this before when I didn't use nohup and couldn't close the terminal in order to keep Redshift running. But this time, display remained red. I opened the terminal again and listed all processes to kill the multiple Redshifts, and there weren't any. I think I run ANOTHER one again to see what happens and take a screenshot. I'm gonna have to restart the laptop now, but I would still like to know how to avoid this in the future or fix in case it happens again.

![screenshot from 2019-01-19 03-09-08](https://user-images.githubusercontent.com/26997029/51420945-bb6ceb80-1b97-11e9-8f98-0ef584abe628.png)

I opened another tab in the terminal and listed processes. This time, there was a single redshift process running – the one in the first tab, I guess. I killed it. The original tab closed, and the screen went back to a more neutral tone. But I can see that it is not completely gone. Redshift sometimes "hiccups" and the screen instantaneously goes blue for a moment, then goes back to what it's supposed to be, so I can tell that what it is now is not the temperature it would normally be, without any Redshift running. What does Redshift do that's so hidden/permanent that it can remain even when there isn't a redshift process running?

- [x] [I have checked the FAQ](https://github.com/jonls/redshift/blob/master/README.md#faq) and my issue is not mentioned there.

**To Reproduce**
1. Run redshift-gtk and redshift, from the terminal. More than one redshift is best. I checked: the culprit command was "redshift xrandr:help". Didn't help.
2. Close redshift-gtk using the drop-down menu. Kill the running redshift process.

**Expected behavior**
Screen becomes regular, high temperature colour, unaltered by Redshift.

**Actual behaviour**
Screen stays reddened, but there's no more redshift processes to kill.

**Software versions (please complete the following information):**
 - OS: Ubuntu 18.04.1 LTS
 - Redshift version: 1.12
 - Distribution: Ubuntu
 - Redshift installed from: built from source

Okay I think the screenshot is not really necessary because I had a problem with the terminal getting stuck, but now I think that's just the way it works and you can open new tabs or windows. TIL

**Comment by matecrn** [comment]
I ran into the same thing last night actually. I ended up running `sudo killall Xorg` and it fixes the problem without a reset. However it logs me out, but it still fixes it.

I don't think I've ever had this problem on Debian Stretch, but I've had it on Debian Testing and Arch. Probably has something to do with the newer version.

**Comment by jonls** [comment]
Use `redshift -x` to reset after you've killed the last instance. Also, regarding the "hiccups", it's likely a different application on your system. See the FAQ entry "Why does the redness effect occasionally switch off for a few seconds?".

**Comment by prosoitos** [comment]
I noticed that `kill`, `pkill`, `killall`, which all default to signal 15 allow redshift to reset the default monitor values as part of the cleanup.

But with signal 9 (e.g. `kill -9`, `pkill -9`, etc.), it is killed instantly and it then leaves the settings behind (which makes sense). In that case, a `redshift -x` is needed to reset.

I thought I'd mention it here in case it helps others figuring out why they have settings left behind.

Personally, I am very happy with this behaviour: as many others, I have flickering issues when 2 instances are running, depending on how they are launched. So I take advantage of this (launch, then `kill -9` the second instance) to set things up and not have the flickering.
