### ISSUE TITLE
Can you make it so you can use redshift based on your clock and not location?

### ISSUE THREAD

**Issue by FrostKnight** [jonls/redshift#702]
I think it would be awesome to not have to use geoclue and thus your location won't be required of you.  

Would it be at all possible to implement this somewhere down the road?
Either a standalone version or implement it into the normal version? 

If you release a beta, let me know and within a week, I will be glad to try it out.  

Don't get me wrong, I don't mind geoclue being optionally used for this, but I would so love to have a clock based option.  As in the hardware clock. :)

**Comment by PAPPL** [comment]
This would be great.
Spend a lot of time trying to make it run.
I installed Redshift (sudo apt install redshift-gtk) on Ubuntu MATE and Ubuntu Budgie and it gets an geoclue2 error on startup, even if 
- Geolocation is enabled in settings -> privacy.
- run as `sudo redshift-gtk`
- Add this to /etc/geoclue/geoclue.conf:
```
`[redshift]`
`allowed=true`
`system=false`
`users=`
```

Still:"_Unable to start GeoClue client: GDBus.Error......._"

Only setting lat / long manually  in ~/.config/redshift.conf did the trick.

Please add a time setting (e.g. 8pm to 6am, but editable in redshift.conf) and set as fallback if geoclue is not working.

**Comment by jonls** [comment]
This is already implemented in Redshift 1.12. See the man page for more information.

**Comment by PAPPL** [comment]
i read the man page, but i can't see a time based setting (except colortemperature option -t for Kelvin).
It is not implemented, because i got all these geoclue errors with v.1.12 and it does not fall back to a time preset.

**Comment by jonls** [comment]
@PAPPL You need to configure the time intervals in the configuration file: https://github.com/jonls/redshift/blob/master/redshift.1#L125

**Comment by FrostKnight** [comment]
Well could you put the exact instructions on the wiki on how to do this? Just  curious.  I am glad to know there are workarounds, I found one myself by searching online but my distro doesn't like the implications, so I wondered if you could make it more  clear how to have set by default to the current time on the hardware. :) Just add it to the wiki right?
