### ISSUE TITLE
Colour Temperature keeps Changing

### ISSUE THREAD

**Issue by sangoku116** [jonls/redshift#724]
Whenever redshift is enabled the colour temperature keeps changing between the set value and the standard colour temperature when redshift is not enabled. If I use the command `redshift -P -O 4000` it changes once and then back to default colour temperature in a second. I have tried using vidmode instead of randr, the issue remains.
OS: Manjaro Linux Kernel 5.1.8
DE: XFCE
Redshift Version: 1.12

**Comment by sangoku116** [comment]
This happens during transition which lasts for over an hour. My screen colours have been fine all day until transition happened.

**Comment by bpiero** [comment]
+1
