### ISSUE TITLE
Getting No more methods to try when running from CLI (wayland + sway). Minus7 fork

### ISSUE THREAD

**Issue by Spectrik** [jonls/redshift#734]
**Describe the bug**

Hi,

I am running Fedora 30 (Wayland + wlroots compositor + sway window manager). I have compiled redshift from source from this fork:

[Redshift minus fork](https://github.com/minus7/redshift/tree/wayland)

According to:

[Sway wiki](https://github.com/swaywm/sway/wiki#redshift)

this should be working. However when I try to run it like this for example:

```
./bin/redshift -l XX:YY -v
Solar elevations: day above 3.0, night below -6.0
Temperatures: 6500K at day, 4500K at night
Brightness: 1.00:1.00
Gamma (Daytime): 1.000, 1.000, 1.000
Gamma (Night): 1.000, 1.000, 1.000
No more methods to try.
```

or  

```
./bin/redshift -b 1
Trying location provider `manual'...
Latitude and longitude must be set
```

I am not able to make it working. Hopefully I am not doing something wrong. Any help is appreciated here! Thank you.

**Error output/logs/screenshots**

```
./bin/redshift -l XX:YY -v
Solar elevations: day above 3.0, night below -6.0
Temperatures: 6500K at day, 4500K at night
Brightness: 1.00:1.00
Gamma (Daytime): 1.000, 1.000, 1.000
Gamma (Night): 1.000, 1.000, 1.000
No more methods to try.
```

**Software versions (please complete the following information):**
 - OS: Linux
 - Redshift version: 1.12
 - Distribution: Fedora 30
 - Redshift installed from: build from source (fork https://github.com/minus7/redshift/tree/wayland)

**Comment by minus7** [comment]
Fedora 30 has sway 0.15 which is *not* based on wlroots and uses a different gamma protocol. I strongly suggest you upgrade to sway 1.0. You'll have a much more pleasant experience and my redshift branch will also work

**Comment by Spectrik** [comment]
Thank you very much for the suggestion.
