### ISSUE TITLE
why does redshift depend on location at all?

### ISSUE THREAD

**Issue by nrdxp** [jonls/redshift#736]
**Is your feature request related to a problem? Please describe.**
I don't understand why the needed complexity of adding a location provider. Every computer has a clock built right into it.

**Describe the solution you'd like**
Just change the screen based on the time in the system clock

**Additional context**
Location is a PITA to setup and a privacy concern. I don't even understand how the system clock was overlooked for this in the first place

**Comment by Toreno96** [comment]
The time alone is insufficient, because time of dusk and dawn are not a fixed value.
What's more, I suppose that change in dusk/dawn time depends on the location, that's probably way it is required.

**Comment by maandree** [comment]
The clock is not sufficient to determine what time it is. You need the UTC time in combination with the longitude. Just take a look at for example China and Greenland on a timezone map. Or even Europe. The timezones are divided conveniently and not optimally to match the actual location.

The latitude is needed to determine how much sun there is in your location, depending on the time of day and day of year. (If you want to be extremely exact you also need altitude.)

**Comment by nrdxp** [comment]
while I see your point, I think time of day plus time of year and the locale should be enough information to provide a reasonable approximation.

**Comment by maandree** [comment]
Your locale is not useful information as it does not necessarily correspond with your location. I have my locale set to en_GB despite not living in great Britain, the timezone would be better. Regarding security, you don't have to input your exact location. Just take the coordinates as found on Wikipedia for the largest city within 15° or even 30°.

**Comment by trymeouteh** [comment]
Personally I would prefer using the clock by default and disabling the location service by default for privacy. I am not against having location as a means to detect dawn/dusk but privacy should come by default put of the box.

**Comment by RsPlayer** [comment]
I think its better to let the user modify the day and night interval, sometimes I want to use night mode at evening. I think redshift should be more configurable for advanced users.

**Comment by maandree** [comment]
@trymeouteh 
Exactly what is the privacy issue? As far as I understand it, in worse case — the common case — there is some server on the Internet that knows that you have some reason to know your location and do not have a GPS device to tell your location.

I know you mean latitude, but altitude would be a nice addition, just in case you are in a particularity tell skyscraper.

@RsPlayer 
You can modify the day and night interval by setting `elevation-high` and `elevation-low` in the config-file. It also looks like you can set it by time nowadays by setting `dawn-time` and `dusk-time`, I don't know if redshift will ignore location if this it set, but it should if everything is implemented as one would expect.
