### ISSUE TITLE
Redshift crashes after starting it as a user service

### ISSUE THREAD

**Issue by Jacotsu** [jonls/redshift#742]
When i start the service with `systemctl --user start redshift` it crashes with the following log

- [x] [I have checked the FAQ](https://github.com/jonls/redshift/blob/master/README.md#faq) and my issue is not mention there.

**To Reproduce**
1. Install redshift, wlroots and sway version 1.1-rc1-51-gf5d1c272
2. Set `adjustment-method=wayland` in `.config/redshift.conf`
3. Start logging with `journalctl --user -u redshift`
4. Start the service with `systemctl --user start redshift`
5. See error

**Expected behavior**
Automatic wayland display detection

**Error output/logs/screenshots**
```
ott 25 17:44:42 stufa systemd[3362]: Started Redshift display colour temperature adjustment.
ott 25 17:44:42 stufa redshift[3818]: Could not connect to wayland display, exiting.
ott 25 17:44:42 stufa redshift[3818]: Failed to start adjustment method wayland.
ott 25 17:44:42 stufa systemd[3362]: redshift.service: Main process exited, code=exited, status=1/FAILURE
ott 25 17:44:42 stufa systemd[3362]: redshift.service: Failed with result 'exit-code'.
ott 25 17:44:42 stufa systemd[3362]: redshift.service: Service RestartSec=100ms expired, scheduling restart.
ott 25 17:44:42 stufa systemd[3362]: redshift.service: Scheduled restart job, restart counter is at 4.
```

**Software versions (please complete the following information):**
 - OS: Linux
 - Redshift version: 1.12
 - Distribution: Ubuntu 19.10
 - Redshift installed from: PPA

**Possible Fix**
By using the following service file redshift starts normally as a user service and works
```
[Unit]
Description=Redshift display colour temperature adjustment
Documentation=http://jonls.dk/redshift/
After=display-manager.service

[Service]
ExecStart=env WAYLAND_DISPLAY=wayland-0 /usr/local/bin/redshift
Restart=always

[Install]
WantedBy=default.target
```
Probably there's a better way to fix this issue

**Comment by WhyNotHugo** [comment]
There are two things that you'd need to do to work around this:

1. Make sure your `WAYLAND_DISPLAY` env setting gets exported before services start up. You can achieve this with `systemctl --user import-environment`.
2. Looks like `WantedBy=default.target` is wrong. This will make redshift start as soon as your session starts, without waiting for your graphical session to start. It should be `WantedBy=graphical-session.target`.

I'll put a PR up to update the service file for the second item. That aside, this is what I have as a last line of `sway/config`, in case you're using sway:

    exec "systemctl --user import-environment; systemctl --user start graphical-session.target"
