### ISSUE TITLE
Research on night mode screens suggests bluer is better

### ISSUE THREAD

**Issue by Joshuaalbert** [jonls/redshift#748]
An article just came out suggesting redshift should be blue shifting https://www.theguardian.com/technology/shortcuts/2019/dec/17/not-such-a-bright-idea-why-your-phones-night-mode-may-be-keeping-you-awake

**Comment by VoidNoire** [comment]
The study cited in that article was only conducted on mice, not humans. Presently, there's just [more research and evidence that show that suppressing blue light at night is better](https://old.reddit.com/r/technology/comments/ednbdo/night_mode_light_is_more_harmful_for_eyes_and/fblpx1o/). But if you really want to, you can just use the redshift's `-t` option to set bluer temperatures at night and yellower temperatures at daytime, for example: `redshift -t 5000K:10000K`.
