### ISSUE TITLE
Grayscale mode

### ISSUE THREAD

**Issue by blut** [jonls/redshift#755]
Hello,

I'm looking for a way to gradually decolorize my screen in the evening hours, similar to the Wind Down feature on Android.
Grayscale could be an optional mode.

Alternatives would be modifying the xorg server or using pluggins for each application.

I tried editing the colorramp.c file, but couldn't manage to resonably adjust colors.

Kind regards

**Comment by 1vasari** [comment]
I'm interested in doing this also - would you mind updating here if you make any breakthroughs?

**Comment by 1vasari** [comment]
Oh... Per #626 and #364 it seems that Redshift cannot be customized to do a grayscale transform. This issue could probably be closed.

**Comment by blut** [comment]
Closed as duplicate of #626
