### ISSUE TITLE
Redshift not switching on/off when clicking on the tray icon (Gnome 3.12)

### ISSUE THREAD

**Issue by cristobaltapia** [jonls/redshift#76]
Normally clicking on the tray icon should enable/disable redshift. Since I updated to Gnome 3.12 it doesn't work any more. Could this be a bug?

**Comment by Arnonjac** [comment]
A very simple way to disable Redshift is: Menu>Administration>System monitor>Processes. Find Redshift in the list, right click on it, and use “end process “ or “kill process". Redshift will be off. If you will like to start it again – just click the icon and it will start. To find the right color temperature - watch this link: https://www.maketecheasier.com/protect-eyes-redshift-linux/
Another way - go to Settings>Startup applications, and than to put Redshift on “off” (or remove it from the startup applications list), and now reboot the computer. Redshift will be off. If you will like to start it again – just click the icon and it will start.
