### ISSUE TITLE
A slide switch so set the temperature

### ISSUE THREAD

**Issue by TornaxO7** [jonls/redshift#760]
**Is your feature request related to a problem? Please describe.**
I try to set the redshift temperature as low as possible, to protect my eyes but sometimes it's so low that I can't read a text anymore (e.g. the text has blue words). Then I need to kill redshift and then everything is instantly bright and my eyes need some time to adjust to the new brightness which hurts a little bit.

**Describe the solution you'd like**
A slide switch to adjust the temperature at the tray-applet of redshift.

**Describe alternatives you've considered**
I'm using this script at this moment:
```bash
#!/bin/bash
result=$(ps -C redshift | grep -o redshift)

if [ "$result" == "redshift" ]; then
	redshift -x
  	killall redshift-gtk
	killall redshift
	#notify-send "Deactivated redshift" -t 1000 
fi

if [ "$1" == 0 ]; then
	redshift-gtk -P -r -c ~/.config/redshift/redshift.conf &
	notify-send "Redshift strong" -t 1000

elif [ "$1" == 1 ]; then
	redshift-gtk -P -r -c ~/.config/redshift/redshift_med.conf&
	notify-send "Redshift medium" -t 1000

elif [ "$1" == 2 ]; then
	redshift-gtk -P -r -c ~/.config/redshift/redshift_light.conf &
	notify-send "Redshift light" -t 1000
fi
```
it will be executed if I click on a button of my polybar. <br>
As you can see I'm using three different scripts to adjust the temperature. Probably you're asking why I'm doing this instead of using for example `geoclue2`: The temperature isn't low enough for me so I've set the temperatures manually but as I already mentioned I need to set the temperature only a little bit higher than before and the other config files are often rough.

**BUG?: redshift-gtk -c <Path> doesn't work for me somehow...**

**Additional context**
OS: Arch Linux
redshift version: redshift 1.12

PS: Sorry for my bad english... if you don't understand something than you can ask me and I'll try to explain in better.

**Comment by jonls** [comment]
Blocked on something like #54 which will allow dynamic adjustments.
