### ISSUE TITLE
redshift randr mode always fails (xauth error?)

### ISSUE THREAD

**Issue by tguruswamy** [jonls/redshift#763]
**Describe the bug**
I'm seeing this issue on openSUSE Tumbleweed for the last few days. redshift-1.12 randr mode no longer works.
However it does work after `xhost +`
Seems to be something has changed with xauth, but not obvious where. No SELinux or AppArmor set up.

- [x] [I have checked the FAQ](https://github.com/jonls/redshift/blob/master/README.md#faq) and my issue is not mention there.

**To Reproduce**
Run `redshift -o -m randr`.

**Error output/logs/screenshots**
```
> redshift -v -o -m randr
Solar elevations: day above 3.0, night below -6.0
Temperatures: 6500K at day, 2700K at night
Brightness: 1.00:0.60
Gamma (Daytime): 1.000, 1.000, 1.000
Gamma (Night): 1.000, 1.000, 1.000
No protocol specified
No protocol specified
`RANDR Query Version' returned error -1
Initialization of randr failed.

> strace -e file redshift -o -m randr
execve("/usr/bin/redshift", ["redshift", "-o", "-m", "randr"], 0x7ffc45c09b18 /* 104 vars */) = 0
...
openat(AT_FDCWD, "/home/~/.config/redshift/redshift.conf", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/~/.config/redshift.conf", O_RDONLY) = 3
access("/run/user/1000/xauth_yuXbHH", R_OK) = 0
openat(AT_FDCWD, "/run/user/1000/xauth_yuXbHH", O_RDONLY) = -1 EACCES (Permission denied)
No protocol specified
No protocol specified
`RANDR Query Version' returned error -1
openat(AT_FDCWD, "/usr/share/locale-langpack/en_GB/LC_MESSAGES/redshift.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/locale/en_GB/LC_MESSAGES/redshift.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/locale-langpack/en/LC_MESSAGES/redshift.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/locale/en/LC_MESSAGES/redshift.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
Initialization of randr failed.
+++ exited with 1 +++
```

```
> xhost
access control enabled, only authorized clients can connect
> ls -l /run/user/1000/xauth_yuXbHH
-rw------- 1 me users 96 Jul 15 16:46 /run/user/1000/xauth_yuXbHH
> env | grep -i XAUTH
XAUTHORITY=/run/user/1000/xauth_yuXbHH
```

**Software versions (please complete the following information):**
 - OS: Linux
 - Redshift version: 1.12
 - Distribution: openSUSE Tumbleweed
 - Redshift installed from: oS RPMs

**Comment by Vogtinator** [comment]
> openat(AT_FDCWD, "/run/user/1000/xauth_yuXbHH", O_RDONLY) = -1 EACCES (Permission denied)

You can open that file manually, right? Is redshift running as your regular user account?

**Comment by tguruswamy** [comment]
Yes and yes. Regular file permissions are 600, and no fancy acl's. I don't know what else could be interfering (no SELinux, think I disabled AppArmor)

If I run other graphical programs, no issue:

```
> strace -e file xterm
access("/run/user/1000/xauth_yfDehn", R_OK) = 0
openat(AT_FDCWD, "/run/user/1000/xauth_yfDehn", O_RDONLY) = 4
```

compare to
```
> strace -e file redshift -v -o -m randr
access("/run/user/1000/xauth_yfDehn", R_OK) = 0
openat(AT_FDCWD, "/run/user/1000/xauth_yfDehn", O_RDONLY) = -1 EACCES (Permission denied)
Initialization of randr failed.
+++ exited with 1 +++
```

after running `xhost +`, the file access is still denied, but redshift works
```
> xhost +
> strace -e file redshift -v -o -m randr
access("/run/user/1000/xauth_yfDehn", R_OK) = 0
openat(AT_FDCWD, "/run/user/1000/xauth_yfDehn", O_RDONLY) = -1 EACCES (Permission denied)
+++ exited with 0 +++
```

**Comment by tguruswamy** [comment]
Problem solved! I had thought AppArmor is disabled, but in fact it was being silently re-enabled. AppArmor is not liking the move of the Xauthority file to /run/user/.../xauth. We will need to update the shipped AppArmor profile, in particular the abstractions/X which is supposed to cover what's needed.

Quick patch is add
`owner /{,var/}run/user/*/xauth_* r,`
to
`/etc/apparmor.d/local/usr.bin.redshift`

**Comment by Vogtinator** [comment]
Great! I filed https://bugzilla.opensuse.org/show_bug.cgi?id=1174293 to get that fixed.
