### ISSUE TITLE
Using One Shot mode once in Ubuntu 20.04 Xorg leads to unidirectional color shift (initial value bug)

### ISSUE THREAD

**Issue by chaitanya-m** [jonls/redshift#765]
**Describe the bug**

Using redshift in one shot mode on Ubuntu 20.04 Gnome XOrg

`redshift -O 9000`
works, but if I follow it up with 

`redshift -O 6000`

The screen becomes much bluer (instead of becoming redder!), and continues to do so regardless of what values are used.

With a warmer initial value, the screen gets continually redder.

A workaround is possible, by using `redshift -x` to reset everything.

- [x] [I have checked the FAQ](https://github.com/jonls/redshift/blob/master/README.md#faq) and my issue is not mention there.

**To Reproduce**
1. Boot into Ubuntu 20.04 Gnome, XOrg
2. `redshift -O 9000`
3. `redshift -O 6000`
4. `redshift -O 3000`

**Expected behavior**
The screen is expected to get warmer from step 3 onwards, but it gets bluer instead.

**Error output/logs/screenshots**

**Software versions (please complete the following information):**
 - OS: Linux
 - Redshift version: 1.12
 - Distribution: Ubuntu 20.04, Gnome on XOrg
 - Redshift installed from: using apt install

**Comment by KT-lcz** [comment]
you can append '-P' with cmd 'redshift -O 9000',
eg: 'redshift -O 9000 -P'
