### ISSUE TITLE
be less verbose when verbose (for logging)

### ISSUE THREAD

**Issue by vuvova** [jonls/redshift#77]
I like to keep logs of what redshift is doing, so I run it with -v, redirecting the output to a file. But it's just way too verbose. This patch (https://gist.github.com/vuvova/2024317db7b211c9fd3c) contains three distinct changes that help for such a use case:
1. it increases the sleep time from 5 sec to 5 min after every adjustment that didn't change the temperature (most of the time, that is)
2. it makes -v not to print "Daytime", etc and the new temperature when they're the same as the previous time (when the temperature didn't change). As usual specifying -v twice (-v -v) gives more verbosity, that is — restores the old behavior, printing the temperature always.
3. It disables output buffering for stdout (otherwise the log becomes pretty useless).
The patch is for 1.7

**Comment by jonls** [comment]
I think all of your issues should be fixed in Redshift 1.10. Increasing the time between adjustments cannot yet be done from the configuration file but you can set `SLEEP_DURATION` in `redshift.c`. I'm going to close this issue and open a new one with the "smart adjustment" suggestion.
