### ISSUE TITLE
我打不开Redshift

### ISSUE THREAD

**Issue by L-QF** [jonls/redshift#796]
我打不开Redshift

![2021-01-19 16-14-13屏幕截图](https://user-images.githubusercontent.com/58257723/105006341-783d0000-5a71-11eb-8276-e5e7dbbca706.png)

并且我已更新“sudo apt-get install geoclue-2.0”
ubuntu 18.04  通过“sudo apt-get install redshift redshift-gtk”安装

**Comment by maxencedubois** [comment]
Hello!

Got the same problem on my side. I'm on Debian 10, version 1.12.2 for my redshift. If I try the location URL in config file (https://location.services.mozilla.com/v1/submit?key=geoclue), I get this :

![Screenshot_2021-01-19 https location services mozilla com](https://user-images.githubusercontent.com/9469099/105094012-e69ab600-5aa3-11eb-9f49-8bd3bc8e6007.png)

Looks like Mozilla location service is down.

**Comment by L-QF** [comment]
你好，我已解决我的问题通过将ubuntu系统中的定位服务打开，你可以尝试相同的操作！
