### ISSUE TITLE
我写入了配置文件但是没有用

### ISSUE THREAD

**Issue by L-QF** [jonls/redshift#797]
我已经在./config/reshift/redshift.conf.写入了如下的配置文件，但是他的经纬度被并没有什么变化，并且一直显示的是本机的地址，ubuntu 18.04  

[redshift]
;设置白天的色温
;temp-day = integer

;设置晚上的色温
;temp-night = integer

;是否渐进地调整色温
transition = 1

;调整白天的屏幕亮度
;brightness-day = 0.1-1.0

;调整晚上的屏幕亮度
;brightness-night = 0.1-1.0

;设置太阳多高了才算是白天
;elevation-high = decimal

;设置太阳多高了才算是晚上
;elevation-low = decimal

;对比度调整(无论白天还是晚上)
;gamma = R:G:B

;白天进行的对比度调整
;gamma-day = R:G:B

;晚上进行的对比度调整
;gamma-night = R:G:B

;调整色温的方法，可以用 redshift -m list 来查看支持的方法，默认为 randr.
;adjustment-method = name

;指定获取经纬度的方法，可以用 redshift -l list 来查看支持的方法,默认为 geoclue2.
location-provider = manual

[manual]
;以下配置项在 [manual] section 下
;设置纬度
;a
lat = 21.14
;b
;lat = 32.45

;设置经度
;a
lon = 99.48
;b
;lon = 125.46

**Comment by dandv** [comment]
Did you notice that this repository is in English?
