### ISSUE TITLE
Redshift is not working after making redshift.config

### ISSUE THREAD

**Issue by itzayush18** [jonls/redshift#833]
I am using Redshift for many days. It automatically set the temperature at night. Now I wanted to set day-temp, then I made a config file of redshift and written the value of day-temp I need. After that When I am opening the redshift this problem is coming....(see attached file)
![Screenshot_2021-08-20_18-25-25](https://user-images.githubusercontent.com/89258126/130236478-69a80f9c-b6ce-46e5-abda-b89fdab609c4.png)
And the screen starts becoming yellow , white , blue again yellow.........continued..
Then I have to login again to fix this issue!!!

And if running gtk this error......
![Screenshot_2021-08-20_18-30-29](https://user-images.githubusercontent.com/89258126/130238105-803a6272-0db8-4e7a-9f8f-20246fd8a3a0.png)

**Comment by officialayushsharma** [comment]
> I am using Redshift for many days. It automatically set the temperature at night. Now I wanted to set day-temp, then I made a config file of redshift and written the value of day-temp I need. After that When I am opening the redshift this problem is coming....
> ![Screenshot_2021-08-20_18-25-25](https://user-images.githubusercontent.com/89258126/130236478-69a80f9c-b6ce-46e5-abda-b89fdab609c4.png)

And if running gtk this error......
![Screenshot_2021-08-20_18-30-29](https://user-images.githubusercontent.com/89258126/130237014-fa881d8b-83eb-44f4-a9d2-be87297226ef.png)

**Comment by itzayush18** [comment]
Sorry I don know It automatically started workin!!!!
