### ISSUE TITLE
Redhift is always red at daytime and nighttime

### ISSUE THREAD

**Issue by MartinX3** [jonls/redshift#843]
**Describe the bug**
Daytime and night time, always my screen is red.
The info screen is telling me that it's daytime and the color is 5700k, but it still uses the nighttime color.

- [X] [I have checked the FAQ](https://github.com/jonls/redshift/blob/master/README.md#faq) and my issue is not mention there.

**To Reproduce**
1. I just use redshift

**Expected behavior**
White at daytime.

**Error output/logs/screenshots**
I don't get any errors (terminal or journalctl)

**Software versions (please complete the following information):**
 - OS: Linux
 - Redshift version: 1.12
 - Distribution: EndeavourOS/Arch Linux
 - Redshift installed from: repo

**Comment by arch-user-france1** [comment]
How do you start redshift?

**Comment by MartinX3** [comment]
It works since some time without doing anything.
