### ISSUE TITLE
[bug] Could not connect to wayland display, exiting. Failed to start adjustment method wayland.

### ISSUE THREAD

**Issue by xj75q** [jonls/redshift#888]
**Describe the bug**
Could not connect to wayland display, exiting. Failed to start adjustment method wayland.

- [ ] [I have checked the FAQ](https://github.com/jonls/redshift/blob/master/README.md#faq) and my issue is not mention there.

**To Reproduce**
redshift -c redshift.config ,there is a error
redshift -g / -l /-t  . the err is same :

**Expected behavior**
when i use redshift -c , there is a err : fopen: Permission denied, Unable to load config file.but when i use root ,the err still appearing。
when i use redshift -v  in root ,something bring to  init conf: eg:

**Error output/logs/screenshots**

Trying location provider `geoclue2'...
Using provider `geoclue2'.
Solar elevations: day above 3.0, night below -6.0
Temperatures: 6500K at day, 4500K at night
Brightness: 1.00:1.00
Gamma (Daytime): 1.000, 1.000, 1.000
Gamma (Night): 1.000, 1.000, 1.000
Could not connect to wayland display, exiting.
Failed to start adjustment method wayland.
Trying next method...
Using method `randr'.
Waiting for initial location to become available...

**Software versions (please complete the following information):**
 - OS:linux 
 - Redshift version: redshift 1.12
 - Distribution:debian
 - Redshift installed from: sudo apt install redshift

**Comment by anaximeno** [comment]
seems related to https://github.com/jonls/redshift/issues/794
