### ISSUE TITLE
Does not seem to install using python 3.12.7 - Deprecation of imp module

### ISSUE THREAD

**Issue by fyv3r** [jonls/redshift#900]
Attempting to install redshift with python 3.12.7  produces the error message:

`ModuleNotFoundError: No module named 'imp'`

It seems that the module was removed in python 3.12 and replaced with importlib and so redshift seems to no longer install with newer python3 versions

**Comment by Ponce** [comment]
here I workaround that running "autoreconf -fi" before the configure call...

**Comment by fyv3r** [comment]
Thanks, strangely this was actually to update the slackbuild

**Comment by fyv3r** [comment]
> here I workaround that running "autoreconf -fi" before the configure call...

Thanks Ponce, strangely this was actually to update my slackbuild :)

PS Its worked
