### ISSUE TITLE
[systemd] user service files not functional -- lack "Environment=DISPLAY=:0" (v.1.9.1 Archlinux)

### ISSUE THREAD

**Issue by neitsab** [jonls/redshift#91]
Hi,

First of all thanks for writing and maintaining this program, it is one of the most essential to my daily use of computers. Really, thanks a lot for making it, moreover as libre software.

Recently I stumbled upon the [changelog for version 1.9](https://github.com/jonls/redshift/releases/tag/v1.9), which mentioned the new systemd service files. As I'm on Archlinux which uses systemd, I thought I'd give it a try so as to rationalise my service management.

However I coudn't get neither redshift-gtk nor redshift to start this way. Two separate problems are involved:
- The first one is that the redshift-gtk.service file provided by the precompiled Arch package (downloadable [here](https://www.archlinux.org/packages/community/x86_64/redshift/)) contains the wrong binary name on the ExecStart line: it refers to `/usr/bin/redshift` instead of `/usr/bin/redshift-gtk`; bug report on the distro bugtracker [here](https://bugs.archlinux.org/task/40476). May it have something to do with the way `--with-systemduserunitdir` build option acts?
- The second error concerns both service files: for them to work on Arch the option `Environment=DISPLAY=:0` must be added to the [Service] part of the service files. See [this thread on Arch forum](https://bbs.archlinux.org/viewtopic.php?pid=1417568#p1417568) for the complete details (journal entries included).

I was wondering how to debug this further, as @hdevalence didn't seem to meet this issue when he made #35.

Thanks

**Comment by genodeftest** [comment]
Still present. Has someone found a better (i.e. cleaner) solution than setting the DISPLAY variable?

**Comment by TingPing** [comment]
Submitted a fix to systemd upstream btw: https://bugs.freedesktop.org/show_bug.cgi?id=90692

**Comment by TingPing** [comment]
According to upstream systemd this is currently up to the application to handle and they don't support importing DISPLAY officially: https://bugs.freedesktop.org/show_bug.cgi?id=90692#c1

The solution basically being redhisft ship its own xinitrc file that effectively does the same thing as this: https://github.com/systemd/systemd/blob/1401ec2d34bcde406ced531a72dc46ebaf332594/xorg/50-systemd-user.sh

**Comment by q2dg** [comment]
Why not simply add a .desktop file in ~/.config/autostart folder with a "Exec=redshift ..." line?
